const ENDPOINT="https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi";
const MAX_BYTES=1500000,TIMEOUT_MS=18000;
const text=(v,n=1000)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function secret(env){const s=text(env?.BASE_API_KEY,500);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:"BASE_API_KEY"});return s}
function query(v){const s=text(v,1000);if(!s)err("ARG_REQUIRED:query",400);return s}
async function boundedText(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502,{limit:MAX_BYTES})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(u){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(u,{method:"GET",headers:{accept:"application/json","user-agent":"three-center-intelligence-base/1.0"},signal:c.signal}),raw=await boundedText(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{http_status:r.status,preview:text(raw,300)})}if(!r.ok){const auth=r.status===401||r.status===403;err(auth?"UPSTREAM_AUTH_FAILED":r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",auth?503:r.status===429?429:502,{http_status:r.status,message:text(body?.error||body?.message||raw,400)})}return body}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function normalizeDoc(d){return{title:d?.dctitle??null,creator:d?.dccreator??null,description:d?.dcdescription??null,doi:d?.dcdoi??null,year:d?.dcyear??null,date:d?.dcdate??null,language:d?.dclang??d?.dclanguage??null,type:d?.dctype??d?.dctypenorm??null,subject:d?.dcsubject??null,identifier:d?.dcidentifier??null,link:d?.dclink??d?.dclink??null,open_access:d?.dcoa??null,collection:d?.dccollection??null,raw:d};}
export const OPERATIONS={base:["search"]};
export async function runAdapter(provider,operation,args={},env={}){if(provider!=="base"||operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation});const u=new URL(ENDPOINT);u.searchParams.set("func","PerformSearch");u.searchParams.set("query",query(args?.query));u.searchParams.set("format","json");u.searchParams.set("hits",String(clamp(args?.limit,1,20,10)));u.searchParams.set("offset",String(clamp(args?.offset,0,999,0)));u.searchParams.set("fields","dctitle,dccreator,dcdescription,dcdoi,dcyear,dcdate,dclang,dclanguage,dctype,dctypenorm,dcsubject,dcidentifier,dclink,dcoa,dccollection");u.searchParams.set("apikey",secret(env));if(args?.boost_open_access===true)u.searchParams.set("boost","oa");const body=await request(u),response=body?.response||{},docs=Array.isArray(response?.docs)?response.docs:[];return{provider:"base",operation:"search",total:Number.isFinite(Number(response?.numFound))?Number(response.numFound):null,offset:Number.isFinite(Number(response?.start))?Number(response.start):0,items:docs.map(normalizeDoc),source_mode:"BASE HTTP Search API; bounded; key-authenticated; no automatic retry"};}
