const BASE="https://api.qichacha.com";
const MAX_RESPONSE_BYTES=1000000,TIMEOUT_MS=12000,MAX_SEARCH_CHARS=200;
const S=[7,12,17,22,7,12,17,22,7,12,17,22,7,12,17,22,5,9,14,20,5,9,14,20,5,9,14,20,5,9,14,20,4,11,16,23,4,11,16,23,4,11,16,23,4,11,16,23,6,10,15,21,6,10,15,21,6,10,15,21,6,10,15,21];
const K=Array.from({length:64},(_,i)=>Math.floor(Math.abs(Math.sin(i+1))*4294967296)>>>0);
const rotl=(x,n)=>((x<<n)|(x>>>(32-n)))>>>0;
const clamp=(v,a,b,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
function md5Upper(input){const src=new TextEncoder().encode(String(input)),paddedLen=Math.ceil((src.length+9)/64)*64,b=new Uint8Array(paddedLen);b.set(src);b[src.length]=0x80;let bits=src.length*8;for(let i=0;i<8;i++){b[paddedLen-8+i]=bits&255;bits=Math.floor(bits/256)}let a0=0x67452301,b0=0xefcdab89,c0=0x98badcfe,d0=0x10325476;for(let off=0;off<b.length;off+=64){const m=new Uint32Array(16);for(let j=0;j<16;j++){const p=off+j*4;m[j]=(b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0}let a=a0,bb=b0,c=c0,d=d0;for(let i=0;i<64;i++){let f,g;if(i<16){f=(bb&c)|((~bb)&d);g=i}else if(i<32){f=(d&bb)|((~d)&c);g=(5*i+1)%16}else if(i<48){f=bb^c^d;g=(3*i+5)%16}else{f=c^(bb|(~d));g=(7*i)%16}const t=d;d=c;c=bb;bb=(bb+rotl((a+f+K[i]+m[g])>>>0,S[i]))>>>0;a=t}a0=(a0+a)>>>0;b0=(b0+bb)>>>0;c0=(c0+c)>>>0;d0=(d0+d)>>>0}const hw=w=>[0,8,16,24].map(s=>((w>>>s)&255).toString(16).padStart(2,"0")).join("");return(hw(a0)+hw(b0)+hw(c0)+hw(d0)).toUpperCase()}
function credentials(env){const appKey=String(env?.QICHACHA_APP_KEY||"").trim(),secretKey=String(env?.QICHACHA_SECRET_KEY||"").trim();if(!appKey||!secretKey)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:"QICHACHA_APP_KEY|QICHACHA_SECRET_KEY"}});return{appKey,secretKey}}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_RESPONSE_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel().catch(()=>{});throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const all=new Uint8Array(total);let off=0;for(const c of chunks){all.set(c,off);off+=c.byteLength}return new TextDecoder().decode(all)}
async function qccGet(path,params,env){const{appKey,secretKey}=credentials(env),timespan=String(Math.floor(Date.now()/1000)),token=md5Upper(appKey+timespan+secretKey),u=new URL(BASE+path);u.searchParams.set("key",appKey);for(const[k,v]of Object.entries(params||{}))if(v!==undefined&&v!==null&&String(v)!=="")u.searchParams.set(k,String(v));const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(u,{headers:{accept:"application/json",Token:token,Timespan:timespan},signal:c.signal}),raw=await readBounded(r);let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502,details:{http_status:r.status}})}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:r.status===401||r.status===403?503:502,details:{http_status:r.status}});if(body?.Status!==undefined&&String(body.Status)!=="200")throw Object.assign(new Error("QICHACHA_API_ERROR"),{status:502,details:{qcc_status:String(body.Status),message:String(body?.Message||"").slice(0,300)}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
export function qichachaMeta(){return{provider:"qichacha",integration:"official-openapi",endpoint_base:BASE,auth:"appkey-secretkey-md5-timespan",secret_names:["QICHACHA_APP_KEY","QICHACHA_SECRET_KEY"],arbitrary_url:false,read_only:true,paid_by_default:true,operation_cost_note:"company_search currently listed at CNY 0.10/request with 20 free trial requests; account eligibility and pricing remain subject to Qichacha",application_review_required:true}}
export const OPERATIONS={qichacha:["company_search"]};
export async function runAdapter(provider,operation,args,env){if(provider!=="qichacha"||!OPERATIONS.qichacha.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});if(operation==="company_search"){const searchKey=String(args?.searchKey??args?.query??"").trim();if(!searchKey)throw Object.assign(new Error("ARG_REQUIRED:searchKey"),{status:400});if(searchKey.length>MAX_SEARCH_CHARS)throw Object.assign(new Error("SEARCH_KEY_TOO_LONG"),{status:400});const pageIndex=clamp(args?.pageIndex,1,100,1),body=await qccGet("/FuzzySearch/GetList",{searchKey,pageIndex},env);return{provider,operation,paging:body?.Paging||null,items:Array.isArray(body?.Result)?body.Result.slice(0,5):[],message:String(body?.Message||"").slice(0,300),order_number:body?.OrderNumber||null}}throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501})}
export const __test={md5Upper};
