const MAX_BYTES=1200000,TIMEOUT_MS=20000;
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
const text=(v,n=8000)=>String(v??"").trim().slice(0,n);
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function required(v,name,n=500){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function secret(env,name){const s=text(env?.[name],500);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function arr(v,n=20){return(Array.isArray(v)?v:[]).map(x=>text(x,240)).filter(Boolean).slice(0,n)}
function safeDate(v,name){if(!v)return null;const s=text(v,40);if(!/^\d{4}-\d{2}-\d{2}(T.*)?$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x))o[k]=/token|secret|authorization|api.?key/i.test(k)?"[redacted]":redact(v);return o}return x}
async function boundedText(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await boundedText(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok){const auth=r.status===401||r.status===403;err(auth?"UPSTREAM_AUTH_FAILED":r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",auth?503:r.status===429?429:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.message||body?.error||raw,500)})}return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

function exaResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),published_date:text(x?.publishedDate,80)||null,author:text(x?.author,300)||null,highlights:Array.isArray(x?.highlights)?x.highlights.map(v=>text(v,2000)).slice(0,8):[]}}
async function exaSearch(args,env){const query=required(args?.query,"query"),body={query,type:["auto","fast","instant","deep-lite"].includes(args?.type)?args.type:"auto",numResults:clamp(args?.limit,1,20,8),contents:{highlights:true}};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.includeDomains=include;if(exclude.length)body.excludeDomains=exclude;const start=safeDate(args?.start_published_date,"start_published_date"),end=safeDate(args?.end_published_date,"end_published_date");if(start)body.startPublishedDate=start;if(end)body.endPublishedDate=end;const out=await request("https://api.exa.ai/search",{method:"POST",headers:{"content-type":"application/json","x-api-key":secret(env,"EXA_API_KEY")},body:JSON.stringify(body)});return{provider:"exa",operation:"search",query,items:Array.isArray(out?.results)?out.results.map(exaResult):[],request_id:out?.requestId||null,cost_dollars:out?.costDollars||null,source_mode:"official-search-api; highlights-only; bounded"}}

function tavilyResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),content:text(x?.content,4000),score:Number.isFinite(Number(x?.score))?Number(x.score):null,published_date:text(x?.published_date||x?.publishedDate,80)||null}}
async function tavilySearch(args,env){const query=required(args?.query,"query"),body={query,search_depth:args?.search_depth==="advanced"?"advanced":"basic",topic:["general","news","finance"].includes(args?.topic)?args.topic:"general",max_results:clamp(args?.limit,1,20,8),include_answer:false,include_raw_content:false};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.include_domains=include;if(exclude.length)body.exclude_domains=exclude;if(args?.country)body.country=text(args.country,80).toLowerCase();if(["day","week","month","year","d","w","m","y"].includes(args?.time_range))body.time_range=args.time_range;const out=await request("https://api.tavily.com/search",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${secret(env,"TAVILY_API_KEY")}`},body:JSON.stringify(body)});return{provider:"tavily",operation:"search",query,items:Array.isArray(out?.results)?out.results.map(tavilyResult):[],request_id:out?.request_id||null,usage:out?.usage||null,response_time:out?.response_time||null,source_mode:"official-search-api; basic-by-default; no-generated-answer; no-raw-content"}}

function firecrawlResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),description:text(x?.description,4000),category:text(x?.category,100)||null}}
async function firecrawlSearch(args,env){const query=required(args?.query,"query",500),body={query,limit:clamp(args?.limit,1,20,8),sources:["web"],timeout:Math.min(15000,clamp(args?.timeout_ms,1000,15000,12000)),ignoreInvalidURLs:true};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.includeDomains=include;if(exclude.length)body.excludeDomains=exclude;if(args?.country)body.country=text(args.country,2).toUpperCase();if(args?.tbs)body.tbs=text(args.tbs,120);const out=await request("https://api.firecrawl.dev/v2/search",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${secret(env,"FIRECRAWL_API_KEY")}`},body:JSON.stringify(body)});const web=Array.isArray(out?.data?.web)?out.data.web:Array.isArray(out?.data)?out.data:[];return{provider:"firecrawl",operation:"search",query,items:web.map(firecrawlResult),success:out?.success===true,source_mode:"official-v2-search; web-only; no scrape/crawl/browser operations exposed"}}

function researchProviders(args,env){const wanted=arr(args?.providers,3).map(x=>x.toLowerCase()).filter(x=>["exa","tavily","firecrawl"].includes(x));const base=wanted.length?wanted:["exa","tavily","firecrawl"];return base.filter(p=>p==="exa"?Boolean(env?.EXA_API_KEY):p==="tavily"?Boolean(env?.TAVILY_API_KEY):Boolean(env?.FIRECRAWL_API_KEY))}
function researchQueries(args){const explicit=arr(args?.queries,3);if(explicit.length)return explicit;const subject=required(args?.query,"query",180),city=text(args?.city,80),prefix=[city,subject].filter(Boolean).join(" ");return[
  `${prefix} 商业选址 商圈 POI 竞品 门店 商业项目`,
  `${prefix} 国土空间规划 交通规划 商业网点 招商 开业`,
  `${prefix} 客流 消费 商业地产 商场 品牌 租金 市场`
]}
function canonicalUrl(v){try{const u=new URL(text(v,2000));u.hash="";[...u.searchParams.keys()].filter(k=>/^utm_/i.test(k)).forEach(k=>u.searchParams.delete(k));return u.href}catch{return text(v,2000)}}
function normalizeResearchItem(provider,round,query,item){return{provider,round,query,title:text(item?.title,500),url:canonicalUrl(item?.url),published_date:item?.published_date||null,excerpt:text(item?.content||item?.description||(Array.isArray(item?.highlights)?item.highlights.join(" "):""),3000)}}
async function commercialWebResearch(args,env){const providers=researchProviders(args,env);if(!providers.length)err("UPSTREAM_AUTH_FAILED",503,{missing_any_of:["EXA_API_KEY","TAVILY_API_KEY","FIRECRAWL_API_KEY"]});const queries=researchQueries(args).slice(0,clamp(args?.rounds,1,3,3)),limit=clamp(args?.limit_per_provider,1,8,5),runs=[],items=[],failures=[];for(let r=0;r<queries.length;r++){const query=queries[r];for(const provider of providers){try{const common={query,limit,include_domains:args?.include_domains,exclude_domains:args?.exclude_domains};const out=provider==="exa"?await exaSearch({...common,type:"auto"},env):provider==="tavily"?await tavilySearch({...common,country:args?.country||"china",search_depth:"basic"},env):await firecrawlSearch({...common,country:args?.country_code||"CN"},env);runs.push({provider,round:r+1,query,ok:true,count:Array.isArray(out?.items)?out.items.length:0,request_id:out?.request_id||null,cost_dollars:out?.cost_dollars||null,usage:out?.usage||null});for(const item of out?.items||[])items.push(normalizeResearchItem(provider,r+1,query,item))}catch(e){failures.push({provider,round:r+1,query,error:text(e?.message||"SEARCH_FAILED",200),status:e?.status||null})}}}if(!runs.length)err("ALL_SEARCH_PROVIDERS_FAILED",503,{failures});const dedup=[],seen=new Set();for(const item of items){const key=item.url||`${item.provider}:${item.title}`;if(!key||seen.has(key))continue;seen.add(key);dedup.push(item)}return{provider:"commercial_web_research",operation:"multi_search",domain:"geospatial-commercial",country_focus:text(args?.country_code||"CN",2).toUpperCase(),evidence_kind:"web-derived-commercial-market-signal",observed_mobile_lbs:false,queries,runs,failures,items:dedup.slice(0,60),source_count:dedup.length,provider_count:new Set(runs.map(x=>x.provider)).size,round_count:queries.length,bounded:true,write:false,notes:["Use web evidence for planning, project pipeline, openings/closures, brands, rents and competition context.","Do not label these results as observed footfall, dwell time, OD or consumer-profile ground truth."]}}

function publicHttpUrl(v){const raw=required(v,"url",2048);let u;try{u=new URL(raw)}catch{err("INVALID_URL")};if(!["http:","https:"].includes(u.protocol))err("URL_SCHEME_NOT_ALLOWED",403);if(u.username||u.password)err("URL_CREDENTIALS_NOT_ALLOWED",403);const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(!h||h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local"))err("PRIVATE_URL_NOT_ALLOWED",403);if(h.includes(":")){if(h==="::1"||h==="::"||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe8")||h.startsWith("fe9")||h.startsWith("fea")||h.startsWith("feb"))err("PRIVATE_URL_NOT_ALLOWED",403)}else if(/^\d{1,3}(?:\.\d{1,3}){3}$/.test(h)){const p=h.split(".").map(Number),a=p[0],b=p[1];if(p.some(x=>x<0||x>255)||a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===198&&(b===18||b===19))||a>=224)err("PRIVATE_URL_NOT_ALLOWED",403)}return u.href}
async function jinaRead(args){const target=publicHttpUrl(args?.url),reader=`https://r.jina.ai/${target}`;const out=await request(reader,{headers:{accept:"text/plain","x-retain-images":"none"}});let content="";if(typeof out==="string")content=out;else if(typeof out?.data?.content==="string")content=out.data.content;else if(typeof out?.content==="string")content=out.content;else if(out!=null)content=JSON.stringify(out);content=text(content,60000);if(!content)err("EMPTY_UPSTREAM_OUTPUT",502);return{provider:"jina",operation:"read",url:target,content,source_mode:"official-r.jina.ai Reader; public-no-key basic mode; bounded; Jina Search disabled",free_mode:true,rate_limit_note:"Jina currently documents 20 RPM without an API key; no monthly request quota is stated for basic Reader usage"}}

export const OPERATIONS={exa:["search"],tavily:["search"],firecrawl:["search"],commercial_web_research:["multi_search"],jina:["read"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="exa")return exaSearch(args,env);if(provider==="tavily")return tavilySearch(args,env);if(provider==="firecrawl")return firecrawlSearch(args,env);if(provider==="commercial_web_research")return commercialWebResearch(args,env);if(provider==="jina")return jinaRead(args);err("ADAPTER_NOT_IMPLEMENTED",501)}