const MAX_BYTES=1500000,TIMEOUT_MS=15000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
const tokenCache=new Map();
function b64urlBytes(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64urlText(s){return b64urlBytes(new TextEncoder().encode(s))}
function pemBytes(pem){const raw=String(pem||"").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s+/g,"");if(!raw)throw Object.assign(new Error("GOOGLE_CREDENTIALS_INVALID"),{status:503});const bin=atob(raw),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out.buffer}
function parseCreds(env){const raw=env.GOOGLE_CLOUD_CREDENTIALS;if(!raw)return null;const s=String(raw).trim();try{return JSON.parse(s)}catch{}try{return JSON.parse(atob(s))}catch{}throw Object.assign(new Error("GOOGLE_CREDENTIALS_INVALID"),{status:503})}
async function bounded(url,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,error:body?.error?.message||body?.error||null}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
async function serviceToken(env,scope){if(env.GOOGLE_CLOUD_ACCESS_TOKEN)return String(env.GOOGLE_CLOUD_ACCESS_TOKEN);const c=parseCreds(env);if(!c?.client_email||!c?.private_key)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const cacheKey=`${c.client_email}|${scope}`,cached=tokenCache.get(cacheKey);if(cached&&cached.exp>Date.now()+60000)return cached.token;const now=Math.floor(Date.now()/1000),header=b64urlText(JSON.stringify({alg:"RS256",typ:"JWT"})),payload=b64urlText(JSON.stringify({iss:c.client_email,scope,aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3300})),input=`${header}.${payload}`,key=await crypto.subtle.importKey("pkcs8",pemBytes(c.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(input))),assertion=`${input}.${b64urlBytes(sig)}`,form=new URLSearchParams({grant_type:"urn:ietf:params:oauth-type:jwt-bearer",assertion});form.set("grant_type","urn:ietf:params:oauth:grant-type:jwt-bearer");const r=await bounded("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","accept":"application/json"},body:form.toString()});if(!r?.access_token)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const exp=Date.now()+Math.max(300,Number(r.expires_in||3600)-60)*1000;tokenCache.set(cacheKey,{token:r.access_token,exp});return r.access_token}
async function authJson(url,env,scope,init={}){const token=await serviceToken(env,scope);return bounded(url,{...init,headers:{accept:"application/json",authorization:`Bearer ${token}`,...(init.headers||{})}})}
function projectId(env,args){const c=parseCreds(env),p=text(args?.project_id||env.GOOGLE_CLOUD_PROJECT||c?.project_id||"",128);if(!/^[a-z][a-z0-9-]{4,62}$/.test(p))throw Object.assign(new Error("ARG_REQUIRED:project_id"),{status:400});return p}
function safeDataset(v){const s=text(v,1024);if(!/^[A-Za-z0-9_\-]+$/.test(s))throw Object.assign(new Error("INVALID_DATASET_ID"),{status:400});return s}
function publicQuery(v){const q=text(v,20000);if(!/^\s*(SELECT|WITH)\b/i.test(q)||/;\s*\S/.test(q)||/\b(INSERT|UPDATE|DELETE|MERGE|CREATE|DROP|ALTER|TRUNCATE|GRANT|REVOKE|CALL|EXPORT)\b/i.test(q))throw Object.assign(new Error("POLICY_DENIED_READ_ONLY_QUERY"),{status:403});if(!/`bigquery-public-data\.[^`]+`/i.test(q))throw Object.assign(new Error("POLICY_DENIED_PUBLIC_DATA_ONLY"),{status:403});for(const m of q.matchAll(/`([^`]+)`/g)){const ref=m[1];if((ref.match(/\./g)||[]).length>=2&&!ref.toLowerCase().startsWith("bigquery-public-data."))throw Object.assign(new Error("POLICY_DENIED_PUBLIC_DATA_ONLY"),{status:403})}return q}
function publicAsset(v,allowRoot=false){let s=text(v,1000);if(!s.startsWith("projects/"))s=`projects/earthengine-public/assets/${s.replace(/^\/+/,"")}`;const root=s==="projects/earthengine-public"||s==="projects/earthengine-public/assets";if(!(s.startsWith("projects/earthengine-public/assets/")||(allowRoot&&root)))throw Object.assign(new Error("POLICY_DENIED_PUBLIC_ASSET_ONLY"),{status:403});return s}
function eePath(name){return name.split("/").map(encodeURIComponent).join("/").replace(/%2F/g,"/")}
export const OPERATIONS={bigquery:["query","tables"],earthengine:["asset_get","list_assets","list_features"]};
export async function runAdapter(provider,operation,args,env){
  if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});
  if(provider==="bigquery"){
    const project=projectId(env,args),scope="https://www.googleapis.com/auth/bigquery.readonly";
    if(operation==="query"){const query=publicQuery(required(args,"query")),u=`https://bigquery.googleapis.com/bigquery/v2/projects/${encodeURIComponent(project)}/queries`,body={query,useLegacySql:false,maxResults:clamp(args.limit,1,1000,100),timeoutMs:clamp(args.timeout_ms,1000,10000,8000)};if(args.maximum_bytes_billed!==undefined)body.maximumBytesBilled=String(Math.max(0,Number(args.maximum_bytes_billed)||0));const out=await authJson(u,env,scope,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});return{provider,operation,data:{schema:out?.schema||null,rows:out?.rows||[],total_rows:out?.totalRows||null,job_complete:out?.jobComplete!==false,cache_hit:out?.cacheHit||false,total_bytes_processed:out?.totalBytesProcessed||null}}}
    if(operation==="tables"){const dataset=safeDataset(required(args,"dataset")),u=new URL(`https://bigquery.googleapis.com/bigquery/v2/projects/bigquery-public-data/datasets/${encodeURIComponent(dataset)}/tables`);u.searchParams.set("maxResults",String(clamp(args.limit,1,1000,100)));if(args.page_token)u.searchParams.set("pageToken",text(args.page_token,512));const out=await authJson(u,env,scope);return{provider,operation,items:out?.tables||[],next_page_token:out?.nextPageToken||null,total_items:out?.totalItems||null}}
  }
  if(provider==="earthengine"){
    const scope="https://www.googleapis.com/auth/earthengine.readonly";
    if(operation==="asset_get"){const name=publicAsset(required(args,"asset")),u=`https://earthengine.googleapis.com/v1/${eePath(name)}`;return{provider,operation,data:await authJson(u,env,scope)}}
    if(operation==="list_assets"){const parent=publicAsset(args.parent||"projects/earthengine-public/assets",true),u=new URL(`https://earthengine.googleapis.com/v1/${eePath(parent)}:listAssets`);u.searchParams.set("pageSize",String(clamp(args.limit,1,1000,100)));if(args.page_token)u.searchParams.set("pageToken",text(args.page_token,512));if(args.filter)u.searchParams.set("filter",text(args.filter,1000));const out=await authJson(u,env,scope);return{provider,operation,items:out?.assets||[],next_page_token:out?.nextPageToken||null}}
    if(operation==="list_features"){const asset=publicAsset(required(args,"asset")),u=new URL(`https://earthengine.googleapis.com/v1/${eePath(asset)}:listFeatures`);u.searchParams.set("pageSize",String(clamp(args.limit,1,1000,100)));if(args.page_token)u.searchParams.set("pageToken",text(args.page_token,512));if(args.filter)u.searchParams.set("filter",text(args.filter,1000));const out=await authJson(u,env,scope);return{provider,operation,items:out?.features||[],next_page_token:out?.nextPageToken||null}}
  }
  throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501});
}
