const MAX_BYTES=1500000,TIMEOUT_MS=12000;
const text=(v,n=300)=>String(v??"").trim().slice(0,n);
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
async function getJson(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/json"},signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,body}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
function coordLatLng(v){const s=text(v,48);if(!/^-?\d{1,2}(?:\.\d{1,8})?,-?\d{1,3}(?:\.\d{1,8})?$/.test(s))throw Object.assign(new Error("INVALID_COORDINATE"),{status:400});const [lat,lng]=s.split(",").map(Number);if(lat<-90||lat>90||lng<-180||lng>180)throw Object.assign(new Error("INVALID_COORDINATE"),{status:400});return s}
function coordArray(v){const s=coordLatLng(v),[lat,lng]=s.split(",").map(Number);return{lat,lng,s}}
function haversineKm(a,b){const r=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function trafficBounds(v){const parts=Array.isArray(v)?v:String(v||"").split(";");if(parts.length!==2)throw Object.assign(new Error("INVALID_BOUNDS"),{status:400});const a=coordArray(parts[0]),b=coordArray(parts[1]);if(a.lat>=b.lat||a.lng>=b.lng||haversineKm(a,b)>2)throw Object.assign(new Error("INVALID_BOUNDS"),{status:400,details:{max_diagonal_km:2}});return`${a.s};${b.s}`}
function trafficPolygon(v){const parts=Array.isArray(v)?v:String(v||"").split(";");if(parts.length<3||parts.length>10)throw Object.assign(new Error("INVALID_POLYGON"),{status:400});const pts=parts.map(coordArray),lats=pts.map(x=>x.lat),lngs=pts.map(x=>x.lng),a={lat:Math.min(...lats),lng:Math.min(...lngs)},b={lat:Math.max(...lats),lng:Math.max(...lngs)};if(haversineKm(a,b)>2)throw Object.assign(new Error("INVALID_POLYGON"),{status:400,details:{max_bounding_diagonal_km:2}});return pts.map(x=>x.s).join(";")}
function coordTypeIn(v){return["bd09ll","gcj02","wgs84"].includes(v)?v:"bd09ll"}
function coordTypeOut(v){return["bd09ll","gcj02"].includes(v)?v:"bd09ll"}
function roadGrade(v){if(v===undefined||v===null||v==="")return"0";const p=String(v).split(",").map(x=>Number(x.trim()));if(!p.length||p.length>5||p.some(x=>!Number.isInteger(x)||x<0||x>5))throw Object.assign(new Error("INVALID_ROAD_GRADE"),{status:400});return[...new Set(p)].join(",")}
function baiduKey(env){return env.BAIDU_MAP_AK||env.BAIDU_MAP_API_KEY||""}
function tencentKey(env){return env.TENCENT_LBS_API_KEY||env.TENCENT_MAP_API_KEY||""}
function ensureBaidu(body){if(Number(body?.status)!==0)throw Object.assign(new Error("UPSTREAM_BUSINESS_ERROR"),{status:502,details:{status:body?.status,message:body?.message}});return body}
function ensureTencent(body){if(Number(body?.status)!==0)throw Object.assign(new Error("UPSTREAM_BUSINESS_ERROR"),{status:502,details:{status:body?.status,message:body?.message}});return body}
function freeTraffic(body){const b=ensureBaidu(body);if(Array.isArray(b?.road_traffic))for(const road of b.road_traffic)if(road&&typeof road==="object")delete road.traffic_detail;return b}
async function baiduTraffic(path,params,env){const ak=baiduKey(env);if(!ak)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const u=new URL(`https://api.map.baidu.com${path}`);u.searchParams.set("ak",String(ak));for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&String(v)!=="")u.searchParams.set(k,String(v));return freeTraffic(await getJson(u))}
export const OPERATIONS={baidu_maps:["geocode","reverse_geocode","traffic_road","traffic_bound","traffic_polygon","traffic_around"],tencent_maps:["geocode","reverse_geocode","place_nearby"]};
export async function runAdapter(provider,operation,args,env){
  if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});
  if(provider==="baidu_maps"){
    const ak=baiduKey(env);if(!ak)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});
    if(operation==="geocode"){const u=new URL("https://api.map.baidu.com/geocoding/v3/");u.searchParams.set("address",text(required(args,"address"),128));u.searchParams.set("output","json");u.searchParams.set("ak",String(ak));if(args.city)u.searchParams.set("city",text(args.city,60));return{provider,operation,data:ensureBaidu(await getJson(u))}}
    if(operation==="reverse_geocode"){const u=new URL("https://api.map.baidu.com/reverse_geocoding/v3/");u.searchParams.set("location",coordLatLng(required(args,"location")));u.searchParams.set("output","json");u.searchParams.set("ak",String(ak));u.searchParams.set("coordtype",["wgs84ll","gcj02ll","bd09ll"].includes(args.coordtype)?args.coordtype:"bd09ll");u.searchParams.set("extensions_poi",args.extensions_poi===true?"1":"0");return{provider,operation,data:ensureBaidu(await getJson(u))}}
    if(operation==="traffic_road"){const data=await baiduTraffic("/traffic/v1/road",{road_name:text(required(args,"road_name"),80),city:text(required(args,"city"),40),coord_type_output:coordTypeOut(args.coord_type_output)},env);return{provider,operation,free_tier_only:true,data}}
    if(operation==="traffic_bound"){const data=await baiduTraffic("/traffic/v1/bound",{bounds:trafficBounds(required(args,"bounds")),road_grade:roadGrade(args.road_grade),coord_type_input:coordTypeIn(args.coord_type_input),coord_type_output:coordTypeOut(args.coord_type_output)},env);return{provider,operation,free_tier_only:true,data}}
    if(operation==="traffic_polygon"){const data=await baiduTraffic("/traffic/v1/polygon",{vertexes:trafficPolygon(required(args,"vertexes")),road_grade:roadGrade(args.road_grade),coord_type_input:coordTypeIn(args.coord_type_input),coord_type_output:coordTypeOut(args.coord_type_output)},env);return{provider,operation,free_tier_only:true,data}}
    if(operation==="traffic_around"){const data=await baiduTraffic("/traffic/v1/around",{center:coordLatLng(required(args,"center")),radius:clamp(args.radius,1,1000,500),road_grade:roadGrade(args.road_grade),coord_type_input:coordTypeIn(args.coord_type_input),coord_type_output:coordTypeOut(args.coord_type_output)},env);return{provider,operation,free_tier_only:true,data}}
  }
  if(provider==="tencent_maps"){
    const key=tencentKey(env);if(!key)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});
    if(operation==="geocode"){const u=new URL("https://apis.map.qq.com/ws/geocoder/v1/");u.searchParams.set("address",text(required(args,"address"),200));u.searchParams.set("key",String(key));if(args.region)u.searchParams.set("region",text(args.region,60));return{provider,operation,data:ensureTencent(await getJson(u))}}
    if(operation==="reverse_geocode"){const u=new URL("https://apis.map.qq.com/ws/geocoder/v1/");u.searchParams.set("location",coordLatLng(required(args,"location")));u.searchParams.set("key",String(key));u.searchParams.set("get_poi",args.get_poi===false?"0":"1");return{provider,operation,data:ensureTencent(await getJson(u))}}
    if(operation==="place_nearby"){const center=coordLatLng(required(args,"location")),radius=clamp(args.radius,10,5000,1000),u=new URL("https://apis.map.qq.com/ws/place/v1/search");u.searchParams.set("keyword",text(required(args,"keyword"),80));u.searchParams.set("boundary",`nearby(${center},${radius})`);u.searchParams.set("page_size",String(clamp(args.limit,1,20,10)));u.searchParams.set("page_index","1");u.searchParams.set("key",String(key));return{provider,operation,data:ensureTencent(await getJson(u))}}
  }
  throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501});
}
