const MAX_BYTES=1500000,TIMEOUT_MS=12000;
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
const text=(v,n=300)=>String(v??"").trim().slice(0,n);
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
async function fetchJson(url,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}});const raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,body}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
export const OPERATIONS={newsapi:["everything"],eia:["seriesid"],opensky:["states"]};
export async function runAdapter(provider,operation,args,env){
  if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});
  if(provider==="newsapi"){
    if(!env.NEWSAPI_KEY)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const q=text(required(args,"query"),500),u=new URL("https://newsapi.org/v2/everything");u.searchParams.set("q",q);u.searchParams.set("pageSize",String(clamp(args.limit,1,20,10)));u.searchParams.set("page","1");const sort=["relevancy","popularity","publishedAt"].includes(args.sort_by)?args.sort_by:"publishedAt";u.searchParams.set("sortBy",sort);if(args.language&&/^(ar|de|en|es|fr|he|it|nl|no|pt|ru|sv|ud|zh)$/.test(args.language))u.searchParams.set("language",args.language);for(const k of ["from","to"]){if(args[k]){const v=text(args[k],30);if(!/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2})?$/.test(v))throw Object.assign(new Error(`INVALID_${k.toUpperCase()}`),{status:400});u.searchParams.set(k,v)}}const body=await fetchJson(u,{headers:{"X-Api-Key":String(env.NEWSAPI_KEY)}});return{provider,operation,total:body?.totalResults??null,items:body?.articles||[]};
  }
  if(provider==="eia"){
    if(!env.EIA_API_KEY)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const series=text(required(args,"series_id"),120);if(!/^[A-Za-z0-9._:-]+$/.test(series))throw Object.assign(new Error("INVALID_SERIES_ID"),{status:400});const u=new URL(`https://api.eia.gov/v2/seriesid/${encodeURIComponent(series)}`);u.searchParams.set("api_key",String(env.EIA_API_KEY));u.searchParams.set("length",String(clamp(args.limit,1,500,100)));if(args.start){const v=text(args.start,20);if(!/^\d{4}(?:-\d{2})?(?:-\d{2})?$/.test(v))throw Object.assign(new Error("INVALID_START"),{status:400});u.searchParams.set("start",v)}if(args.end){const v=text(args.end,20);if(!/^\d{4}(?:-\d{2})?(?:-\d{2})?$/.test(v))throw Object.assign(new Error("INVALID_END"),{status:400});u.searchParams.set("end",v)}const body=await fetchJson(u);return{provider,operation,data:body?.response||body};
  }
  if(provider==="opensky"){
    if(!env.OPENSKY_CLIENT_ID||!env.OPENSKY_CLIENT_SECRET)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503});const form=new URLSearchParams({grant_type:"client_credentials",client_id:String(env.OPENSKY_CLIENT_ID),client_secret:String(env.OPENSKY_CLIENT_SECRET)});const tok=await fetchJson("https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form.toString()});if(!tok?.access_token)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:502});const u=new URL("https://opensky-network.org/api/states/all");if(Array.isArray(args.icao24)){for(const id of args.icao24.slice(0,10)){const s=text(id,6).toLowerCase();if(!/^[0-9a-f]{6}$/.test(s))throw Object.assign(new Error("INVALID_ICAO24"),{status:400});u.searchParams.append("icao24",s)}}const bbox=args.bbox;if(Array.isArray(bbox)&&bbox.length===4){const [lamin,lamax,lomin,lomax]=bbox.map(Number);if(![lamin,lamax,lomin,lomax].every(Number.isFinite)||lamin<-90||lamax>90||lomin<-180||lomax>180||lamin>lamax||lomin>lomax)throw Object.assign(new Error("INVALID_BBOX"),{status:400});u.searchParams.set("lamin",String(lamin));u.searchParams.set("lamax",String(lamax));u.searchParams.set("lomin",String(lomin));u.searchParams.set("lomax",String(lomax))}const body=await fetchJson(u,{headers:{authorization:`Bearer ${tok.access_token}`}});return{provider,operation,time:body?.time??null,states:Array.isArray(body?.states)?body.states.slice(0,500):[]};
  }
  throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501});
}
