const TIMEOUT_MS=18000,MAX_BYTES=1800000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function id(v,name,re,n=120){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(raw,400)});try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502)}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function gdcFields(){return["case_id","submitter_id","project.project_id","disease_type","primary_site","demographic.gender","demographic.vital_status","diagnoses.primary_diagnosis","diagnoses.age_at_diagnosis"].join(",")}
async function precision(operation,args){
 if(operation==="gdc_projects"){const u=new URL("https://api.gdc.cancer.gov/projects");u.searchParams.set("format","JSON");u.searchParams.set("size",String(clamp(args?.limit,1,100,20)));u.searchParams.set("fields","project_id,name,disease_type,primary_site,program.name,summary.case_count,summary.file_count");const b=await request(u);return{provider:"splus_precision_biomed",operation,source:"NCI GDC",items:b?.data?.hits||[],pagination:b?.data?.pagination||null}}
 if(operation==="gdc_cases"){const u=new URL("https://api.gdc.cancer.gov/cases");u.searchParams.set("format","JSON");u.searchParams.set("size",String(clamp(args?.limit,1,100,20)));u.searchParams.set("fields",gdcFields());if(args?.project_id){const p=id(args.project_id,"project_id",/^[A-Za-z0-9_.-]+$/,80);u.searchParams.set("filters",JSON.stringify({op:"=",content:{field:"project.project_id",value:[p]}}))}const b=await request(u);return{provider:"splus_precision_biomed",operation,source:"NCI GDC",controlled_data_note:"Public metadata only here; controlled file download requires user-authorized GDC token and is not proxied by this operation.",items:b?.data?.hits||[],pagination:b?.data?.pagination||null}}
 if(operation==="gtex_gene_search"){const gene=id(args?.gene,"gene",/^[A-Za-z0-9_.-]+$/,80),u=new URL("https://gtexportal.org/api/v2/reference/geneSearch");u.searchParams.set("geneId",gene);u.searchParams.set("gencodeVersion",["v39","v26","v19"].includes(args?.gencode_version)?args.gencode_version:"v39");u.searchParams.set("genomeBuild",args?.genome_build==="GRCh37/hg19"?"GRCh37/hg19":"GRCh38/hg38");u.searchParams.set("itemsPerPage",String(clamp(args?.limit,1,100,20)));const b=await request(u);return{provider:"splus_precision_biomed",operation,source:"GTEx V2",items:b?.data||[],paging:b?.paging_info||null}}
 if(operation==="gtex_gene_expression"){const gene=id(args?.gencode_id,"gencode_id",/^ENSG\d{11}(\.\d+)?$/,40),u=new URL("https://gtexportal.org/api/v2/expression/geneExpression");u.searchParams.set("gencodeId",gene);u.searchParams.set("datasetId",["gtex_v8","gtex_v10","gtex_snrnaseq_pilot"].includes(args?.dataset_id)?args.dataset_id:"gtex_v10");if(args?.tissue)u.searchParams.append("tissueSiteDetailId",id(args.tissue,"tissue",/^[A-Za-z0-9_:-]+$/,100));u.searchParams.set("itemsPerPage",String(clamp(args?.limit,1,250,50)));const b=await request(u);return{provider:"splus_precision_biomed",operation,source:"GTEx V2",items:b?.data||[],paging:b?.paging_info||null}}
 if(operation==="alphafold_prediction"){const uniprot=id(args?.uniprot,"uniprot",/^[A-Za-z0-9]{6,12}$/,12).toUpperCase(),b=await request(`https://alphafold.ebi.ac.uk/api/prediction/${encodeURIComponent(uniprot)}`);return{provider:"splus_precision_biomed",operation,source:"AlphaFold DB",uniprot,items:Array.isArray(b)?b:[b].filter(Boolean)}}
 if(operation==="hpa_gene"){const ensembl=id(args?.ensembl_id,"ensembl_id",/^ENSG\d{11}$/,15),b=await request(`https://www.proteinatlas.org/${encodeURIComponent(ensembl)}.json`);return{provider:"splus_precision_biomed",operation,source:"Human Protein Atlas",ensembl,data:b}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}
export const OPERATIONS={splus_precision_biomed:["gdc_projects","gdc_cases","gtex_gene_search","gtex_gene_expression","alphafold_prediction","hpa_gene"]};
export async function runAdapter(provider,operation,args={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="splus_precision_biomed")return precision(operation,args);err("ADAPTER_NOT_IMPLEMENTED",501)}