const MAX_BYTES=1500000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function required(v,name){const s=text(v,1000);if(!s)err(`ARG_REQUIRED:${name}`);return s}
async function fetchText(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"*/*",...(init.headers||{})}}),declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(raw,500)});return raw}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
async function fetchJson(url,init={}){const raw=await fetchText(url,{...init,headers:{accept:"application/json",...(init.headers||{})}});try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502)}}
function lat(v){const n=Number(v);if(!Number.isFinite(n)||n< -90||n>90)err("INVALID_LATITUDE");return n}
function lon(v){const n=Number(v);if(!Number.isFinite(n)||n< -180||n>180)err("INVALID_LONGITUDE");return n}
function powerDate(v,kind){const s=String(v||"").replace(/-/g,"");const re=kind==="monthly"?/^\d{4}$/:/^\d{8}$/;if(!re.test(s))err("INVALID_DATE",400,{expected:kind==="monthly"?"YYYY":"YYYYMMDD"});return s}
function parameters(v){const raw=Array.isArray(v)?v:String(v||"").split(","),out=raw.map(x=>String(x).trim().toUpperCase()).filter(Boolean).slice(0,12);if(!out.length)err("ARG_REQUIRED:parameters");if(out.some(x=>!/^[A-Z0-9_]+$/.test(x)))err("INVALID_PARAMETER");return out.join(",")}
const POWER_BASE="https://power.larc.nasa.gov/api/temporal";
async function power(operation,args){const map={point_daily:"daily",point_hourly:"hourly",point_monthly:"monthly",point_climatology:"climatology"},kind=map[operation];if(!kind)err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`${POWER_BASE}/${kind}/point`);u.searchParams.set("parameters",parameters(args?.parameters));u.searchParams.set("community",["RE","AG","SB"].includes(String(args?.community||"RE").toUpperCase())?String(args?.community||"RE").toUpperCase():"RE");u.searchParams.set("longitude",String(lon(args?.longitude)));u.searchParams.set("latitude",String(lat(args?.latitude)));u.searchParams.set("format","JSON");if(kind!=="climatology"){u.searchParams.set("start",powerDate(args?.start,kind));u.searchParams.set("end",powerDate(args?.end,kind))}const body=await fetchJson(u);return{provider:"nasa_power",operation,temporal:kind,data:body}}
function csvRows(raw,delimiter=","){const lines=raw.replace(/^\uFEFF/,"").trim().split(/\r?\n/);if(!lines.length||!lines[0])return[];const parse=line=>{const out=[];let cur="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===delimiter&&!q){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out};const hdr=parse(lines[0]);return lines.slice(1).filter(Boolean).slice(0,500).map(line=>Object.fromEntries(parse(line).map((v,i)=>[hdr[i]||`c${i}`,v])))}
const FIRMS_BASE="https://firms.modaps.eosdis.nasa.gov";
const FIRMS_SOURCES=new Set(["MODIS_NRT","MODIS_SP","VIIRS_NOAA20_NRT","VIIRS_NOAA20_SP","VIIRS_NOAA21_NRT","VIIRS_SNPP_NRT","VIIRS_SNPP_SP","BA_MODIS","BA_VIIRS"]);
function firmsKey(env){const k=String(env?.NASA_FIRMS_MAP_KEY||env?.FIRMS_MAP_KEY||"").trim();if(!k)err("UPSTREAM_AUTH_FAILED",503,{missing:"NASA_FIRMS_MAP_KEY"});if(!/^[A-Za-z0-9_-]{8,80}$/.test(k))err("UPSTREAM_AUTH_FAILED",503,{invalid:"NASA_FIRMS_MAP_KEY"});return k}
function firmsSource(v){const s=String(v||"VIIRS_NOAA20_NRT").toUpperCase();if(!FIRMS_SOURCES.has(s))err("INVALID_FIRMS_SOURCE",400,{allowed:[...FIRMS_SOURCES]});return s}
function firmsBbox(v){const a=Array.isArray(v)?v.map(Number):String(v||"").split(",").map(Number);if(a.length!==4||a.some(x=>!Number.isFinite(x)))err("INVALID_BBOX");const[w,s,e,n]=a;if(w< -180||e>180||s< -90||n>90||w>=e||s>=n)err("INVALID_BBOX");if((e-w)*(n-s)>400)err("BBOX_TOO_LARGE",413,{max_square_degrees:400});return a.join(",")}
async function firms(operation,args,env){if(operation==="countries"){const raw=await fetchText(`${FIRMS_BASE}/api/countries`);return{provider:"nasa_firms",operation,items:csvRows(raw,";")}}const key=firmsKey(env);if(operation==="mapkey_status")return{provider:"nasa_firms",operation,data:await fetchJson(`${FIRMS_BASE}/mapserver/mapkey_status/?MAP_KEY=${encodeURIComponent(key)}`)};if(operation==="data_availability"){const src=args?.source?firmsSource(args.source):"all",raw=await fetchText(`${FIRMS_BASE}/api/data_availability/csv/${encodeURIComponent(key)}/${encodeURIComponent(src)}`);return{provider:"nasa_firms",operation,items:csvRows(raw)}}if(operation==="area"){const src=firmsSource(args?.source),box=firmsBbox(args?.bbox),days=clamp(args?.day_range,1,5,1);let url=`${FIRMS_BASE}/api/area/csv/${encodeURIComponent(key)}/${encodeURIComponent(src)}/${encodeURIComponent(box)}/${days}`;if(args?.date){const d=String(args.date);if(!/^\d{4}-\d{2}-\d{2}$/.test(d))err("INVALID_DATE");url+=`/${encodeURIComponent(d)}`}const raw=await fetchText(url);const items=csvRows(raw);return{provider:"nasa_firms",operation,source:src,bbox:box,day_range:days,truncated:raw.trim().split(/\r?\n/).length-1>items.length,items}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}
const GIBS_ROOT="https://gibs.earthdata.nasa.gov";
const GIBS_PROJECTIONS=new Set(["epsg4326","epsg3857","epsg3413","epsg3031"]);
const GIBS_SETS=new Set(["best","std","nrt","all"]);
function gibsProjection(v){const s=String(v||"epsg4326").toLowerCase();if(!GIBS_PROJECTIONS.has(s))err("INVALID_PROJECTION");return s}
function gibsSet(v){const s=String(v||"best").toLowerCase();if(!GIBS_SETS.has(s))err("INVALID_LAYER_SET");return s}
async function gibs(operation,args){if(operation==="source_info")return{provider:"nasa_gibs",operation,protocols:["WMTS","WMS","TWMS"],projections:[...GIBS_PROJECTIONS],sets:[...GIBS_SETS],role:"NASA Worldview imagery backend"};if(operation==="layers"){const projection=gibsProjection(args?.projection),set=gibsSet(args?.set),url=`${GIBS_ROOT}/wmts/${projection}/${set}/1.0.0/WMTSCapabilities.xml`,raw=await fetchText(url),rx=/<Layer\b[\s\S]*?<ows:Identifier>([^<]+)<\/ows:Identifier>[\s\S]*?<\/Layer>/g,all=[];for(const m of raw.matchAll(rx)){const id=m[1];if(!all.includes(id))all.push(id)}const q=text(args?.query,120).toLowerCase(),filtered=(q?all.filter(x=>x.toLowerCase().includes(q)):all).slice(0,clamp(args?.limit,1,200,50));return{provider:"nasa_gibs",operation,projection,set,total_layers:all.length,items:filtered}}if(operation==="tile_url"){const projection=gibsProjection(args?.projection),set=gibsSet(args?.set),layer=required(args?.layer,"layer");if(!/^[A-Za-z0-9_.-]+$/.test(layer))err("INVALID_LAYER");const date=String(args?.date||"");if(date&&!/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}Z)?$/.test(date))err("INVALID_DATE");const matrix=required(args?.tile_matrix_set,"tile_matrix_set");if(!/^[A-Za-z0-9_.-]+$/.test(matrix))err("INVALID_TILE_MATRIX_SET");const z=clamp(args?.tile_matrix,0,30,0),row=clamp(args?.tile_row,0,10000000,0),col=clamp(args?.tile_col,0,10000000,0),format=String(args?.format||"jpg").toLowerCase();if(!["jpg","jpeg","png","pbf"].includes(format))err("INVALID_FORMAT");const when=date||"default";return{provider:"nasa_gibs",operation,url:`${GIBS_ROOT}/wmts/${projection}/${set}/${layer}/default/${when}/${matrix}/${z}/${row}/${col}.${format}`}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}
export const OPERATIONS={nasa_power:["point_daily","point_hourly","point_monthly","point_climatology"],nasa_firms:["countries","mapkey_status","data_availability","area"],nasa_gibs:["source_info","layers","tile_url"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="nasa_power")return power(operation,args);if(provider==="nasa_firms")return firms(operation,args,env);if(provider==="nasa_gibs")return gibs(operation,args);err("ADAPTER_NOT_IMPLEMENTED",501)}
