const MAX_BYTES=1800000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function req(v,name,n=300){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function tok(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=req(v,name,n);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function arr(v,n=20){return(Array.isArray(v)?v:String(v??"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,n)}
function secret(env,name){const s=text(env?.[name],300);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function isoDate(v,name){const s=tok(v,name,/^\d{4}-\d{2}-\d{2}$/,10),d=new Date(`${s}T00:00:00Z`);if(Number.isNaN(+d)||d.toISOString().slice(0,10)!==s)err(`INVALID_${name.toUpperCase()}`);return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x)){if(["api_key","apikey","authorization","x-api-key","token"].includes(k.toLowerCase()))o[k]="[redacted]";else o[k]=redact(v)}return o}return x}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":r.status===404?"UPSTREAM_NOT_FOUND":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:r.status===404?404:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.message||body?.error||raw,400)});return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

const FR="https://www.federalregister.gov/api/v1";
function frDocNo(v){return tok(v,"document_number",/^[0-9]{4}-[0-9]{4,6}$/i,20)}
async function federalRegister(operation,args){if(operation==="documents"){const u=new URL(`${FR}/documents.json`);u.searchParams.set("per_page",String(clamp(args?.limit,1,100,20)));u.searchParams.set("page",String(clamp(args?.page,1,1000,1)));u.searchParams.set("order",["newest","oldest","relevance"].includes(args?.order)?args.order:"newest");if(args?.query)u.searchParams.set("conditions[term]",req(args.query,"query",240));const agencies=arr(args?.agencies,10);for(const a of agencies)u.searchParams.append("conditions[agencies][]",tok(a,"agency",/^[A-Za-z0-9-]+$/,100));if(args?.start_date)u.searchParams.set("conditions[publication_date][gte]",isoDate(args.start_date,"start_date"));if(args?.end_date)u.searchParams.set("conditions[publication_date][lte]",isoDate(args.end_date,"end_date"));const body=await request(u);return{provider:"federal_register",operation,total:body?.count??null,items:Array.isArray(body?.results)?body.results:[],legal_note:"FederalRegister.gov is an informational service; for controlling legal text, cross-check the official Federal Register edition / govinfo."}}
 if(operation==="document"){const no=frDocNo(args?.document_number),body=await request(`${FR}/documents/${encodeURIComponent(no)}.json`);return{provider:"federal_register",operation,document_number:no,data:body,legal_note:"Cross-check controlling legal text against the official Federal Register edition / govinfo when legal effect matters."}}
 if(operation==="agencies"){const body=await request(`${FR}/agencies.json`);return{provider:"federal_register",operation,items:Array.isArray(body)?body:[]}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const CONGRESS="https://api.congress.gov/v3";
const BILL_TYPES=new Set(["hr","s","hjres","sjres","hconres","sconres","hres","sres"]);
function congressKey(env){return secret(env,"CONGRESS_GOV_API_KEY")}
function congressNum(v){const n=Number(v);if(!Number.isInteger(n)||n<1||n>999)err("INVALID_CONGRESS");return String(n)}
function billType(v){const s=String(v||"").toLowerCase();if(!BILL_TYPES.has(s))err("INVALID_BILL_TYPE",400,{allowed:[...BILL_TYPES]});return s}
function billNum(v){const n=Number(v);if(!Number.isInteger(n)||n<1||n>999999)err("INVALID_BILL_NUMBER");return String(n)}
function congressUrl(path,args,env){const u=new URL(`${CONGRESS}/${path}`);u.searchParams.set("api_key",congressKey(env));u.searchParams.set("format","json");if(args?.limit!==undefined)u.searchParams.set("limit",String(clamp(args.limit,1,100,20)));if(args?.offset!==undefined)u.searchParams.set("offset",String(clamp(args.offset,0,1000000,0)));return u}
async function congress(operation,args,env){if(operation==="bills"){const c=args?.congress?congressNum(args.congress):"",t=args?.bill_type?billType(args.bill_type):"";if(t&&!c)err("ARG_REQUIRED:congress_with_bill_type");const path=t?`bill/${c}/${t}`:c?`bill/${c}`:"bill",u=congressUrl(path,args,env);if(args?.from_date_time)u.searchParams.set("fromDateTime",req(args.from_date_time,"from_date_time",30));if(args?.to_date_time)u.searchParams.set("toDateTime",req(args.to_date_time,"to_date_time",30));const body=await request(u);return{provider:"congress_gov",operation,items:Array.isArray(body?.bills)?body.bills:[],pagination:body?.pagination||null}}
 const c=congressNum(args?.congress),t=billType(args?.bill_type),n=billNum(args?.bill_number),suffix=operation==="bill_actions"?"/actions":"",body=await request(congressUrl(`bill/${c}/${t}/${n}${suffix}`,{},env));if(operation==="bill")return{provider:"congress_gov",operation,data:body?.bill||body};if(operation==="bill_actions")return{provider:"congress_gov",operation,items:Array.isArray(body?.actions)?body.actions:[],pagination:body?.pagination||null};err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const REGS="https://api.regulations.gov/v4";
function regsHeaders(env){return{"X-Api-Key":secret(env,"REGULATIONS_GOV_API_KEY")}}
function regId(v,name){return tok(v,name,/^[A-Za-z0-9][A-Za-z0-9._-]{2,120}$/,121)}
function regsSearchParams(args){const p=new URLSearchParams();p.set("page[size]",String(clamp(args?.limit,1,100,20)));p.set("page[number]",String(clamp(args?.page,1,20,1)));if(args?.query)p.set("filter[searchTerm]",req(args.query,"query",240));if(args?.agency_id){const a=arr(args.agency_id,10);if(a.some(x=>!/^[A-Z0-9-]{2,20}$/i.test(x)))err("INVALID_AGENCY_ID");p.set("filter[agencyId]",a.join(","))}if(args?.docket_id)p.set("filter[docketId]",regId(args.docket_id,"docket_id"));if(args?.start_date)p.set("filter[postedDate][ge]",isoDate(args.start_date,"start_date"));if(args?.end_date)p.set("filter[postedDate][le]",isoDate(args.end_date,"end_date"));p.set("sort",args?.sort==="asc"?"postedDate":"-postedDate");return p}
async function regulations(operation,args,env){const h=regsHeaders(env);if(operation==="documents"||operation==="dockets"){const u=new URL(`${REGS}/${operation}`),p=regsSearchParams(args);for(const[k,v]of p)u.searchParams.set(k,v);const body=await request(u,{headers:h});return{provider:"regulations_gov",operation,items:Array.isArray(body?.data)?body.data:[],meta:body?.meta||null}}
 if(operation==="document"){const id=regId(args?.document_id,"document_id"),body=await request(`${REGS}/documents/${encodeURIComponent(id)}`,{headers:h});return{provider:"regulations_gov",operation,document_id:id,data:body?.data||body}}
 if(operation==="docket"){const id=regId(args?.docket_id,"docket_id"),body=await request(`${REGS}/dockets/${encodeURIComponent(id)}`,{headers:h});return{provider:"regulations_gov",operation,docket_id:id,data:body?.data||body}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const CATALOG=[{provider:"federal_register",role:"US-federal-rules-proposed-rules-notices-presidential-documents",auth:"public",legal_note:"informational index; cross-check govinfo for controlling legal text"},{provider:"congress_gov",role:"US-legislation-bills-and-actions",auth:"CONGRESS_GOV_API_KEY"},{provider:"regulations_gov",role:"US-rulemaking-documents-and-dockets",auth:"REGULATIONS_GOV_API_KEY",write_policy:"read-only; comment submission deliberately not exposed"}];
export const OPERATIONS={federal_register:["documents","document","agencies"],congress_gov:["bills","bill","bill_actions"],regulations_gov:["documents","document","dockets","docket"],splus_policy_regulatory_primary:["catalog"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="federal_register")return federalRegister(operation,args);if(provider==="congress_gov")return congress(operation,args,env);if(provider==="regulations_gov")return regulations(operation,args,env);if(provider==="splus_policy_regulatory_primary")return{provider,operation,items:CATALOG};err("ADAPTER_NOT_IMPLEMENTED",501)}
