import {OPERATIONS as CORE_OPERATIONS,runAdapter as runCore} from "./adapters-core.js";
import {OPERATIONS as EXTRA_OPERATIONS,runAdapter as runExtra} from "./adapters-extra.js";
import {OPERATIONS as EXTRA2_OPERATIONS,runAdapter as runExtra2} from "./adapters-extra2.js";
import {OPERATIONS as EXTRA3_OPERATIONS,runAdapter as runExtra3} from "./adapters-extra3.js";
import {OPERATIONS as EXTRA4_OPERATIONS,runAdapter as runExtra4} from "./adapters-extra4.js";
import {OPERATIONS as EXTRA5_OPERATIONS,runAdapter as runExtra5} from "./adapters-extra5.js";
import {OPERATIONS as EXTRA6_OPERATIONS,runAdapter as runExtra6} from "./adapters-extra6.js";
import {OPERATIONS as EXTRA7_OPERATIONS,runAdapter as runExtra7} from "./adapters-extra7.js";
import {OPERATIONS as EXTRA8_OPERATIONS,runAdapter as runExtra8} from "./adapters-extra8.js";
import {OPERATIONS as EXTRA9_OPERATIONS,runAdapter as runExtra9} from "./adapters-extra9.js";
import {OPERATIONS as EXTRA10_OPERATIONS,runAdapter as runExtra10} from "./adapters-extra10.js";
import {OPERATIONS as EXTRA11_OPERATIONS,runAdapter as runExtra11} from "./adapters-extra11.js";
import {OPERATIONS as EXTRA12_OPERATIONS,runAdapter as runExtra12} from "./adapters-extra12.js";
import {OPERATIONS as EXTRA13_OPERATIONS,runAdapter as runExtra13} from "./adapters-extra13.js";
import {OPERATIONS as EXTRA14_OPERATIONS,runAdapter as runExtra14} from "./adapters-extra14.js";
import {OPERATIONS as EXTRA15_OPERATIONS,runAdapter as runExtra15} from "./adapters-extra15.js";
import {OPERATIONS as EXTRA16_OPERATIONS,runAdapter as runExtra16} from "./adapters-extra16.js";
import {OPERATIONS as EXTRA17_OPERATIONS,runAdapter as runExtra17} from "./adapters-extra17.js";
import {OPERATIONS as EXTRA18_OPERATIONS,runAdapter as runExtra18} from "./adapters-extra18.js";
import {OPERATIONS as EXTRA19_OPERATIONS,runAdapter as runExtra19} from "./adapters-extra19.js";
import {OPERATIONS as EXTRA20_OPERATIONS,runAdapter as runExtra20} from "./adapters-extra20.js";
import {OPERATIONS as EXTRA21_OPERATIONS,runAdapter as runExtra21} from "./adapters-extra21.js";
import {OPERATIONS as EXTRA22_OPERATIONS,runAdapter as runExtra22} from "./adapters-extra22.js";
import {OPERATIONS as EXTRA23_OPERATIONS,runAdapter as runExtra23} from "./adapters-extra23.js";
import {OPERATIONS as EXTRA24_OPERATIONS,runAdapter as runExtra24} from "./adapters-extra24.js";
import {OPERATIONS as EXTRA25_OPERATIONS,runAdapter as runExtra25} from "./adapters-extra25.js";
import {OPERATIONS as EXTRA26_OPERATIONS,runAdapter as runExtra26} from "./adapters-extra26.js";
import {OPERATIONS as EXTRA27_OPERATIONS,runAdapter as runExtra27} from "./adapters-extra27.js";
import {OPERATIONS as EXTRA28_OPERATIONS,runAdapter as runExtra28} from "./adapters-extra28.js";
import {OPERATIONS as EXTRA29_OPERATIONS,runAdapter as runExtra29} from "./adapters-extra29.js";
import {OPERATIONS as EXTRA30_OPERATIONS,runAdapter as runExtra30} from "./adapters-extra30.js";
import {OPERATIONS as EXTRA31_OPERATIONS,runAdapter as runExtra31} from "./adapters-extra31.js";
import {OPERATIONS as EXTRA32_OPERATIONS,runAdapter as runExtra32} from "./adapters-extra32.js";
import {OPERATIONS as EXTRA33_OPERATIONS,runAdapter as runExtra33} from "./adapters-extra33.js";
import {OPERATIONS as EXTRA34_OPERATIONS,runAdapter as runExtra34} from "./adapters-extra34.js";
import {OPERATIONS as EXTRA35_OPERATIONS,runAdapter as runExtra35} from "./adapters-extra35.js";
import {OPERATIONS as EXTRA36_OPERATIONS,runAdapter as runExtra36} from "./adapters-extra36.js";
import {OPERATIONS as EXTRA37_OPERATIONS,runAdapter as runExtra37} from "./adapters-extra37.js";
import {OPERATIONS as EXTRA38_OPERATIONS,runAdapter as runExtra38} from "./adapters-extra38.js";
const OPSETS=[CORE_OPERATIONS,EXTRA_OPERATIONS,EXTRA2_OPERATIONS,EXTRA3_OPERATIONS,EXTRA4_OPERATIONS,EXTRA5_OPERATIONS,EXTRA6_OPERATIONS,EXTRA7_OPERATIONS,EXTRA8_OPERATIONS,EXTRA9_OPERATIONS,EXTRA10_OPERATIONS,EXTRA11_OPERATIONS,EXTRA12_OPERATIONS,EXTRA13_OPERATIONS,EXTRA14_OPERATIONS,EXTRA15_OPERATIONS,EXTRA16_OPERATIONS,EXTRA17_OPERATIONS,EXTRA18_OPERATIONS,EXTRA19_OPERATIONS,EXTRA20_OPERATIONS,EXTRA21_OPERATIONS,EXTRA22_OPERATIONS,EXTRA23_OPERATIONS,EXTRA24_OPERATIONS,EXTRA25_OPERATIONS,EXTRA26_OPERATIONS,EXTRA27_OPERATIONS,EXTRA28_OPERATIONS,EXTRA29_OPERATIONS,EXTRA30_OPERATIONS,EXTRA31_OPERATIONS,EXTRA32_OPERATIONS,EXTRA33_OPERATIONS,EXTRA34_OPERATIONS,EXTRA35_OPERATIONS,EXTRA36_OPERATIONS,EXTRA37_OPERATIONS,EXTRA38_OPERATIONS];
export const OPERATIONS={};
for(const group of OPSETS)for(const[provider,ops]of Object.entries(group))OPERATIONS[provider]=[...new Set([...(OPERATIONS[provider]||[]),...ops])];
export async function runAdapter(provider,operation,args,env){
  if(EXTRA38_OPERATIONS[provider]?.includes(operation))return runExtra38(provider,operation,args,env);
  if(EXTRA37_OPERATIONS[provider]?.includes(operation))return runExtra37(provider,operation,args,env);
  if(EXTRA36_OPERATIONS[provider]?.includes(operation))return runExtra36(provider,operation,args,env);
  if(EXTRA35_OPERATIONS[provider]?.includes(operation))return runExtra35(provider,operation,args,env);
  if(EXTRA34_OPERATIONS[provider]?.includes(operation))return runExtra34(provider,operation,args,env);
  if(EXTRA33_OPERATIONS[provider]?.includes(operation))return runExtra33(provider,operation,args,env);
  if(EXTRA32_OPERATIONS[provider]?.includes(operation))return runExtra32(provider,operation,args,env);
  if(EXTRA31_OPERATIONS[provider]?.includes(operation))return runExtra31(provider,operation,args,env);
  if(EXTRA30_OPERATIONS[provider]?.includes(operation))return runExtra30(provider,operation,args,env);
  if(EXTRA29_OPERATIONS[provider]?.includes(operation))return runExtra29(provider,operation,args,env);
  if(EXTRA28_OPERATIONS[provider]?.includes(operation))return runExtra28(provider,operation,args,env);
  if(EXTRA27_OPERATIONS[provider]?.includes(operation))return runExtra27(provider,operation,args,env);
  if(EXTRA26_OPERATIONS[provider]?.includes(operation))return runExtra26(provider,operation,args,env);
  if(EXTRA25_OPERATIONS[provider]?.includes(operation))return runExtra25(provider,operation,args,env);
  if(EXTRA24_OPERATIONS[provider]?.includes(operation))return runExtra24(provider,operation,args,env);
  if(EXTRA23_OPERATIONS[provider]?.includes(operation))return runExtra23(provider,operation,args,env);
  if(EXTRA22_OPERATIONS[provider]?.includes(operation))return runExtra22(provider,operation,args,env);
  if(EXTRA21_OPERATIONS[provider]?.includes(operation))return runExtra21(provider,operation,args,env);
  if(EXTRA20_OPERATIONS[provider]?.includes(operation))return runExtra20(provider,operation,args,env);
  if(EXTRA19_OPERATIONS[provider]?.includes(operation))return runExtra19(provider,operation,args,env);
  if(EXTRA18_OPERATIONS[provider]?.includes(operation))return runExtra18(provider,operation,args,env);
  if(EXTRA17_OPERATIONS[provider]?.includes(operation))return runExtra17(provider,operation,args,env);
  if(EXTRA16_OPERATIONS[provider]?.includes(operation))return runExtra16(provider,operation,args,env);
  if(EXTRA15_OPERATIONS[provider]?.includes(operation))return runExtra15(provider,operation,args,env);
  if(EXTRA14_OPERATIONS[provider]?.includes(operation))return runExtra14(provider,operation,args,env);
  if(EXTRA13_OPERATIONS[provider]?.includes(operation))return runExtra13(provider,operation,args,env);
  if(EXTRA12_OPERATIONS[provider]?.includes(operation))return runExtra12(provider,operation,args,env);
  if(EXTRA11_OPERATIONS[provider]?.includes(operation))return runExtra11(provider,operation,args,env);
  if(EXTRA10_OPERATIONS[provider]?.includes(operation))return runExtra10(provider,operation,args,env);
  if(EXTRA9_OPERATIONS[provider]?.includes(operation))return runExtra9(provider,operation,args,env);
  if(EXTRA8_OPERATIONS[provider]?.includes(operation))return runExtra8(provider,operation,args,env);
  if(EXTRA7_OPERATIONS[provider]?.includes(operation))return runExtra7(provider,operation,args,env);
  if(EXTRA6_OPERATIONS[provider]?.includes(operation))return runExtra6(provider,operation,args,env);
  if(EXTRA5_OPERATIONS[provider]?.includes(operation))return runExtra5(provider,operation,args,env);
  if(EXTRA4_OPERATIONS[provider]?.includes(operation))return runExtra4(provider,operation,args,env);
  if(EXTRA3_OPERATIONS[provider]?.includes(operation))return runExtra3(provider,operation,args,env);
  if(EXTRA2_OPERATIONS[provider]?.includes(operation))return runExtra2(provider,operation,args,env);
  if(EXTRA_OPERATIONS[provider]?.includes(operation))return runExtra(provider,operation,args,env);
  return runCore(provider,operation,args,env);
}
