const MAX_BYTES=1800000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function req(v,name,n=300){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function tok(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=req(v,name,n);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function arr(v,n=20){return(Array.isArray(v)?v:String(v??"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,n)}
function secret(env,name){const s=text(env?.[name],300);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x)){if(["crtfc_key","api_key","apikey","authorization","x-app-token","app_token","token"].includes(k.toLowerCase()))o[k]="[redacted]";else o[k]=redact(v)}return o}return x}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":r.status===404?"UPSTREAM_NOT_FOUND":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:r.status===404?404:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.message||body?.error||raw,400)});return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

const CH="https://api.company-information.service.gov.uk";
function companyNumber(v){return tok(v,"company_number",/^[A-Za-z0-9]{6,10}$/,10).toUpperCase()}
function chHeaders(env){const key=secret(env,"COMPANIES_HOUSE_API_KEY");return{authorization:`Basic ${btoa(`${key}:`)}`}}
async function companiesHouse(operation,args,env){if(operation==="search_companies"){const u=new URL(`${CH}/search/companies`);u.searchParams.set("q",req(args?.query,"query",180));u.searchParams.set("items_per_page",String(clamp(args?.limit,1,100,20)));u.searchParams.set("start_index",String(clamp(args?.start_index,0,10000,0)));const body=await request(u,{headers:chHeaders(env)});return{provider:"companies_house_uk",operation,total:body?.total_results??null,items:Array.isArray(body?.items)?body.items:[]}}
 if(operation==="company_profile"){const no=companyNumber(args?.company_number),body=await request(`${CH}/company/${encodeURIComponent(no)}`,{headers:chHeaders(env)});return{provider:"companies_house_uk",operation,company_number:no,data:body}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const DART="https://engopendart.fss.or.kr/engapi";
function dartKey(env){const k=secret(env,"OPENDART_API_KEY");if(!/^[A-Za-z0-9]{40}$/.test(k))err("UPSTREAM_AUTH_FAILED",503,{invalid:"OPENDART_API_KEY"});return k}
function corpCode(v){return tok(v,"corp_code",/^\d{8}$/,8)}
function ymd(v,name){const s=tok(v,name,/^\d{8}$/,8),y=Number(s.slice(0,4)),m=Number(s.slice(4,6)),d=Number(s.slice(6,8)),dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d)err(`INVALID_${name.toUpperCase()}`);return s}
function dartRange(a,b){const start=ymd(a,"bgn_de"),end=ymd(b,"end_de");if(start>end)err("INVALID_DATE_RANGE");const ms=Date.UTC(+end.slice(0,4),+end.slice(4,6)-1,+end.slice(6,8))-Date.UTC(+start.slice(0,4),+start.slice(4,6)-1,+start.slice(6,8));if(ms/86400000>93)err("DART_DATE_RANGE_TOO_LARGE",413,{max_days_without_corp_code:93});return[start,end]}
async function opendart(operation,args,env){const key=dartKey(env);if(operation==="disclosures"){const u=new URL(`${DART}/list.json`);u.searchParams.set("crtfc_key",key);if(args?.corp_code)u.searchParams.set("corp_code",corpCode(args.corp_code));let start=args?.bgn_de?ymd(args.bgn_de,"bgn_de"):"",end=args?.end_de?ymd(args.end_de,"end_de"):"";if(!args?.corp_code){if(!start||!end)err("ARG_REQUIRED:bgn_de_and_end_de_without_corp_code");[start,end]=dartRange(start,end)}else if(start&&end&&start>end)err("INVALID_DATE_RANGE");if(start)u.searchParams.set("bgn_de",start);if(end)u.searchParams.set("end_de",end);if(args?.last_reprt_at!==undefined)u.searchParams.set("last_reprt_at",args.last_reprt_at===true?"Y":"N");if(args?.pblntf_ty)u.searchParams.set("pblntf_ty",tok(args.pblntf_ty,"pblntf_ty",/^[A-J]$/i,1).toUpperCase());if(args?.corp_cls)u.searchParams.set("corp_cls",tok(args.corp_cls,"corp_cls",/^[YKNE]$/i,1).toUpperCase());u.searchParams.set("sort",["date","crp","rpt"].includes(args?.sort)?args.sort:"date");u.searchParams.set("sort_mth",args?.sort_mth==="asc"?"asc":"desc");u.searchParams.set("page_no",String(clamp(args?.page,1,99999,1)));u.searchParams.set("page_count",String(clamp(args?.limit,1,100,20)));const body=await request(u);return{provider:"opendart_korea",operation,status:body?.status||null,message:body?.message||null,page_no:body?.page_no??null,total_count:body?.total_count??null,items:Array.isArray(body?.list)?body.list:[]}}
 if(operation==="company"){const code=corpCode(args?.corp_code),u=new URL(`${DART}/company.json`);u.searchParams.set("crtfc_key",key);u.searchParams.set("corp_code",code);return{provider:"opendart_korea",operation,corp_code:code,data:await request(u)}}
 if(operation==="major_accounts"){const code=corpCode(args?.corp_code),year=tok(args?.bsns_year,"bsns_year",/^\d{4}$/,4),report=tok(args?.reprt_code,"reprt_code",/^1101[1-4]$/,5);if(!new Set(["11011","11012","11013","11014"]).has(report))err("INVALID_REPRT_CODE");const u=new URL(`${DART}/fnlttSinglAcnt.json`);u.searchParams.set("crtfc_key",key);u.searchParams.set("corp_code",code);u.searchParams.set("bsns_year",year);u.searchParams.set("reprt_code",report);const body=await request(u);return{provider:"opendart_korea",operation,corp_code:code,bsns_year:year,reprt_code:report,status:body?.status||null,message:body?.message||null,items:Array.isArray(body?.list)?body.list:[]}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const CFTC="https://publicreporting.cftc.gov/resource";
const CFTC_DATASETS={tff_combined:"yw9f-hn96",disaggregated_combined:"kh3c-gbw2",product_hierarchy:"rj6x-va3z"};
function socrataHeaders(env){const t=text(env?.CFTC_APP_TOKEN,200);return t?{"X-App-Token":t}:{}}
async function cftc(operation,args,env){const id=CFTC_DATASETS[operation];if(!id)err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`${CFTC}/${id}.json`);u.searchParams.set("$limit",String(clamp(args?.limit,1,500,100)));u.searchParams.set("$offset",String(clamp(args?.offset,0,10000000,0)));const fields=arr(args?.fields,30);if(fields.length){if(fields.some(x=>!/^[A-Za-z_][A-Za-z0-9_]*$/.test(x)))err("INVALID_CFTC_FIELD");u.searchParams.set("$select",fields.join(","))}if(args?.order_by){const f=tok(args.order_by,"order_by",/^[A-Za-z_][A-Za-z0-9_]*$/,80),dir=String(args?.order||"desc").toLowerCase();if(!["asc","desc"].includes(dir))err("INVALID_CFTC_ORDER");u.searchParams.set("$order",`${f} ${dir}`)}const filters=args?.filters&&typeof args.filters==="object"&&!Array.isArray(args.filters)?Object.entries(args.filters).slice(0,10):[];for(const[k,v]of filters){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(k))err("INVALID_CFTC_FILTER_FIELD");const vals=arr(v,2);if(vals.length!==1)err("INVALID_CFTC_FILTER_VALUE");u.searchParams.set(k,text(vals[0],160))}const body=await request(u,{headers:socrataHeaders(env)});return{provider:"cftc_cot",operation,dataset_id:id,items:Array.isArray(body)?body:[]}}

const TED="https://api.ted.europa.eu/v3/notices/search";
const TED_DEFAULT_FIELDS=["publication-number","notice-title","buyer-name","notice-type"];
function tedQuery(v){const s=req(v,"query",500);if(/[\u0000-\u001f\u007f]/.test(s))err("INVALID_TED_QUERY");return s}
function tedFields(v){const a=(v?arr(v,20):TED_DEFAULT_FIELDS);if(!a.length||a.some(x=>!^[A-Za-z0-9_.()\-]+$/.test(x)))err("INVALID_TED_FIELD");return a}
async function ted(operation,args){if(operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403);const payload={query:tedQuery(args?.query),fields:tedFields(args?.fields),page:clamp(args?.page,1,300,1),limit:clamp(args?.limit,1,50,20),checkQuerySyntax:true,paginationMode:"PAGE_NUMBER"};const body=await request(TED,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"ted_eu_procurement",operation,total:body?.totalNoticeCount??body?.total??null,items:Array.isArray(body?.notices)?body.notices:Array.isArray(body?.results)?body.results:[],pagination:{page:payload.page,limit:payload.limit,mode:"PAGE_NUMBER"}}}

const CATALOG=[
 {provider:"companies_house_uk",role:"UK-company-register-live-profile-and-search",auth:"COMPANIES_HOUSE_API_KEY"},
 {provider:"opendart_korea",role:"Korea-disclosures-company-profile-and-periodic-financial-accounts",auth:"OPENDART_API_KEY"},
 {provider:"cftc_cot",role:"US-regulatory-trader-positioning-and-product-hierarchy",auth:"public; CFTC_APP_TOKEN optional"},
 {provider:"ted_eu_procurement",role:"EU-published-public-procurement-notices",auth:"public"}
];
export const OPERATIONS={companies_house_uk:["search_companies","company_profile"],opendart_korea:["disclosures","company","major_accounts"],cftc_cot:["tff_combined","disaggregated_combined","product_hierarchy"],ted_eu_procurement:["search"],splus_corporate_markets_procurement:["catalog"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="companies_house_uk")return companiesHouse(operation,args,env);if(provider==="opendart_korea")return opendart(operation,args,env);if(provider==="cftc_cot")return cftc(operation,args,env);if(provider==="ted_eu_procurement")return ted(operation,args);if(provider==="splus_corporate_markets_procurement")return{provider,operation,items:CATALOG};err("ADAPTER_NOT_IMPLEMENTED",501)}
