const round=(v,d=1)=>{const p=10**d;return Math.round((Number(v)+Number.EPSILON)*p)/p};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function num(v,name,min=-Infinity,max=Infinity){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)err(`INVALID_${name.toUpperCase()}`);return n}
function bool(v,name){if(typeof v!=="boolean")err(`INVALID_${name.toUpperCase()}`);return v}
function sex(v){const s=String(v??"").trim().toLowerCase();if(!["male","female"].includes(s))err("INVALID_SEX");return s}
function creatinineMgDl(value,unit){const n=num(value,"serum_creatinine",0.01,30),u=String(unit||"mg/dL").toLowerCase();if(["mg/dl","mgdl"].includes(u))return n;if(["umol/l","µmol/l","μmol/l"].includes(u))return n/88.4;err("INVALID_CREATININE_UNIT")}
function bmiCategory(bmi){if(bmi<18.5)return"underweight";if(bmi<25)return"normal-range";if(bmi<30)return"overweight";return"obesity"}
function bmi(args){const weight=num(args?.weight_kg,"weight_kg",1,500),height=num(args?.height_m,"height_m",0.3,2.8),value=weight/(height*height);return{provider:"medical_clinical_calculators",operation:"bmi",bmi:round(value,1),adult_who_category:bmiCategory(value),units:"kg/m^2",source:"WHO adult BMI definition"}}
function egfrCr(args){const age=num(args?.age_years,"age_years",18,120),sx=sex(args?.sex),scr=creatinineMgDl(args?.serum_creatinine,args?.creatinine_unit),female=sx==="female",k=female?0.7:0.9,alpha=female?-0.241:-0.302,value=142*(Math.min(scr/k,1)**alpha)*(Math.max(scr/k,1)**-1.2)*(0.9938**age)*(female?1.012:1);return{provider:"medical_clinical_calculators",operation:"egfr_2021_creatinine",egfr_ml_min_1_73m2:round(value,1),age_years:age,sex:sx,serum_creatinine_mg_dl:round(scr,3),equation:"2021 CKD-EPI creatinine",source:"NIDDK"}}
function egfrCrCys(args){const age=num(args?.age_years,"age_years",18,120),sx=sex(args?.sex),scr=creatinineMgDl(args?.serum_creatinine,args?.creatinine_unit),scys=num(args?.cystatin_c_mg_l,"cystatin_c_mg_l",0.05,20),female=sx==="female",k=female?0.7:0.9,alpha=female?-0.219:-0.144,value=135*(Math.min(scr/k,1)**alpha)*(Math.max(scr/k,1)**-0.544)*(Math.min(scys/0.8,1)**-0.323)*(Math.max(scys/0.8,1)**-0.778)*(0.9961**age)*(female?0.963:1);return{provider:"medical_clinical_calculators",operation:"egfr_2021_creatinine_cystatin_c",egfr_ml_min_1_73m2:round(value,1),age_years:age,sex:sx,serum_creatinine_mg_dl:round(scr,3),cystatin_c_mg_l:scys,equation:"2021 CKD-EPI creatinine-cystatin C",source:"NIDDK"}}
function crbCore(args,withUrea){const confusion=bool(args?.confusion,"confusion"),rr=num(args?.respiratory_rate,"respiratory_rate",0,100),sbp=num(args?.systolic_bp,"systolic_bp",20,300),dbp=num(args?.diastolic_bp,"diastolic_bp",10,200),age=num(args?.age_years,"age_years",16,120);let score=(confusion?1:0)+(rr>=30?1:0)+(dbp<=60||sbp<90?1:0)+(age>=65?1:0),urea=null;if(withUrea){urea=num(args?.urea_mmol_l,"urea_mmol_l",0,100);if(urea>7)score++}return{score,components:{confusion,urea_over_7_mmol_l:withUrea?urea>7:undefined,respiratory_rate_at_least_30:rr>=30,low_blood_pressure:dbp<=60||sbp<90,age_at_least_65:age>=65}}}
function crb65(args){const x=crbCore(args,false),risk=x.score===0?"low (<1% 30-day mortality)":x.score<=2?"intermediate (1-10% 30-day mortality)":"high (>10% 30-day mortality)";return{provider:"medical_clinical_calculators",operation:"crb65",...x,nice_risk_group:risk,source:"NICE NG250 2025"}}
function curb65(args){const x=crbCore(args,true),risk=x.score<=1?"low (<3% mortality)":x.score===2?"intermediate (3-15% mortality)":"high (>15% mortality)";return{provider:"medical_clinical_calculators",operation:"curb65",...x,nice_risk_group:risk,source:"NICE NG250 2025"}}
function qsofa(args){const rr=num(args?.respiratory_rate,"respiratory_rate",0,100),sbp=num(args?.systolic_bp,"systolic_bp",20,300);let altered;if(typeof args?.altered_mentation==="boolean")altered=args.altered_mentation;else if(args?.gcs!=null)altered=num(args.gcs,"gcs",3,15)<15;else err("ARG_REQUIRED:altered_mentation_or_gcs");const components={respiratory_rate_at_least_22:rr>=22,altered_mentation:altered,systolic_bp_at_most_100:sbp<=100},score=Object.values(components).filter(Boolean).length;return{provider:"medical_clinical_calculators",operation:"qsofa",score,positive_two_or_more:score>=2,components,source:"Sepsis-3 qSOFA criteria"}}
export const OPERATIONS={medical_clinical_calculators:["bmi","egfr_2021_creatinine","egfr_2021_creatinine_cystatin_c","crb65","curb65","qsofa"]};
export async function runAdapter(provider,operation,args={}){if(provider!=="medical_clinical_calculators"||!OPERATIONS[provider].includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation});if(operation==="bmi")return bmi(args);if(operation==="egfr_2021_creatinine")return egfrCr(args);if(operation==="egfr_2021_creatinine_cystatin_c")return egfrCrCys(args);if(operation==="crb65")return crb65(args);if(operation==="curb65")return curb65(args);return qsofa(args)}