const TIMEOUT_MS=18000,MAX_BYTES=1600000;
const FUNCTIONS=Object.freeze({stock_zh_a_hist:"stock_zh_a_hist",stock_zh_a_spot_em:"stock_zh_a_spot_em",stock_hk_hist:"stock_hk_hist",stock_us_hist:"stock_us_hist",index_zh_a_hist:"index_zh_a_hist",fund_etf_hist_em:"fund_etf_hist_em"});
export const OPERATIONS={akshare:Object.keys(FUNCTIONS),aktools:["health",...Object.keys(FUNCTIONS)]};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function text(v,n=2000){return String(v??"").trim().slice(0,n)}
function baseUrl(env){const raw=text(env?.AKTOOLS_BASE_URL,1000);if(!raw)err("UPSTREAM_AUTH_FAILED",503,{missing:"AKTOOLS_BASE_URL"});let u;try{u=new URL(raw)}catch{err("AKTOOLS_BASE_URL_INVALID",503)}if(u.protocol!=="https:"||u.username||u.password||u.search||u.hash)err("AKTOOLS_BASE_URL_INVALID",503,{requirement:"https URL without credentials/query/fragment"});u.pathname=u.pathname.replace(/\/+$/g,"")+"/";return u}
function cleanParams(args){const out={};for(const[k,v]of Object.entries(args&&typeof args==="object"&&!Array.isArray(args)?args:{})){if(!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(k))err("INVALID_ARG_KEY",400,{key:text(k,80)});if(v===undefined||v===null||v==="")continue;if(typeof v==="string"||typeof v==="number"||typeof v==="boolean")out[k]=String(v).slice(0,500);else err("INVALID_ARG_TYPE",400,{key:k})}return out}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502,{limit:MAX_BYTES})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function getJson(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{method:"GET",signal:c.signal,headers:{accept:"application/json","user-agent":"three-center-intelligence-aktools/1.0"}}),raw=await readBounded(r);if(!r.ok)err(r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",r.status===429?429:502,{http_status:r.status,message:text(raw,300)});try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{preview:text(raw,200)})}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
async function call(operation,args,env){const fn=FUNCTIONS[operation];if(!fn)err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`api/public/${fn}`,baseUrl(env));for(const[k,v]of Object.entries(cleanParams(args)))u.searchParams.set(k,v);const data=await getJson(u);return{provider:"akshare",operation,function:fn,transport:"AKTools HTTP",source:"AKShare public-source interface",items:Array.isArray(data)?data:data?.data??data,source_terms_note:"AKShare data originate from public sources; upstream/source terms and research-use warnings remain applicable."}}
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="aktools"&&operation==="health"){const data=await getJson(new URL("",baseUrl(env)));return{provider,operation,ok:true,endpoint_configured:true,response_type:Array.isArray(data)?"array":typeof data}}return call(operation,args,env)}
