const MAX_BYTES=1200000,TIMEOUT_MS=20000;
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
const text=(v,n=8000)=>String(v??"").trim().slice(0,n);
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function required(v,name,n=500){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function secret(env,name){const s=text(env?.[name],500);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function arr(v,n=20){return(Array.isArray(v)?v:[]).map(x=>text(x,240)).filter(Boolean).slice(0,n)}
function safeDate(v,name){if(!v)return null;const s=text(v,40);if(!/^\d{4}-\d{2}-\d{2}(T.*)?$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x))o[k]=/token|secret|authorization|api.?key/i.test(k)?"[redacted]":redact(v);return o}return x}
async function boundedText(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await boundedText(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok){const auth=r.status===401||r.status===403;err(auth?"UPSTREAM_AUTH_FAILED":r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",auth?503:r.status===429?429:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.message||body?.error||raw,500)})}return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

function exaResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),published_date:text(x?.publishedDate,80)||null,author:text(x?.author,300)||null,highlights:Array.isArray(x?.highlights)?x.highlights.map(v=>text(v,2000)).slice(0,8):[]}}
async function exaSearch(args,env){const query=required(args?.query,"query"),body={query,type:["auto","fast","instant","deep-lite"].includes(args?.type)?args.type:"auto",numResults:clamp(args?.limit,1,20,8),contents:{highlights:true}};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.includeDomains=include;if(exclude.length)body.excludeDomains=exclude;const start=safeDate(args?.start_published_date,"start_published_date"),end=safeDate(args?.end_published_date,"end_published_date");if(start)body.startPublishedDate=start;if(end)body.endPublishedDate=end;const out=await request("https://api.exa.ai/search",{method:"POST",headers:{"content-type":"application/json","x-api-key":secret(env,"EXA_API_KEY")},body:JSON.stringify(body)});return{provider:"exa",operation:"search",query,items:Array.isArray(out?.results)?out.results.map(exaResult):[],request_id:out?.requestId||null,cost_dollars:out?.costDollars||null,source_mode:"official-search-api; highlights-only; bounded"}}

function tavilyResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),content:text(x?.content,4000),score:Number.isFinite(Number(x?.score))?Number(x.score):null,published_date:text(x?.published_date||x?.publishedDate,80)||null}}
async function tavilySearch(args,env){const query=required(args?.query,"query"),body={query,search_depth:args?.search_depth==="advanced"?"advanced":"basic",topic:["general","news","finance"].includes(args?.topic)?args.topic:"general",max_results:clamp(args?.limit,1,20,8),include_answer:false,include_raw_content:false};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.include_domains=include;if(exclude.length)body.exclude_domains=exclude;if(args?.country)body.country=text(args.country,80).toLowerCase();if(["day","week","month","year","d","w","m","y"].includes(args?.time_range))body.time_range=args.time_range;const out=await request("https://api.tavily.com/search",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${secret(env,"TAVILY_API_KEY")}`},body:JSON.stringify(body)});return{provider:"tavily",operation:"search",query,items:Array.isArray(out?.results)?out.results.map(tavilyResult):[],request_id:out?.request_id||null,usage:out?.usage||null,response_time:out?.response_time||null,source_mode:"official-search-api; basic-by-default; no-generated-answer; no-raw-content"}}

function firecrawlResult(x){return{title:text(x?.title,500),url:text(x?.url,2000),description:text(x?.description,4000),category:text(x?.category,100)||null}}
async function firecrawlSearch(args,env){const query=required(args?.query,"query",500),body={query,limit:clamp(args?.limit,1,20,8),sources:["web"],timeout:Math.min(15000,clamp(args?.timeout_ms,1000,15000,12000)),ignoreInvalidURLs:true};const include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20);if(include.length)body.includeDomains=include;if(exclude.length)body.excludeDomains=exclude;if(args?.country)body.country=text(args.country,2).toUpperCase();if(args?.tbs)body.tbs=text(args.tbs,120);const out=await request("https://api.firecrawl.dev/v2/search",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${secret(env,"FIRECRAWL_API_KEY")}`},body:JSON.stringify(body)});const web=Array.isArray(out?.data?.web)?out.data.web:Array.isArray(out?.data)?out.data:[];return{provider:"firecrawl",operation:"search",query,items:web.map(firecrawlResult),success:out?.success===true,source_mode:"official-v2-search; web-only; no scrape/crawl/browser operations exposed"}}

function jinaItem(x){return{title:text(x?.title,500),url:text(x?.url,2000),content:text(x?.content,6000),published_time:text(x?.publishedTime||x?.published_time,100)||null}}
async function jinaSearch(args,env){const query=required(args?.query,"query",500),u=new URL("https://s.jina.ai/");u.searchParams.set("q",query);const out=await request(u,{headers:{accept:"application/json",authorization:`Bearer ${secret(env,"JINA_API_KEY")}`,"x-retain-images":"none"}});let items=[];if(Array.isArray(out))items=out;else if(Array.isArray(out?.data))items=out.data;else if(out&&typeof out==="object")items=[out];else if(typeof out==="string")return{provider:"jina",operation:"search",query,items:[],content:text(out,30000),source_mode:"official-s.jina.ai search grounding; bounded"};return{provider:"jina",operation:"search",query,items:items.slice(0,5).map(jinaItem),source_mode:"official-s.jina.ai search grounding; fixed top-five; API-key authenticated"}}

export const OPERATIONS={exa:["search"],tavily:["search"],firecrawl:["search"],jina:["search"]};
export async function runAdapter(provider,operation,args={},env={}){if(operation!=="search"||!OPERATIONS[provider])err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation});if(provider==="exa")return exaSearch(args,env);if(provider==="tavily")return tavilySearch(args,env);if(provider==="firecrawl")return firecrawlSearch(args,env);if(provider==="jina")return jinaSearch(args,env);err("ADAPTER_NOT_IMPLEMENTED",501)}