const TIMEOUT_MS=18000,MAX_BYTES=1800000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function token(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function readBounded(r,maxBytes=MAX_BYTES){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>maxBytes)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>maxBytes){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={},expect="json"){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:expect==="json"?"application/json":"*/*",...(init.headers||{})}}),raw=await readBounded(r);if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(raw,400)});if(expect==="text")return raw;try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502)}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function period(v,name){const s=text(v,24);if(!s)return"";if(!/^\d{4}(-\d{2}(-\d{2})?)?$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function macro(operation,args){
 if(operation==="oecd_dataflows"){const u=new URL("https://sdmx.oecd.org/public/rest/dataflow/all");u.searchParams.set("format","jsondata");const b=await request(u);return{provider:"splus_macro",operation,source:"OECD",data:b}}
 if(operation==="oecd_data"){const flow=token(args?.flow,"flow",/^[A-Za-z0-9_.@,+-]+$/,220),key=text(args?.key||"all",350);if(!/^[A-Za-z0-9_.@,+-]*$/.test(key))err("INVALID_KEY");const u=new URL(`https://sdmx.oecd.org/public/rest/data/${encodeURIComponent(flow)}/${key||"all"}`);const start=period(args?.start,"start"),end=period(args?.end,"end");if(start)u.searchParams.set("startPeriod",start);if(end)u.searchParams.set("endPeriod",end);u.searchParams.set("dimensionAtObservation","AllDimensions");u.searchParams.set("format","jsondata");const b=await request(u);return{provider:"splus_macro",operation,source:"OECD",flow,data:b}}
 if(operation==="eurostat_data"){const dataset=token(args?.dataset,"dataset",/^[A-Za-z0-9_-]+$/,100),u=new URL(`https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/${encodeURIComponent(dataset)}`);u.searchParams.set("format","JSON");u.searchParams.set("lang","EN");const filters=args?.filters&&typeof args.filters==="object"&&!Array.isArray(args.filters)?Object.entries(args.filters).slice(0,12):[];for(const[k,v]of filters){if(!/^[A-Za-z0-9_-]{1,80}$/.test(k))err("INVALID_FILTER_KEY");const vals=(Array.isArray(v)?v:[v]).slice(0,20);for(const x of vals){const s=text(x,120);if(!/^[A-Za-z0-9_.:@,+-]+$/.test(s))err("INVALID_FILTER_VALUE");u.searchParams.append(k,s)}}const b=await request(u);return{provider:"splus_macro",operation,source:"Eurostat",dataset,data:b}}
 if(operation==="imf_source_info")return{provider:"splus_macro",operation,source:"IMF",interfaces:["SDMX 2.1","SDMX 3.0","DataMapper"],role:"authoritative-global-macroeconomic-financial-statistics",note:"Use IMF official machine interfaces; this branch avoids guessing dataset-specific dimensions."}
 if(operation==="bis_source_info")return{provider:"splus_macro",operation,source:"BIS",interface:"SDMX REST",endpoint:"https://stats.bis.org/api/v2",role:"global-banking-credit-property-fx-derivatives-financial-system-statistics"}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}
function isoDate(v,name){const s=text(v,30);if(!s)return"";if(!/^\d{4}-\d{2}-\d{2}(T[0-9:.+-]+Z?)?$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function risk(operation,args,env){
 if(operation==="nvd_cve"){const u=new URL("https://services.nvd.nist.gov/rest/json/cves/2.0"),k=text(env?.NVD_API_KEY,100);if(args?.cve_id)u.searchParams.set("cveId",token(args.cve_id,"cve_id",/^CVE-\d{4}-\d{4,10}$/i,40).toUpperCase());if(args?.keyword)u.searchParams.set("keywordSearch",text(args.keyword,220));if(args?.has_kev===true)u.searchParams.set("hasKev","");if(args?.start_index!==undefined)u.searchParams.set("startIndex",String(clamp(args.start_index,0,1000000,0)));u.searchParams.set("resultsPerPage",String(clamp(args?.limit,1,100,20)));const b=await request(u,{headers:k?{apiKey:k}:{}});return{provider:"splus_risk",operation,source:"NIST NVD",total:b?.totalResults??null,items:b?.vulnerabilities||[]}}
 if(operation==="cisa_kev"){const b=await request("https://raw.githubusercontent.com/cisagov/kev-data/develop/known_exploited_vulnerabilities.json");let items=Array.isArray(b?.vulnerabilities)?b.vulnerabilities:[];const q=text(args?.query,120).toLowerCase();if(q)items=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(args?.vendor)items=items.filter(x=>String(x?.vendorProject||"").toLowerCase().includes(text(args.vendor,80).toLowerCase()));return{provider:"splus_risk",operation,source:"CISA KEV official mirror",catalog_version:b?.catalogVersion||null,total:b?.count??items.length,items:items.slice(0,clamp(args?.limit,1,200,50))}}
 if(operation==="gleif_search"){const u=new URL("https://api.gleif.org/api/v1/lei-records");u.searchParams.set("page[size]",String(clamp(args?.limit,1,100,20)));if(args?.lei)u.searchParams.set("filter[lei]",token(args.lei,"lei",/^[A-Z0-9]{20}$/i,20).toUpperCase());if(args?.legal_name)u.searchParams.set("filter[entity.legalName]",text(args.legal_name,180));if(args?.country)u.searchParams.set("filter[entity.legalAddress.country]",token(args.country,"country",/^[A-Z]{2}$/i,2).toUpperCase());const b=await request(u);return{provider:"splus_risk",operation,source:"GLEIF",items:b?.data||[],meta:b?.meta||null}}
 if(operation==="usgs_earthquake"){const u=new URL("https://earthquake.usgs.gov/fdsnws/event/1/query");u.searchParams.set("format","geojson");const start=isoDate(args?.start,"start"),end=isoDate(args?.end,"end");if(start)u.searchParams.set("starttime",start);if(end)u.searchParams.set("endtime",end);if(args?.min_magnitude!==undefined){const n=Number(args.min_magnitude);if(!Number.isFinite(n)||n< -2||n>10)err("INVALID_MIN_MAGNITUDE");u.searchParams.set("minmagnitude",String(n))}if(args?.latitude!==undefined||args?.longitude!==undefined){const lat=Number(args.latitude),lon=Number(args.longitude),radius=Number(args.max_radius_km||500);if(!Number.isFinite(lat)||lat< -90||lat>90||!Number.isFinite(lon)||lon< -180||lon>180||!Number.isFinite(radius)||radius<=0||radius>20000)err("INVALID_GEO");u.searchParams.set("latitude",String(lat));u.searchParams.set("longitude",String(lon));u.searchParams.set("maxradiuskm",String(radius))}u.searchParams.set("limit",String(clamp(args?.limit,1,200,50)));u.searchParams.set("orderby","time");const b=await request(u);return{provider:"splus_risk",operation,source:"USGS",metadata:b?.metadata||null,items:b?.features||[]}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}
export const OPERATIONS={
 splus_macro:["oecd_dataflows","oecd_data","eurostat_data","imf_source_info","bis_source_info"],
 splus_risk:["nvd_cve","cisa_kev","gleif_search","usgs_earthquake"]
};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="splus_macro")return macro(operation,args);if(provider==="splus_risk")return risk(operation,args,env);err("ADAPTER_NOT_IMPLEMENTED",501)}