const BASE="https://stac.dataspace.copernicus.eu/v1";
const ADAPTER_VERSION="copernicus-cdse-stac-v2-20260817";
const MAX_BYTES=4000000,DEFAULT_TIMEOUT_MS=15000;
const text=(v,n=1200)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function safeId(v,name="id",max=220){const s=text(v,max);if(!s||!/^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function bbox(v){if(!Array.isArray(v)||v.length!==4)err("INVALID_BBOX");const a=v.map(Number);if(a.some(x=>!Number.isFinite(x)))err("INVALID_BBOX");const[w,s,e,n]=a;if(w<-180||e>180||s<-90||n>90||w>=e||s>=n)err("INVALID_BBOX");return a}
function datetime(v){if(v===undefined||v===null||v==="")return null;const s=text(v,100),dateOnly=/^\d{4}-\d{2}-\d{2}$/,stamp=/^\d{4}-\d{2}-\d{2}T[0-9:.+-]+Z?$/;const norm=(x,end=false)=>dateOnly.test(x)?`${x}T${end?"23:59:59.999":"00:00:00"}Z`:stamp.test(x)?x:null;if(s.includes("/")){const p=s.split("/");if(p.length!==2)err("INVALID_DATETIME");const a=norm(p[0],false),b=norm(p[1],true);if(!a||!b)err("INVALID_DATETIME");return`${a}/${b}`}const one=norm(s,false);if(!one)err("INVALID_DATETIME");return dateOnly.test(s)?`${s}T00:00:00Z/${s}T23:59:59.999Z`:one}
function collectionList(v){const raw=Array.isArray(v)?v:[v];const out=raw.filter(x=>x!==undefined&&x!==null&&String(x).trim()!=="").slice(0,8).map(x=>safeId(x,"collection",120));if(!out.length)err("ARG_REQUIRED:collections");return[...new Set(out)]}
async function request(path,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),DEFAULT_TIMEOUT_MS);try{const r=await fetch(`${BASE}${path}`,{...init,headers:{accept:"application/geo+json,application/json",...(init.headers||{})},signal:c.signal}),declared=Number(r.headers.get("content-length")||0);if(declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502,{http_status:r.status,bytes:declared});const raw=await r.text(),bytes=new TextEncoder().encode(raw).length;if(bytes>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502,{http_status:r.status,bytes});let body;try{body=raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{http_status:r.status})}if(!r.ok){const detail=body?.description||body?.message||(body?.detail?JSON.stringify(body.detail):null)||raw;err(r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",r.status===429?429:502,{http_status:r.status,message:text(detail,600)})}return body}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(t)}}
function collectionView(x){return{id:x?.id||null,title:text(x?.title,500)||null,description:text(x?.description,2500)||null,license:x?.license||null,keywords:Array.isArray(x?.keywords)?x.keywords.slice(0,40):[],providers:Array.isArray(x?.providers)?x.providers.slice(0,20):[],extent:x?.extent||null,assets:x?.assets||null,stac_version:x?.stac_version||null}}
function assetView(name,a={}){const alt=a?.alternate?.https?.href||null;return{name,title:text(a?.title,500)||null,type:a?.type||null,roles:Array.isArray(a?.roles)?a.roles.slice(0,20):[],gsd:Number.isFinite(Number(a?.gsd))?Number(a.gsd):null,size:Number.isFinite(Number(a?.["file:size"]))?Number(a["file:size"]):null,checksum:a?.["file:checksum"]||null,href:a?.href||null,https_href:alt,auth_refs:Array.isArray(a?.["auth:refs"])?a["auth:refs"].slice(0,10):[],storage_refs:Array.isArray(a?.["storage:refs"])?a["storage:refs"].slice(0,10):[],bands:Array.isArray(a?.bands)?a.bands.slice(0,20):[]}}
function assetViews(x,max=120){const entries=Object.entries(x?.assets||{}).slice(0,max);return entries.map(([k,v])=>assetView(k,v))}
function props(p={}){return{datetime:p.datetime||null,start_datetime:p.start_datetime||null,end_datetime:p.end_datetime||null,platform:p.platform||null,constellation:p.constellation||null,instruments:Array.isArray(p.instruments)?p.instruments.slice(0,20):[],gsd:Number.isFinite(Number(p.gsd))?Number(p.gsd):null,cloud_cover:Number.isFinite(Number(p["eo:cloud_cover"]))?Number(p["eo:cloud_cover"]):null,snow_cover:Number.isFinite(Number(p["eo:snow_cover"]))?Number(p["eo:snow_cover"]):null,product_type:p["product:type"]||null,processing_level:p["processing:level"]||null,processing_datetime:p["processing:datetime"]||null,timeliness:p["product:timeliness"]||null,orbit_state:p["sat:orbit_state"]||null,absolute_orbit:p["sat:absolute_orbit"]??null,relative_orbit:p["sat:relative_orbit"]??null,grid_code:p["grid:code"]||null,published:p.published||null,updated:p.updated||null}}
function handoff(x){const collection=x?.collection||null,id=x?.id||null;return{contract:"copernicus-cdse-stac-handoff-v1",kind:"earth-observation-stac-item",stac_api:BASE,collection,item_id:id,item_url:collection&&id?`${BASE}/collections/${encodeURIComponent(collection)}/items/${encodeURIComponent(id)}`:null,compute_target:"copernicus-openeo",recommended_process:"load_stac",binary_proxy:false,asset_download_deferred:true}}
function itemView(x,{assets=false}={}){const out={id:x?.id||null,collection:x?.collection||null,bbox:Array.isArray(x?.bbox)?x.bbox:null,properties:props(x?.properties||{}),asset_count:Object.keys(x?.assets||{}).length,compute_handoff:handoff(x)};if(assets)out.assets=assetViews(x);return out}
async function collections(args={}){const body=await request("/collections");const limit=clamp(args.limit,1,200,100),items=(Array.isArray(body?.collections)?body.collections:[]).slice(0,limit).map(collectionView);return{provider:"copernicus_cdse_stac",operation:"collections",adapter_version:ADAPTER_VERSION,endpoint:BASE,public_catalog:true,items,count:items.length,binary_proxy:false}}
async function collectionGet(args={}){const id=safeId(args.collection||args.id,"collection",120),body=await request(`/collections/${encodeURIComponent(id)}`);return{provider:"copernicus_cdse_stac",operation:"collection_get",adapter_version:ADAPTER_VERSION,endpoint:BASE,item:collectionView(body),binary_proxy:false}}
async function search(args={}){const collections=collectionList(args.collections||args.collection),body={collections,limit:clamp(args.limit,1,50,10),fields:{exclude:["geometry","links"]}};if(args.bbox!==undefined)body.bbox=bbox(args.bbox);const dt=datetime(args.datetime);if(dt)body.datetime=dt;if(args.cloud_cover_lte!==undefined){const cc=Number(args.cloud_cover_lte);if(!Number.isFinite(cc)||cc<0||cc>100)err("INVALID_CLOUD_COVER_LTE");body.query={"eo:cloud_cover":{lte:cc}}}const ids=Array.isArray(args.ids)?args.ids.slice(0,20).map(x=>safeId(x,"item",240)):[];if(ids.length)body.ids=ids;const data=await request("/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),items=(Array.isArray(data?.features)?data.features:[]).slice(0,body.limit).map(x=>itemView(x,{assets:false}));return{provider:"copernicus_cdse_stac",operation:"search",adapter_version:ADAPTER_VERSION,endpoint:BASE,query:{collections,bbox:body.bbox||null,datetime:dt,cloud_cover_lte:args.cloud_cover_lte??null,limit:body.limit},number_matched:data?.numberMatched??null,number_returned:data?.numberReturned??items.length,items,binary_proxy:false,compute_handoff_ready:true}}
async function itemGet(args={}){const collection=safeId(args.collection,"collection",120),id=safeId(args.item_id||args.id,"item",240),body=await request(`/collections/${encodeURIComponent(collection)}/items/${encodeURIComponent(id)}`);return{provider:"copernicus_cdse_stac",operation:"item_get",adapter_version:ADAPTER_VERSION,endpoint:BASE,item:itemView(body,{assets:true}),binary_proxy:false}}
async function assetRefs(args={}){const collection=safeId(args.collection,"collection",120),id=safeId(args.item_id||args.id,"item",240),body=await request(`/collections/${encodeURIComponent(collection)}/items/${encodeURIComponent(id)}`),assets=assetViews(body,200);return{provider:"copernicus_cdse_stac",operation:"asset_refs",adapter_version:ADAPTER_VERSION,endpoint:BASE,collection,item_id:id,assets,asset_count:assets.length,compute_handoff:handoff(body),binary_proxy:false,note:"Asset bytes are not proxied through Intelligence Center; authenticated HTTPS/S3 download or openEO processing is deferred to the appropriate runtime."}}
function sourceInfo(){return{provider:"copernicus_cdse_stac",adapter_version:ADAPTER_VERSION,endpoint:BASE,integration:"official-CDSE-STAC-v1",public_catalog:true,operations:OPERATIONS.copernicus_cdse_stac,binary_proxy:false,scope:"collections-spatiotemporal-item-search-single-item-and-asset-references",compute_handoff:"copernicus-openeo-load_stac"}}
export const OPERATIONS={copernicus_cdse_stac:["source_info","collections","collection_get","search","item_get","asset_refs"]};
export async function runAdapter(provider,operation,args={}){if(provider!=="copernicus_cdse_stac"||!OPERATIONS.copernicus_cdse_stac.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(operation==="source_info")return sourceInfo();if(operation==="collections")return collections(args);if(operation==="collection_get")return collectionGet(args);if(operation==="search")return search(args);if(operation==="item_get")return itemGet(args);return assetRefs(args)}
