const TIMEOUT_MS=15000,MAX_RESPONSE_BYTES=1200000;
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function text(v,n=300){return String(v??"").trim().slice(0,n)}
function int(v,min,max,d){const n=Number(v??d);if(!Number.isInteger(n)||n<min||n>max)err("INVALID_INTEGER",400,{min,max});return n}
function safeId(v,re,name){const s=String(v??"").trim();if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_RESPONSE_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function requestJson(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body;try{body=raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{http_status:r.status})}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status});return body}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
async function requestText(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await readBounded(r);if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status});return raw}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
async function ons(operation,args){const base="https://api.beta.ons.gov.uk/v1";if(operation==="list_datasets"){const u=new URL(`${base}/datasets`);u.searchParams.set("limit",String(int(args?.limit,1,50,20)));u.searchParams.set("offset",String(int(args?.offset,0,5000,0)));if(args?.type)u.searchParams.set("type",text(args.type,40));if(args?.id)u.searchParams.set("id",safeId(args.id,/^[A-Za-z0-9._-]{1,120}$/,"id"));return{provider:"ons_uk",operation,result:await requestJson(u)}}if(operation==="dataset_get"){const id=safeId(args?.id,/^[A-Za-z0-9._-]{1,120}$/,"id");return{provider:"ons_uk",operation,result:await requestJson(`${base}/datasets/${encodeURIComponent(id)}`)}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}
async function statcan(operation,args){const base="https://www150.statcan.gc.ca/t1/wds/rest";if(operation==="changed_series")return{provider:"statcan",operation,result:await requestJson(`${base}/getChangedSeriesList`)};if(operation==="vector_latest"){const vectorId=int(args?.vector_id,1,9999999999,1),latestN=int(args?.latest_n,1,50,3);return{provider:"statcan",operation,result:await requestJson(`${base}/getDataFromVectorsAndLatestNPeriods`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify([{vectorId,latestN}])})}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}
async function ecb(operation,args){if(operation!=="data")err("ADAPTER_OPERATION_NOT_APPROVED",403);const flow=safeId(args?.flow,/^[A-Za-z0-9_,.-]{1,120}$/,"flow"),key=safeId(args?.key??"",/^[A-Za-z0-9+*.,_-]{0,300}$/,"key");const u=new URL(`https://data-api.ecb.europa.eu/service/data/${encodeURIComponent(flow)}/${key}`);if(args?.start_period)u.searchParams.set("startPeriod",safeId(args.start_period,/^[0-9A-Za-z-]{4,20}$/,"start_period"));if(args?.end_period)u.searchParams.set("endPeriod",safeId(args.end_period,/^[0-9A-Za-z-]{4,20}$/,"end_period"));u.searchParams.set("format","jsondata");u.searchParams.set("lastNObservations",String(int(args?.last_n,1,200,20)));return{provider:"ecb_data",operation,result:await requestJson(u)}}
async function sec(operation,args){if(operation!=="companyfacts")err("ADAPTER_OPERATION_NOT_APPROVED",403);const cik=String(args?.cik??"").replace(/\D/g,"").padStart(10,"0");if(!/^\d{10}$/.test(cik))err("INVALID_CIK");const ua=text(args?.user_agent||"three-center-intelligence/1.0 contact@example.invalid",200);return{provider:"sec_edgar",operation,cik,result:await requestJson(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`,{headers:{"user-agent":ua}})}}
async function clinical(operation,args){if(operation!=="search_studies")err("ADAPTER_OPERATION_NOT_APPROVED",403);const q=text(args?.query,300);if(!q)err("ARG_REQUIRED:query");const u=new URL("https://clinicaltrials.gov/api/v2/studies");u.searchParams.set("query.term",q);u.searchParams.set("pageSize",String(int(args?.page_size,1,100,20)));u.searchParams.set("format","json");return{provider:"clinicaltrials",operation,result:await requestJson(u)}}
export const OPERATIONS={ons_uk:["list_datasets","dataset_get"],statcan:["changed_series","vector_latest"],ecb_data:["data"],sec_edgar:["companyfacts"],clinicaltrials:["search_studies"]};
export async function runAdapter(provider,operation,args={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="ons_uk")return ons(operation,args);if(provider==="statcan")return statcan(operation,args);if(provider==="ecb_data")return ecb(operation,args);if(provider==="sec_edgar")return sec(operation,args);if(provider==="clinicaltrials")return clinical(operation,args);err("ADAPTER_NOT_FOUND",404)}
export const __test={int,safeId,text};
