const TIMEOUT_MS=16000,MAX_BYTES=1400000;
const text=(v,n=1600)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function required(v,name,n=800){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function secret(env,name){const s=text(env?.[name],1000);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function optionalSecret(env,name){return text(env?.[name],1000)||null}
async function boundedText(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502,{limit:MAX_BYTES});const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502,{limit:MAX_BYTES})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function requestJson(url,init={},opts={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,headers:{accept:"application/json","user-agent":"three-center-intelligence-medical/1.0",...(init.headers||{})},signal:c.signal}),raw=await boundedText(r);if(opts.allow404&&r.status===404)return null;if(!r.ok){const auth=r.status===401||r.status===403;err(auth?"UPSTREAM_AUTH_FAILED":r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",auth?503:r.status===429?429:502,{http_status:r.status,preview:text(raw,500)})}try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{preview:text(raw,400)})}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function lang(v){const s=text(v||"en",12);if(!/^[a-z]{2}(?:-[A-Za-z]{2})?$/.test(s))err("INVALID_LANGUAGE");return s}
function cleanId(v,name,n=100){const s=required(v,name,n);if(!/^[A-Za-z0-9_.:+-]+$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}

async function whoToken(env){const id=secret(env,"WHO_ICD_CLIENT_ID"),sec=secret(env,"WHO_ICD_CLIENT_SECRET"),body=new URLSearchParams({grant_type:"client_credentials",scope:"icdapi_access"}).toString();const out=await requestJson("https://icdaccessmanagement.who.int/connect/token",{method:"POST",headers:{authorization:`Basic ${btoa(`${id}:${sec}`)}`,"content-type":"application/x-www-form-urlencoded"},body});const token=text(out?.access_token,5000);if(!token)err("UPSTREAM_AUTH_FAILED",503,{provider:"who_icd11"});return token}
async function whoIcd(operation,args,env){if(operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403);const q=required(args?.query,"query",500),release=text(args?.release||"2026-01",20),language=lang(args?.language),limit=clamp(args?.limit,1,25,10);if(!/^20\d{2}-\d{2}$/.test(release))err("INVALID_RELEASE");const token=await whoToken(env),u=new URL(`https://id.who.int/icd/release/11/${release}/mms/search`);u.searchParams.set("q",q);u.searchParams.set("useFlexisearch",args?.flexible===false?"false":"true");u.searchParams.set("flatResults","true");u.searchParams.set("highlightingEnabled","false");const out=await requestJson(u,{headers:{authorization:`Bearer ${token}`,"API-Version":"v2","Accept-Language":language}}),items=Array.isArray(out?.destinationEntities)?out.destinationEntities.slice(0,limit):[];return{provider:"who_icd11",operation,query:q,release,language,items,source_mode:"WHO ICD-11 MMS official API v2; OAuth2; bounded read-only"}}

async function umls(operation,args,env){const key=secret(env,"UMLS_API_KEY");if(operation==="search"){const q=required(args?.query,"query",500),limit=clamp(args?.limit,1,25,10),u=new URL("https://uts-ws.nlm.nih.gov/rest/search/current");u.searchParams.set("string",q);u.searchParams.set("pageSize",String(limit));u.searchParams.set("apiKey",key);if(args?.semantic_group)u.searchParams.set("semanticGroups",text(args.semantic_group,80));if(args?.semantic_types)u.searchParams.set("semanticTypes",text(args.semantic_types,160));if(args?.partial===true)u.searchParams.set("partialSearch","true");const out=await requestJson(u),items=Array.isArray(out?.result?.results)?out.result.results.slice(0,limit):[];return{provider:"umls_uts",operation,query:q,items,source_mode:"NLM UMLS REST current release; bounded read-only"}}
  if(operation==="definitions"){const cui=cleanId(args?.cui,"cui",20);if(!/^C\d{7}$/.test(cui))err("INVALID_CUI");const u=new URL(`https://uts-ws.nlm.nih.gov/rest/content/current/CUI/${cui}/definitions`);u.searchParams.set("apiKey",key);if(args?.source)u.searchParams.set("sabs",text(args.source,80));const out=await requestJson(u),items=Array.isArray(out?.result)?out.result.slice(0,25):[];return{provider:"umls_uts",operation,cui,items,source_mode:"NLM UMLS concept definitions; bounded read-only"}}
  err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const MEDLINE_OIDS={icd10cm:"2.16.840.1.113883.6.90",snomed:"2.16.840.1.113883.6.96",rxcui:"2.16.840.1.113883.6.88",ndc:"2.16.840.1.113883.6.69",loinc:"2.16.840.1.113883.6.1",cpt:"2.16.840.1.113883.6.12"};
function atomValue(v){if(v==null)return null;if(typeof v==="string")return text(v,4000);return text(v?._value??v?.value??v?.content??"",4000)||null}
function atomLink(v){if(Array.isArray(v)){const x=v.find(a=>a?.href)||v[0];return text(x?.href,2000)||null}return text(v?.href,2000)||null}
async function medline(operation,args){if(operation!=="lookup")err("ADAPTER_OPERATION_NOT_APPROVED",403);const system=text(args?.code_system,30).toLowerCase(),oid=MEDLINE_OIDS[system];if(!oid)err("INVALID_CODE_SYSTEM",400,{allowed:Object.keys(MEDLINE_OIDS)});const code=required(args?.code,"code",120),language=["en","es"].includes(text(args?.language,5).toLowerCase())?text(args.language,5).toLowerCase():"en",u=new URL("https://connect.medlineplus.gov/service");u.searchParams.set("mainSearchCriteria.v.cs",oid);u.searchParams.set("mainSearchCriteria.v.c",code);if(args?.display)u.searchParams.set("mainSearchCriteria.v.dn",text(args.display,300));u.searchParams.set("informationRecipient.languageCode.c",language);u.searchParams.set("knowledgeResponseType","application/json");const out=await requestJson(u),entries=Array.isArray(out?.feed?.entry)?out.feed.entry:[];return{provider:"medlineplus_connect",operation,code_system:system,code,language,items:entries.slice(0,20).map(x=>({title:atomValue(x?.title),url:atomLink(x?.link),summary:atomValue(x?.summary),updated:atomValue(x?.updated),source:atomValue(x?.author?.name)})),matched:entries.length>0,source_mode:"NLM MedlinePlus Connect official code-linked web service; read-only"}}

const FDA_FIELDS={generic_name:"openfda.generic_name",brand_name:"openfda.brand_name",rxcui:"openfda.rxcui",product_ndc:"openfda.product_ndc",substance_name:"openfda.substance_name",application_number:"openfda.application_number"};
function fdaTerm(v){return required(v,"drug",240).replace(/["\\]/g," ").replace(/\s+/g," ").trim()}
function firstArray(v,n=6000){if(Array.isArray(v))return v.slice(0,4).map(x=>text(x,n));if(v==null)return[];return[text(v,n)]}
function normalizeLabel(x){const o=x?.openfda||{};return{id:x?.id??null,effective_time:x?.effective_time??null,generic_name:firstArray(o?.generic_name,300),brand_name:firstArray(o?.brand_name,300),manufacturer_name:firstArray(o?.manufacturer_name,300),rxcui:firstArray(o?.rxcui,100),product_ndc:firstArray(o?.product_ndc,100),route:firstArray(o?.route,100),dosage_form:firstArray(o?.dosage_form,120),indications_and_usage:firstArray(x?.indications_and_usage),contraindications:firstArray(x?.contraindications),boxed_warning:firstArray(x?.boxed_warning),warnings:firstArray(x?.warnings),warnings_and_cautions:firstArray(x?.warnings_and_cautions),adverse_reactions:firstArray(x?.adverse_reactions),drug_interactions:firstArray(x?.drug_interactions),dosage_and_administration:firstArray(x?.dosage_and_administration),pregnancy:firstArray(x?.pregnancy),pediatric_use:firstArray(x?.pediatric_use),geriatric_use:firstArray(x?.geriatric_use)}}
async function openFda(operation,args,env){if(operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403);const drug=fdaTerm(args?.drug),field=text(args?.field||"generic_name",40),apiField=FDA_FIELDS[field];if(!apiField)err("INVALID_FIELD",400,{allowed:Object.keys(FDA_FIELDS)});const limit=clamp(args?.limit,1,5,3),u=new URL("https://api.fda.gov/drug/label.json");u.searchParams.set("search",`${apiField}:\"${drug}\"`);u.searchParams.set("limit",String(limit));const key=optionalSecret(env,"OPENFDA_API_KEY");if(key)u.searchParams.set("api_key",key);const out=await requestJson(u,{}, {allow404:true}),items=Array.isArray(out?.results)?out.results.slice(0,limit).map(normalizeLabel):[];return{provider:"openfda_drug_label",operation,field,drug,items,source_mode:"FDA openFDA drug labeling API; optional free key; bounded read-only"}}

async function rxclass(operation,args){if(operation==="classes_by_drug"){const drug=required(args?.drug_name,"drug_name",240),u=new URL("https://rxnav.nlm.nih.gov/REST/rxclass/class/byDrugName.json");u.searchParams.set("drugName",drug);if(args?.rela_source)u.searchParams.set("relaSource",text(args.rela_source,50));const out=await requestJson(u),items=Array.isArray(out?.rxclassDrugInfoList?.rxclassDrugInfo)?out.rxclassDrugInfoList.rxclassDrugInfo.slice(0,50):[];return{provider:"rxclass",operation,drug_name:drug,items,source_mode:"NLM RxClass official API; no license required; read-only"}}
  if(operation==="class_members"){const classId=cleanId(args?.class_id,"class_id",80),u=new URL("https://rxnav.nlm.nih.gov/REST/rxclass/classMembers.json");u.searchParams.set("classId",classId);if(args?.rela_source)u.searchParams.set("relaSource",text(args.rela_source,50));if(args?.rela)u.searchParams.set("rela",text(args.rela,60));const out=await requestJson(u),items=Array.isArray(out?.drugMemberGroup?.drugMember)?out.drugMemberGroup.drugMember.slice(0,100):[];return{provider:"rxclass",operation,class_id:classId,items,source_mode:"NLM RxClass class members; bounded read-only"}}
  err("ADAPTER_OPERATION_NOT_APPROVED",403)}

async function pubtator(operation,args){if(operation==="search"){const q=required(args?.query,"query",600),page=clamp(args?.page,1,20,1),limit=clamp(args?.limit,1,20,10),u=new URL("https://www.ncbi.nlm.nih.gov/research/pubtator3-api/search/");u.searchParams.set("text",q);u.searchParams.set("page",String(page));const out=await requestJson(u),raw=Array.isArray(out)?out:Array.isArray(out?.results)?out.results:Array.isArray(out?.items)?out.items:[];return{provider:"pubtator3",operation,query:q,page,items:raw.slice(0,limit),source_mode:"NCBI PubTator3 semantic literature search; <=3 requests/sec policy; no retry"}}
  if(operation==="entity_autocomplete"){const q=required(args?.query,"query",300),limit=clamp(args?.limit,1,10,8),concept=text(args?.concept,30).toLowerCase(),u=new URL("https://www.ncbi.nlm.nih.gov/research/pubtator3-api/entity/autocomplete/");u.searchParams.set("query",q);u.searchParams.set("limit",String(limit));if(["gene","disease","chemical","variant"].includes(concept))u.searchParams.set("concept",concept);const out=await requestJson(u),items=Array.isArray(out)?out.slice(0,limit):Array.isArray(out?.results)?out.results.slice(0,limit):[];return{provider:"pubtator3",operation,query:q,concept:concept||null,items,source_mode:"NCBI PubTator3 entity normalization; bounded read-only"}}
  err("ADAPTER_OPERATION_NOT_APPROVED",403)}

async function monarch(operation,args){const base="https://api-v3.monarchinitiative.org/v3/api";if(operation==="search"){const q=required(args?.query,"query",400),limit=clamp(args?.limit,1,25,10),u=new URL(`${base}/search`);u.searchParams.set("q",q);u.searchParams.set("limit",String(limit));const out=await requestJson(u),items=Array.isArray(out?.items)?out.items.slice(0,limit):Array.isArray(out?.results)?out.results.slice(0,limit):[];return{provider:"monarch_api",operation,query:q,items,source_mode:"Monarch Initiative v3 knowledge-graph search; public read-only"}}
  if(operation==="entity"){const id=cleanId(args?.id,"id",100),out=await requestJson(`${base}/entity/${encodeURIComponent(id)}`);return{provider:"monarch_api",operation,id,entity:out,source_mode:"Monarch Initiative v3 entity lookup; public read-only"}}
  if(operation==="case_phenotype"){const diseaseId=cleanId(args?.disease_id,"disease_id",100),out=await requestJson(`${base}/case-phenotype-matrix/${encodeURIComponent(diseaseId)}`);return{provider:"monarch_api",operation,disease_id:diseaseId,data:out,source_mode:"Monarch Initiative v3 case-phenotype matrix; public read-only"}}
  err("ADAPTER_OPERATION_NOT_APPROVED",403)}

async function ebiOls(operation,args){if(operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403);const q=required(args?.query,"query",400),limit=clamp(args?.limit,1,25,10),u=new URL("https://www.ebi.ac.uk/ols4/api/search");u.searchParams.set("q",q);u.searchParams.set("rows",String(limit));if(args?.ontology)u.searchParams.set("ontology",text(args.ontology,80).toLowerCase());if(args?.exact===true)u.searchParams.set("exact","true");const out=await requestJson(u),docs=Array.isArray(out?.response?.docs)?out.response.docs.slice(0,limit):[];return{provider:"ebi_ols",operation,query:q,ontology:args?.ontology?text(args.ontology,80).toLowerCase():null,items:docs,source_mode:"EMBL-EBI OLS4 official ontology search API; public read-only"}}

export const OPERATIONS={
  who_icd11:["search"],
  umls_uts:["search","definitions"],
  medlineplus_connect:["lookup"],
  openfda_drug_label:["search"],
  rxclass:["classes_by_drug","class_members"],
  pubtator3:["search","entity_autocomplete"],
  monarch_api:["search","entity","case_phenotype"],
  ebi_ols:["search"]
};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="who_icd11")return whoIcd(operation,args,env);if(provider==="umls_uts")return umls(operation,args,env);if(provider==="medlineplus_connect")return medline(operation,args);if(provider==="openfda_drug_label")return openFda(operation,args,env);if(provider==="rxclass")return rxclass(operation,args);if(provider==="pubtator3")return pubtator(operation,args);if(provider==="monarch_api")return monarch(operation,args);if(provider==="ebi_ols")return ebiOls(operation,args);err("ADAPTER_NOT_IMPLEMENTED",501)}