const MAX_BYTES=1500000,TIMEOUT_MS=20000;
const UA="IntelligenceCenter/2026.08 (https://github.com/three-center-static-relay/qingbaozhongxin; read-only)";
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
function cdsKey(env){const v=String(env?.COPERNICUS_CDS_API_KEY||env?.CDS_API_KEY||"").trim();if(!v)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:"COPERNICUS_CDS_API_KEY|CDS_API_KEY"}});return v}
function safeId(v,label){const s=text(v,200);if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/.test(s))throw Object.assign(new Error(`INVALID_${label.toUpperCase()}_ID`),{status:400});return s}
function cleanJson(v,depth=0,state={n:0}){if(++state.n>2000)throw Object.assign(new Error("REQUEST_TOO_COMPLEX"),{status:400});if(depth>8)throw Object.assign(new Error("REQUEST_TOO_DEEP"),{status:400});if(v===null||typeof v==="boolean")return v;if(typeof v==="number"){if(!Number.isFinite(v))throw Object.assign(new Error("INVALID_NUMBER"),{status:400});return v}if(typeof v==="string")return v.slice(0,4000);if(Array.isArray(v)){if(v.length>500)throw Object.assign(new Error("REQUEST_ARRAY_TOO_LARGE"),{status:400});return v.map(x=>cleanJson(x,depth+1,state))}if(v&&typeof v==="object"){const entries=Object.entries(v);if(entries.length>150)throw Object.assign(new Error("REQUEST_OBJECT_TOO_LARGE"),{status:400});const out={};for(const[k,x]of entries){if(!/^[A-Za-z0-9_.:-]{1,100}$/.test(k))throw Object.assign(new Error("INVALID_REQUEST_KEY"),{status:400});out[k]=cleanJson(x,depth+1,state)}return out}throw Object.assign(new Error("INVALID_REQUEST_VALUE"),{status:400})}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const all=new Uint8Array(total);let off=0;for(const c of chunks){all.set(c,off);off+=c.byteLength}return new TextDecoder().decode(all)}
async function bounded(url,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await readBounded(r);let body=null;if(raw){try{body=JSON.parse(raw)}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502,details:{http_status:r.status}})}}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:r.status===401||r.status===403?503:502,details:{http_status:r.status,error:body?.detail||body?.title||body?.message||body?.error||null}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
const BASE="https://cds.climate.copernicus.eu/api";
function headers(env){return{"PRIVATE-TOKEN":cdsKey(env),accept:"application/json","user-agent":UA}}
async function copernicus(operation,args,env){const h=headers(env);
  if(operation==="auth_check"){return{provider:"copernicus_cds",operation,data:await bounded(`${BASE}/profiles/v1/account/verification/pat`,{method:"POST",headers:h})}}
  if(operation==="catalog_search"){const u=new URL(`${BASE}/catalogue/v1/datasets`),q=text(required(args,"query"),300),limit=Math.max(1,Math.min(50,Number(args?.limit)||10)),sortby=["relevance","id","title","update"].includes(String(args?.sortby||"relevance"))?String(args?.sortby||"relevance"):"relevance";u.searchParams.set("query",q);u.searchParams.set("limit",String(limit));u.searchParams.set("sortby",sortby);u.searchParams.set("search_stats","false");return{provider:"copernicus_cds",operation,data:await bounded(u,{headers:h})}}
  if(operation==="dataset_get"){const id=safeId(required(args,"dataset"),"dataset");return{provider:"copernicus_cds",operation,data:await bounded(`${BASE}/catalogue/v1/collections/${encodeURIComponent(id)}`,{headers:h})}}
  if(operation==="retrieve_submit"){const id=safeId(required(args,"dataset"),"dataset"),request=cleanJson(required(args,"request"));if(!request||Array.isArray(request)||typeof request!=="object")throw Object.assign(new Error("INVALID_REQUEST_OBJECT"),{status:400});const data=await bounded(`${BASE}/retrieve/v1/processes/${encodeURIComponent(id)}/execution`,{method:"POST",headers:{...h,"content-type":"application/json"},body:JSON.stringify({inputs:request})});return{provider:"copernicus_cds",operation,data}}
  if(operation==="job_status"){const id=safeId(required(args,"job_id"),"job");const u=new URL(`${BASE}/retrieve/v1/jobs/${encodeURIComponent(id)}`);u.searchParams.set("log","false");u.searchParams.set("request","false");return{provider:"copernicus_cds",operation,data:await bounded(u,{headers:h})}}
  if(operation==="job_results"){const id=safeId(required(args,"job_id"),"job");return{provider:"copernicus_cds",operation,data:await bounded(`${BASE}/retrieve/v1/jobs/${encodeURIComponent(id)}/results`,{headers:h})}}
  throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403})}
export const OPERATIONS={copernicus_cds:["auth_check","catalog_search","dataset_get","retrieve_submit","job_status","job_results"]};
export async function runAdapter(provider,operation,args,env){if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});return copernicus(operation,args||{},env)}
