import {runAdapter as runWebSearch} from "./adapters-extra39.js";

const MAX_BYTES=1500000,TIMEOUT_MS=18000,PROFILE="top-tier-free";
const text=(v,n=1600)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function required(v,name,n=800){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function arr(v,n=20){return(Array.isArray(v)?v:[]).map(x=>text(x,300)).filter(Boolean).slice(0,n)}
async function boundedText(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function getJson(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:{accept:"application/vnd.api+json,application/json","user-agent":"three-center-intelligence-global-institution/1.1"},signal:c.signal}),raw=await boundedText(r);if(!r.ok)err(r.status===429?"UPSTREAM_RATE_LIMITED":"UPSTREAM_HTTP_ERROR",r.status===429?429:502,{http_status:r.status,preview:text(raw,400)});try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{preview:text(raw,300)})}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

const DEFAULT_TYPES=[
  "global or national flagship universities national academies and top-tier research institutes",
  "national governments ministries central banks national statistics offices supreme regulators and national authorities",
  "global or national financial regulators central banks and systemically important financial institutions",
  "globally leading or nationally strategic companies and corporate groups",
  "globally or nationally leading think tanks policy institutes and research organizations",
  "intergovernmental organizations major global NGOs foundations and apex industry associations",
  "national libraries national archives national museums and globally significant repositories",
  "global or national authoritative databases registries knowledge graphs datasets API MCP SPARQL OAI-PMH CKAN DCAT SRU SDMX IIIF services"
];
function geo(args){return[arr(args?.regions,8).join(" "),text(args?.country,100)].filter(Boolean).join(" ").trim()||"global and country-level only"}
function typeText(args){const xs=arr(args?.institution_types,12);return(xs.length?xs:DEFAULT_TYPES).join("; ")}
function buildQueries(args){const g=geo(args),types=typeText(args),industry=text(args?.industry,200),subject=text(args?.query,600),extra=[industry,subject].filter(Boolean).join(" ");return[
  `official primary sources only; top-tier global, national apex, or apex-industry institutions for ${types}; geography: ${g}; ${extra}; free public access or free registration key only; no paid subscription, no time-limited trial, no paywall; exclude provincial state municipal county district local small organizations`,
  `authoritative national flagship directories and apex registries for ${types}; geography: ${g}; ${extra}; prioritize national ministries, central banks, national statistics offices, national regulators, national libraries and archives, national academies, flagship research institutions, globally leading companies and apex industry bodies; free access only; exclude ordinary companies, local associations, local universities, municipal or subnational institutions`,
  `machine-readable official free interfaces API MCP OpenAPI SPARQL OAI-PMH CKAN DCAT SRU SDMX IIIF bulk data for top-tier global, national apex, or apex-industry sources among ${types}; geography: ${g}; ${extra}; stable free access only; exclude paid-only, trial-only, local, small and subnational sources`
]}
function hostOf(url){try{return new URL(url).hostname.toLowerCase()}catch{return""}}
function authorityHint(url,title=""){const h=hostOf(url),s=`${h} ${title}`.toLowerCase();if(/\.int$|\.un\.org$|worldbank\.org$|imf\.org$|oecd\.org$|bis\.org$|wto\.org$/.test(h))return"global-authority-likely";if(/\.gov\.|\.gov$|\.gouv\.|\.go\.|\.gc\.|\.europa\.eu$/.test(h))return"national-or-supranational-official-likely";if(/central bank|national bank|ministry|national statistics|national library|national archives|supreme court|securities commission|financial authority|national academy/.test(s))return"national-apex-likely";if(/global|world|international|standards organization|standards body|apex association/.test(s))return"global-or-industry-apex-likely";if(/university|universit|academy|research institute/.test(s))return"flagship-status-needs-verification";if(/bank|corporation|group|company/.test(s))return"leading-status-needs-verification";return"candidate-unverified"}
function obviousNonTopTier(title=""){const s=String(title).toLowerCase();return/\b(city of|municipal|municipality|county|district council|town council|township|village|local chamber|regional chamber|community college|provincial department|province of|state department of)\b/.test(s)}
function normalizeCandidate(x,engine,round){const url=text(x?.url,2000),title=text(x?.title,500);return{engine,round,title,url,host:hostOf(url),published_date:x?.published_date||null,score:x?.score??null,authority_hint:authorityHint(url,title),candidate_only:true,scope_profile:PROFILE,free_access_status:"must-be-verified-before-promotion",snippet:text(x?.content||arr(x?.highlights,4).join(" "),2200)}}
function dedupe(items){const seen=new Set(),out=[];for(const x of items){if(obviousNonTopTier(x.title))continue;const key=(x.url||`${x.host}|${x.title}`).toLowerCase();if(!key||seen.has(key))continue;seen.add(key);out.push(x)}return out}
async function globalDiscovery(args,env){
  const rounds=clamp(args?.rounds,1,3,3),limit=clamp(args?.limit_per_engine,3,20,10),queries=buildQueries(args).slice(0,rounds),include=arr(args?.include_domains,20),exclude=arr(args?.exclude_domains,20),all=[],round_meta=[];
  for(let i=0;i<queries.length;i++){
    const q=queries[i],base={query:q,limit,include_domains:include,exclude_domains:exclude},meta={round:i+1,query:q,exa_ok:false,tavily_ok:false};
    try{const r=await runWebSearch("exa","search",{...base,type:i===2?"deep-lite":"auto"},env);meta.exa_ok=true;meta.exa_request_id=r?.request_id||null;meta.exa_cost_dollars=r?.cost_dollars??null;for(const x of r?.items||[])all.push(normalizeCandidate(x,"exa",i+1))}catch(e){meta.exa_error=String(e?.message||e)}
    try{const r=await runWebSearch("tavily","search",{...base,search_depth:i===2?"advanced":"basic",topic:"general"},env);meta.tavily_ok=true;meta.tavily_request_id=r?.request_id||null;meta.tavily_usage=r?.usage||null;for(const x of r?.items||[])all.push(normalizeCandidate(x,"tavily",i+1))}catch(e){meta.tavily_error=String(e?.message||e)}
    round_meta.push(meta);
    if(args?.require_both!==false&&(!meta.exa_ok||!meta.tavily_ok))err("DUAL_SEARCH_INCOMPLETE",502,{round:i+1,exa_ok:meta.exa_ok,tavily_ok:meta.tavily_ok,exa_error:meta.exa_error||null,tavily_error:meta.tavily_error||null});
  }
  const items=dedupe(all);return{provider:"global_institution_discovery",operation:"search",scope_profile:PROFILE,selection_policy:{top_tier_only:true,free_only:true,levels:["global","national-apex","apex-industry","global-leading-or-national-flagship"],excluded:["subnational","municipal","county","district","ordinary-small-institution","ordinary-company","ordinary-association","paid-only","trial-only","paywalled"]},rounds:round_meta,items,total_candidates:items.length,discovery_only:true,promotion_rule:"promote only after official verification proves global/national/apex-industry or leading/flagship status AND stable no-fee public access or no-fee registration-key access; reject paid-only, trial-only, paywalled, subnational, local, small or ordinary sources"};
}
function gleifItem(x){const a=x?.attributes||{},entity=a?.entity||{},reg=a?.registration||{},addr=entity?.legalAddress||{};return{lei:x?.id||a?.lei||null,legal_name:entity?.legalName?.name||entity?.legalName||null,other_names:(entity?.otherNames||[]).slice(0,8),country:addr?.country||null,city:addr?.city||null,jurisdiction:entity?.jurisdiction||null,category:entity?.category||null,registration_status:reg?.status||null,initial_registration_date:reg?.initialRegistrationDate||null,last_update_date:reg?.lastUpdateDate||null,links:x?.links||null}}
async function gleifSearch(args){const q=required(args?.query,"query",255),limit=clamp(args?.limit,1,50,15),page=clamp(args?.page,1,1000,1),u=new URL("https://api.gleif.org/api/v1/lei-records");u.searchParams.set("filter[fulltext]",q);if(args?.country&&/^[A-Za-z]{2}$/.test(String(args.country)))u.searchParams.set("filter[entity.legalAddress.country]",String(args.country).toUpperCase());u.searchParams.set("page[size]",String(limit));u.searchParams.set("page[number]",String(page));const body=await getJson(u);return{provider:"gleif",operation:"search",page,total:Number(body?.meta?.pagination?.total??0)||null,items:(Array.isArray(body?.data)?body.data:[]).map(gleifItem),source_mode:"GLEIF official API v1; public; bounded fulltext legal-entity search"}}

export const OPERATIONS={global_institution_discovery:["search"],gleif:["search"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation});if(provider==="global_institution_discovery")return globalDiscovery(args,env);if(provider==="gleif")return gleifSearch(args);err("ADAPTER_NOT_IMPLEMENTED",501)}
