import {runAdapter as runExtra6} from "./adapters-extra6.js";
import {runAdapter as runExtra18} from "./adapters-extra18.js";

const TIMEOUT_MS=18000,MAX_BYTES=1500000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function countryCode(v){const s=text(v||"",2).toUpperCase();if(s&&!/^[A-Z]{2}$/.test(s))err("INVALID_COUNTRY_CODE",400);return s}
function stripMarkup(v,n=2000){return text(v,n).replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g," ").trim()}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function jsonFetch(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{signal:c.signal,headers:{accept:"application/json","user-agent":"ThreeCenterIntelligence/1.0 (+bounded public Google source reader)"}}),raw=await readBounded(r);if(!r.ok)err("GOOGLE_PATENTS_PUBLIC_SEARCH_UNAVAILABLE",502,{http_status:r.status});try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502)}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function rowValue(data,index=0){return data?.rows?.[0]?.f?.[index]?.v??null}
function ymdPartition(v){const s=String(v||"");if(!/^\d{8}$/.test(s))err("GOOGLE_TRENDS_LATEST_PARTITION_NOT_FOUND",502,{partition:s||null});return`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`}
async function latestTrendDate(operation,args,env){const table=operation==="rising_terms"?"international_top_rising_terms":"international_top_terms",q=`SELECT MAX(partition_id) AS latest_partition FROM \`bigquery-public-data.google_trends.INFORMATION_SCHEMA.PARTITIONS\` WHERE table_name='${table}' AND partition_id IS NOT NULL AND partition_id!='__NULL__'`,meta=await runExtra6("bigquery","query",{project_id:args?.project_id,query:q,limit:1,maximum_bytes_billed:20000000,location:args?.location||"US"},env),partition=rowValue(meta?.data,0);return{date:ymdPartition(partition),metadata_bytes:meta?.data?.total_bytes_processed||null}}
async function trends(operation,args,env){if(args?.refresh_date){const out=await runExtra6("google_trends_public",operation,args,env);return{...out,refresh_date_source:"explicit"}}
 const latest=await latestTrendDate(operation,args,env),budget=clamp(args?.maximum_bytes_billed,520000000,650000000,600000000),out=await runExtra6("google_trends_public",operation,{...args,refresh_date:latest.date,maximum_bytes_billed:budget,location:args?.location||"US"},env);return{...out,latest_refresh_date:latest.date,refresh_date_source:"latest-partition-metadata",partition_metadata_bytes_processed:latest.metadata_bytes,maximum_bytes_billed:budget}}
function patentItems(body){const clusters=Array.isArray(body?.results?.cluster)?body.results.cluster:[],rows=[];for(const c of clusters){for(const r of Array.isArray(c?.result)?c.result:[]){const p=r?.patent;if(!p)continue;rows.push({publication_number:text(p.publication_number,80),title:stripMarkup(p.title,1000),snippet:stripMarkup(p.snippet,2500),priority_date:text(p.priority_date,20)||null,filing_date:text(p.filing_date,20)||null,grant_date:text(p.grant_date,20)||null,publication_date:text(p.publication_date,20)||null,inventor:text(p.inventor,500)||null,assignee:text(p.assignee,500)||null,language:text(p.language,20)||null,url:p.publication_number?`https://patents.google.com/patent/${encodeURIComponent(p.publication_number)}/en`:null})}}return rows}
async function patents(args){const query=text(args?.query,300);if(!query)err("ARG_REQUIRED:query",400);const inner=new URLSearchParams({q:query});const cc=countryCode(args?.country_code);if(cc)inner.set("country",cc);const from=clamp(args?.from_year,1900,2100,1900);if(args?.from_year)inner.set("after",`priority:${from}0101`);const u=new URL("https://patents.google.com/xhr/query");u.searchParams.set("url",inner.toString());const body=await jsonFetch(u),limit=clamp(args?.limit,1,50,10),items=patentItems(body).filter(x=>(!cc||String(x.publication_number||"").toUpperCase().startsWith(cc))&&(!args?.from_year||Number(String(x.priority_date||x.filing_date||"").slice(0,4))>=from)).slice(0,limit);return{provider:"google_patents_public",operation:"search",integration:"official-google-patents-public-search",query_mode:"bounded-public-search-no-bigquery-scan",items,total_results:Number(body?.results?.total_num_results)||null,total_pages:Number(body?.results?.total_num_pages)||null,source_url:`https://patents.google.com/?${inner.toString()}`,bigquery_bytes_billed:0,rate_limit_note:"single bounded request; no retries"}}
function pkulawDataState(data){if(data?.isError===true)return"tool-error";const s=data?.structuredContent;if(Array.isArray(s?.result))return s.result.length?"nonempty":"empty";if(Array.isArray(s?.Data))return s.Data.length?"nonempty":"empty";const raw=Array.isArray(data?.content)?data.content.map(x=>x?.text||"").join(" "):"";if(/未找到数据/.test(raw)&&/Total[^0-9]*0/.test(raw))return"empty";if(raw.trim())return"nonempty";return"unknown"}
async function pkulawHealth(env){const lawList=await runExtra18("pkulaw","mcp_call",{service:"mcp-law",tool:"get_law_list",arguments:{title:"刑法"}},env),lawSearch=await runExtra18("pkulaw","mcp_call",{service:"mcp-law-search-service",tool:"search_article",arguments:{text:"劳动合同解除",timeliness:"现行有效",size:1}},env),caseSearch=await runExtra18("pkulaw","mcp_call",{service:"mcp-case-search-service",tool:"search_case",arguments:{text:"劳动合同纠纷",size:1}},env),lawListState=pkulawDataState(lawList.data),lawSearchState=pkulawDataState(lawSearch.data),caseState=pkulawDataState(caseSearch.data),lawDataOk=lawListState==="nonempty"||lawSearchState==="nonempty",caseDataOk=caseState==="nonempty";return{provider:"pkulaw",operation:"health_check",transport_ok:true,auth_ok:true,law_data_ok:lawDataOk,case_data_ok:caseDataOk,status:lawDataOk&&caseDataOk?"healthy":caseDataOk?"degraded-law-data":"degraded",checks:{law_list:lawListState,law_search:lawSearchState,case_search:caseState},note:lawDataOk?null:"PKULaw law MCP services returned empty baseline results; case search remains independently usable."}}
async function pkulaw(operation,args,env){if(operation==="health_check")return pkulawHealth(env);const out=await runExtra18("pkulaw",operation,args,env);if(operation==="mcp_call")return{...out,upstream_data_status:pkulawDataState(out?.data)};return out}
export const OPERATIONS={google_trends_public:["top_terms","rising_terms"],google_patents_public:["search"],pkulaw:["mcp_tools","mcp_call","health_check"]};
export async function runAdapter(provider,operation,args={},env){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="google_trends_public")return trends(operation,args,env);if(provider==="google_patents_public")return patents(args);if(provider==="pkulaw")return pkulaw(operation,args,env);err("ADAPTER_NOT_IMPLEMENTED",501)}
