import {OPERATIONS as CORE_OPERATIONS,runAdapter as runCore} from "./adapters-core.js";
import {OPERATIONS as EXTRA_OPERATIONS,runAdapter as runExtra} from "./adapters-extra.js";
import {OPERATIONS as EXTRA2_OPERATIONS,runAdapter as runExtra2} from "./adapters-extra2.js";
import {OPERATIONS as EXTRA3_OPERATIONS,runAdapter as runExtra3} from "./adapters-extra3.js";
import {OPERATIONS as EXTRA4_OPERATIONS,runAdapter as runExtra4} from "./adapters-extra4.js";
import {OPERATIONS as EXTRA5_OPERATIONS,runAdapter as runExtra5} from "./adapters-extra5.js";
import {OPERATIONS as EXTRA6_OPERATIONS,runAdapter as runExtra6} from "./adapters-extra6.js";
import {OPERATIONS as EXTRA7_OPERATIONS,runAdapter as runExtra7} from "./adapters-extra7.js";
import {OPERATIONS as EXTRA8_OPERATIONS,runAdapter as runExtra8} from "./adapters-extra8.js";
import {OPERATIONS as EXTRA9_OPERATIONS,runAdapter as runExtra9} from "./adapters-extra9.js";
import {OPERATIONS as EXTRA10_OPERATIONS,runAdapter as runExtra10} from "./adapters-extra10.js";
import {OPERATIONS as EXTRA11_OPERATIONS,runAdapter as runExtra11} from "./adapters-extra11.js";
import {OPERATIONS as EXTRA12_OPERATIONS,runAdapter as runExtra12} from "./adapters-extra12.js";
import {OPERATIONS as EXTRA13_OPERATIONS,runAdapter as runExtra13} from "./adapters-extra13.js";
import {OPERATIONS as EXTRA14_OPERATIONS,runAdapter as runExtra14} from "./adapters-extra14.js";
import {OPERATIONS as EXTRA15_OPERATIONS,runAdapter as runExtra15} from "./adapters-extra15.js";
import {OPERATIONS as EXTRA16_OPERATIONS,runAdapter as runExtra16} from "./adapters-extra16.js";
import {OPERATIONS as EXTRA17_OPERATIONS,runAdapter as runExtra17} from "./adapters-extra17.js";
import {OPERATIONS as EXTRA18_OPERATIONS,runAdapter as runExtra18} from "./adapters-extra18.js";
import {OPERATIONS as EXTRA19_OPERATIONS,runAdapter as runExtra19} from "./adapters-extra19.js";
import {OPERATIONS as EXTRA20_OPERATIONS,runAdapter as runExtra20} from "./adapters-extra20.js";
import {OPERATIONS as EXTRA21_OPERATIONS,runAdapter as runExtra21} from "./adapters-extra21.js";
import {OPERATIONS as EXTRA22_OPERATIONS,runAdapter as runExtra22} from "./adapters-extra22.js";
export const OPERATIONS={...CORE_OPERATIONS,...EXTRA_OPERATIONS,...EXTRA2_OPERATIONS,...EXTRA3_OPERATIONS,...EXTRA4_OPERATIONS,...EXTRA5_OPERATIONS,...EXTRA6_OPERATIONS,...EXTRA7_OPERATIONS,...EXTRA8_OPERATIONS,...EXTRA9_OPERATIONS,...EXTRA10_OPERATIONS,...EXTRA11_OPERATIONS,...EXTRA12_OPERATIONS,...EXTRA13_OPERATIONS,...EXTRA14_OPERATIONS,...EXTRA15_OPERATIONS,...EXTRA16_OPERATIONS,...EXTRA17_OPERATIONS,...EXTRA18_OPERATIONS,...EXTRA19_OPERATIONS,...EXTRA20_OPERATIONS,...EXTRA21_OPERATIONS,...EXTRA22_OPERATIONS};
export async function runAdapter(provider,operation,args,env){
  if(EXTRA22_OPERATIONS[provider]?.includes(operation))return runExtra22(provider,operation,args,env);
  if(EXTRA21_OPERATIONS[provider]?.includes(operation))return runExtra21(provider,operation,args,env);
  if(EXTRA20_OPERATIONS[provider]?.includes(operation))return runExtra20(provider,operation,args,env);
  if(EXTRA19_OPERATIONS[provider]?.includes(operation))return runExtra19(provider,operation,args,env);
  if(EXTRA18_OPERATIONS[provider]?.includes(operation))return runExtra18(provider,operation,args,env);
  if(EXTRA17_OPERATIONS[provider]?.includes(operation))return runExtra17(provider,operation,args,env);
  if(EXTRA16_OPERATIONS[provider]?.includes(operation))return runExtra16(provider,operation,args,env);
  if(EXTRA15_OPERATIONS[provider]?.includes(operation))return runExtra15(provider,operation,args,env);
  if(EXTRA14_OPERATIONS[provider]?.includes(operation))return runExtra14(provider,operation,args,env);
  if(EXTRA13_OPERATIONS[provider]?.includes(operation))return runExtra13(provider,operation,args,env);
  if(EXTRA12_OPERATIONS[provider]?.includes(operation))return runExtra12(provider,operation,args,env);
  if(EXTRA11_OPERATIONS[provider]?.includes(operation))return runExtra11(provider,operation,args,env);
  if(EXTRA10_OPERATIONS[provider]?.includes(operation))return runExtra10(provider,operation,args,env);
  if(EXTRA9_OPERATIONS[provider]?.includes(operation))return runExtra9(provider,operation,args,env);
  if(EXTRA8_OPERATIONS[provider]?.includes(operation))return runExtra8(provider,operation,args,env);
  if(EXTRA7_OPERATIONS[provider]?.includes(operation))return runExtra7(provider,operation,args,env);
  if(EXTRA6_OPERATIONS[provider]?.includes(operation))return runExtra6(provider,operation,args,env);
  if(EXTRA5_OPERATIONS[provider]?.includes(operation))return runExtra5(provider,operation,args,env);
  if(EXTRA4_OPERATIONS[provider]?.includes(operation))return runExtra4(provider,operation,args,env);
  if(EXTRA3_OPERATIONS[provider]?.includes(operation))return runExtra3(provider,operation,args,env);
  if(EXTRA2_OPERATIONS[provider]?.includes(operation))return runExtra2(provider,operation,args,env);
  if(EXTRA_OPERATIONS[provider]?.includes(operation))return runExtra(provider,operation,args,env);
  return runCore(provider,operation,args,env);
}