const MAX_BYTES=1500000,TIMEOUT_MS=20000;
const UA="IntelligenceCenter/2026.08 (https://github.com/three-center-static-relay/qingbaozhongxin; read-only)";
const MCP_PROTOCOL_VERSION="2025-11-25";
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
const envRequired=(env,k)=>{const v=env?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:k}});return String(v)};
async function bounded(url,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,error:body?.detail||body?.message||body?.error?.message||body?.error||null}});return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
const BF_ENDPOINT="https://api.browserfabric.com/api/v1/services/browseruse/call";
async function bfCall(env,toolName,args={},sessionId=null){const key=envRequired(env,"BROWSERFABRIC_API_KEY"),body={tool_name:toolName,arguments:args};if(sessionId)body.session_id=sessionId;return bounded(BF_ENDPOINT,{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body)})}
const BROWSER_SOURCES={pkulaw:{base:"https://www.pkulaw.com/",hosts:new Set(["www.pkulaw.com","sfb.pkulaw.com","home.pkulaw.com"]),context:"PKULAW_BROWSERFABRIC_CONTEXT_ID"}};
function fixedTarget(provider,args){const s=BROWSER_SOURCES[provider],raw=text(args?.path||s.base,2000),u=new URL(raw,s.base);if(u.protocol!=="https:"||!s.hosts.has(u.hostname))throw Object.assign(new Error("POLICY_DENIED_FIXED_SOURCE_ONLY"),{status:403});u.username="";u.password="";u.hash="";return u.toString()}
async function createBrowserSession(env,contextId){const base={headless:true};let contextRestoreFailed=false;if(contextId){try{const created=await bfCall(env,"create_session",{...base,context_id:contextId});const sessionId=created?.result?.session_id||created?.session_id;if(!sessionId)throw Object.assign(new Error("UPSTREAM_BAD_SESSION"),{status:502});return{sessionId,authMode:"persistent-context",contextRestoreFailed:false}}catch(e){if(!["UPSTREAM_HTTP_ERROR","UPSTREAM_BAD_SESSION"].includes(String(e?.message||"")))throw e;contextRestoreFailed=true}}
  const created=await bfCall(env,"create_session",base),sessionId=created?.result?.session_id||created?.session_id;if(!sessionId)throw Object.assign(new Error("UPSTREAM_BAD_SESSION"),{status:502});return{sessionId,authMode:"public-session",contextRestoreFailed}}
async function readBrowserPage(env,operation,sessionId,target){const nav=await bfCall(env,"navigate",{url:target},sessionId);const out=operation==="snapshot"?await bfCall(env,"snapshot",{},sessionId):await bfCall(env,"page_summary",{},sessionId);return{navigation:nav?.result||nav,data:out?.result||out}}
async function browserRead(provider,operation,args,env){const s=BROWSER_SOURCES[provider],contextId=text(env?.[s.context]||"",256),target=fixedTarget(provider,args);let sessionId=null,authMode="public-session",contextRestoreFailed=false;try{let created=await createBrowserSession(env,contextId);sessionId=created.sessionId;authMode=created.authMode;contextRestoreFailed=created.contextRestoreFailed;try{const read=await readBrowserPage(env,operation,sessionId,target);return{provider,operation,auth_mode:authMode,persistent_context_configured:Boolean(contextId),context_restore_failed:contextRestoreFailed,...read}}catch(e){if(authMode!=="persistent-context"||String(e?.message||"")!=="UPSTREAM_HTTP_ERROR")throw e;try{await bfCall(env,"close_session",{},sessionId)}catch{}sessionId=null;created=await createBrowserSession(env,"");sessionId=created.sessionId;authMode="public-session";contextRestoreFailed=true;const read=await readBrowserPage(env,operation,sessionId,target);return{provider,operation,auth_mode:authMode,persistent_context_configured:Boolean(contextId),context_restore_failed:true,...read}}}finally{if(sessionId)try{await bfCall(env,"close_session",{},sessionId)}catch{}}}

function yuandianKey(env){return String(env?.YD_API_KEY||env?.YUANDIAN_API_KEY||"").trim()||envRequired(env,"YD_API_KEY")}
function trimObject(v,depth=0){if(depth>5)return null;if(Array.isArray(v))return v.slice(0,50).map(x=>trimObject(x,depth+1));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v).slice(0,80))o[text(k,100)]=trimObject(x,depth+1);return o}if(typeof v==="string")return text(v,5000);if(typeof v==="number"||typeof v==="boolean"||v===null)return v;return text(v,5000)}
const YUANDIAN_MCP={
  law_search:{endpoint:"https://open.chineselaw.com/mcp/law/stream",tool:"yuandian_law_vector_search"},
  case_search:{endpoint:"https://open.chineselaw.com/mcp/case/stream",tool:"yuandian_case_vector_search"},
  enterprise_search:{endpoint:"https://open.chineselaw.com/mcp/company/stream",tool:"yuandian_rh_enterpriseSearch"}
};
function parseSse(raw){const messages=[];for(const block of String(raw||"").split(/\r?\n\r?\n/)){const lines=block.split(/\r?\n/),data=lines.filter(x=>x.startsWith("data:")).map(x=>x.slice(5).trim()).join("\n");if(!data||data==="[DONE]")continue;try{messages.push(JSON.parse(data))}catch{}}return messages}
async function mcpHttp(url,{key,method,name,body,sessionId,protocolVersion=MCP_PROTOCOL_VERSION,allowEmpty=false}){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const headers={authorization:`Bearer ${key}`,accept:"application/json, text/event-stream","content-type":"application/json","user-agent":UA,"mcp-method":method};if(name)headers["mcp-name"]=name;if(sessionId)headers["mcp-session-id"]=sessionId;if(method!=="initialize")headers["mcp-protocol-version"]=protocolVersion;const r=await fetch(url,{method:"POST",headers,body:JSON.stringify(body),signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,error:text(raw,1000)||null}});if(!raw.trim()){if(allowEmpty)return{body:null,sessionId:r.headers.get("mcp-session-id")||sessionId||null};throw Object.assign(new Error("UPSTREAM_BAD_MCP_RESPONSE"),{status:502})}let parsed;const ct=(r.headers.get("content-type")||"").toLowerCase();if(ct.includes("text/event-stream")){const events=parseSse(raw);parsed=events.find(x=>x?.id===body?.id)||events.find(x=>x?.result||x?.error)||events.at(-1)||null}else{try{parsed=JSON.parse(raw)}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}}if(!parsed)throw Object.assign(new Error("UPSTREAM_BAD_MCP_RESPONSE"),{status:502});if(parsed.error)throw Object.assign(new Error("UPSTREAM_MCP_ERROR"),{status:502,details:{code:parsed.error.code,message:text(parsed.error.message,1000)}});return{body:parsed,sessionId:r.headers.get("mcp-session-id")||sessionId||null}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
function unwrapMcpResult(result){if(result?.isError===true)throw Object.assign(new Error("UPSTREAM_MCP_TOOL_ERROR"),{status:502,details:{content:trimObject(result?.content)}});if(result?.structuredContent!==undefined)return trimObject(result.structuredContent);const content=Array.isArray(result?.content)?result.content:[];const texts=content.filter(x=>x?.type==="text"&&typeof x.text==="string").map(x=>x.text);if(texts.length===1){try{return trimObject(JSON.parse(texts[0]))}catch{}}return trimObject(result)}
async function yuandianMcp(operation,args,env){const spec=YUANDIAN_MCP[operation];if(!spec)throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});const key=yuandianKey(env),idBase=Date.now(),initBody={jsonrpc:"2.0",id:idBase,method:"initialize",params:{protocolVersion:MCP_PROTOCOL_VERSION,capabilities:{},clientInfo:{name:"three-center-intelligence",version:"2026.08"}}};const init=await mcpHttp(spec.endpoint,{key,method:"initialize",body:initBody});const negotiated=text(init.body?.result?.protocolVersion||MCP_PROTOCOL_VERSION,64),sessionId=init.sessionId;await mcpHttp(spec.endpoint,{key,method:"notifications/initialized",body:{jsonrpc:"2.0",method:"notifications/initialized"},sessionId,protocolVersion:negotiated,allowEmpty:true});let toolArgs;if(operation==="law_search"){toolArgs={query:text(required(args,"query"),2000),rewrite_flag:Boolean(args?.rewrite_flag??false),return_num:Math.max(1,Math.min(50,Number(args?.return_num)||10))};if(args?.fatiao_filter)toolArgs.fatiao_filter=trimObject(args.fatiao_filter)}else if(operation==="case_search"){toolArgs={query:text(required(args,"query"),2000),rewrite_flag:Boolean(args?.rewrite_flag??false),return_num:Math.max(1,Math.min(50,Number(args?.return_num)||10))};if(args?.wenshu_filter)toolArgs.wenshu_filter=trimObject(args.wenshu_filter)}else{toolArgs={name:text(required(args,"name"),300),top_k:Math.max(1,Math.min(50,Number(args?.top_k)||10))}}const callBody={jsonrpc:"2.0",id:idBase+1,method:"tools/call",params:{name:spec.tool,arguments:toolArgs}},call=await mcpHttp(spec.endpoint,{key,method:"tools/call",name:spec.tool,body:callBody,sessionId,protocolVersion:negotiated});return{provider:"yuandian",operation,transport:"mcp-streamable-http",mcp_server:spec.endpoint,mcp_tool:spec.tool,protocol_version:negotiated,data:unwrapMcpResult(call.body?.result)}}

function safeSparql(v){let q=text(v,10000);if(!/^\s*(SELECT|ASK)\b/i.test(q))throw Object.assign(new Error("POLICY_DENIED_READ_ONLY_QUERY"),{status:403});if(/\bSERVICE\b/i.test(q)||/\b(INSERT|DELETE|LOAD|CLEAR|CREATE|DROP|COPY|MOVE|ADD|WITH)\b/i.test(q))throw Object.assign(new Error("POLICY_DENIED_READ_ONLY_QUERY"),{status:403});for(const m of q.matchAll(/\bLIMIT\s+(\d+)/ig))if(Number(m[1])>500)throw Object.assign(new Error("QUERY_LIMIT_TOO_LARGE"),{status:400});if(/^\s*SELECT\b/i.test(q)&&!/\bLIMIT\s+\d+/i.test(q))q+=`\nLIMIT 200`;return q}
async function wikidata(operation,args){if(operation==="entity_get"){const id=text(required(args,"id"),32).toUpperCase();if(!/^[QP]\d+$/.test(id))throw Object.assign(new Error("INVALID_WIKIDATA_ENTITY_ID"),{status:400});const u=`https://www.wikidata.org/wiki/Special:EntityData/${encodeURIComponent(id)}.json`;const out=await bounded(u,{headers:{accept:"application/json","user-agent":UA}});return{provider:"wikidata",operation,data:out?.entities?.[id]||null}}
  const query=safeSparql(required(args,"query")),body=new URLSearchParams({query,format:"json"}).toString(),out=await bounded("https://query.wikidata.org/sparql",{method:"POST",headers:{accept:"application/sparql-results+json","content-type":"application/x-www-form-urlencoded;charset=UTF-8","user-agent":UA},body});return{provider:"wikidata",operation,data:out}}
export const OPERATIONS={pkulaw:["snapshot","page_info"],yuandian:["law_search","case_search","enterprise_search"],wikidata:["sparql","entity_get"]};
export async function runAdapter(provider,operation,args,env){if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});if(provider==="pkulaw")return browserRead(provider,operation,args||{},env);if(provider==="yuandian")return yuandianMcp(operation,args||{},env);if(provider==="wikidata")return wikidata(operation,args||{});throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501})}
