const MAX_BYTES=1800000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function req(v,name,n=300){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function tok(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=req(v,name,n);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function isoDate(v,name){const s=text(v,30);if(!s)return"";if(!/^\d{4}(?:-\d{2}-\d{2})?$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function year(v,name="year"){const s=text(v,4);if(!/^\d{4}$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x)){if(["api_key","apikey","authorization","token","access_token"].includes(k.toLowerCase()))o[k]="[redacted]";else o[k]=redact(v)}return o}return x}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.error?.message||body?.message||raw,400)});return{body:redact(body),content_type:r.headers.get("content-type")||""}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

const WB="https://api.worldbank.org/v2";
function wbIds(v,name,max=8){const a=(Array.isArray(v)?v:String(v||"").split(/[;,]/)).map(x=>String(x).trim()).filter(Boolean).slice(0,max);if(!a.length)err(`ARG_REQUIRED:${name}`);if(a.some(x=>!/^[A-Za-z0-9._-]+$/.test(x)))err(`INVALID_${name.toUpperCase()}`);return a}
async function worldbank(operation,args){
 if(operation==="countries"){const u=new URL(`${WB}/country`);u.searchParams.set("format","json");u.searchParams.set("page",String(clamp(args?.page,1,500,1)));u.searchParams.set("per_page",String(clamp(args?.limit,1,200,50)));const{body}=await request(u);return{provider:"worldbank",operation,metadata:Array.isArray(body)?body[0]:null,items:Array.isArray(body)?body[1]||[]:[]}}
 if(operation==="indicator_metadata"){const id=tok(args?.indicator,"indicator",/^[A-Za-z0-9._-]+$/,80),u=new URL(`${WB}/indicator/${encodeURIComponent(id)}`);u.searchParams.set("format","json");const{body}=await request(u);return{provider:"worldbank",operation,item:Array.isArray(body)?body?.[1]?.[0]||null:null}}
 if(operation==="topic_indicators"){const topic=tok(args?.topic,"topic",/^\d{1,4}$/,4),u=new URL(`${WB}/topic/${encodeURIComponent(topic)}/indicator`);u.searchParams.set("format","json");u.searchParams.set("page",String(clamp(args?.page,1,500,1)));u.searchParams.set("per_page",String(clamp(args?.limit,1,200,50)));const{body}=await request(u);return{provider:"worldbank",operation,metadata:Array.isArray(body)?body[0]:null,items:Array.isArray(body)?body[1]||[]:[]}}
 if(operation==="multi_indicator"){const countries=wbIds(args?.countries||args?.country,"countries",8),indicators=wbIds(args?.indicators||args?.indicator,"indicators",8),source=tok(args?.source||"2","source",/^\d{1,5}$/,5),u=new URL(`${WB}/country/${countries.map(encodeURIComponent).join(";")}/indicator/${indicators.map(encodeURIComponent).join(";")}`);u.searchParams.set("format","json");u.searchParams.set("source",source);u.searchParams.set("per_page",String(clamp(args?.limit,1,500,200)));if(args?.date)u.searchParams.set("date",text(args.date,30));const{body}=await request(u);return{provider:"worldbank",operation,countries,indicators,metadata:Array.isArray(body)?body[0]:null,items:Array.isArray(body)?body[1]||[]:[]}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}

const IMF="https://www.imf.org/external/datamapper/api/v2";
async function imf(operation,args){
 if(["indicators","countries","regions","groups"].includes(operation)){const{body}=await request(`${IMF}/${operation}`);return{provider:"imf",operation,data:body}}
 if(operation==="timeseries"){const indicator=tok(args?.indicator,"indicator",/^[A-Za-z0-9_]+$/,80).toUpperCase(),locations=wbIds(args?.locations||args?.countries||args?.country,"locations",12).map(x=>x.toUpperCase()),u=new URL(`${IMF}/${encodeURIComponent(indicator)}/${locations.map(encodeURIComponent).join("/")}`);const periods=(Array.isArray(args?.periods)?args.periods:String(args?.periods||"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,30);if(periods.length){for(const p of periods)year(p,"period");u.searchParams.set("periods",periods.join(","))}const{body}=await request(u);return{provider:"imf",operation,indicator,locations,data:body}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}

const FRED="https://api.stlouisfed.org/fred";
function fredKey(env){const k=text(env?.FRED_API_KEY,100);if(!k)err("UPSTREAM_AUTH_FAILED",503,{missing:"FRED_API_KEY"});return k}
async function fred(operation,args,env){const api=fredKey(env),u=new URL(`${FRED}/${operation==="series"?"series":operation==="search"?"series/search":"series/vintagedates"}`);u.searchParams.set("api_key",api);u.searchParams.set("file_type","json");if(operation==="series"||operation==="vintages")u.searchParams.set("series_id",tok(args?.series_id,"series_id",/^[A-Za-z0-9._-]+$/,100));if(operation==="search"){u.searchParams.set("search_text",req(args?.query,"query",240));u.searchParams.set("limit",String(clamp(args?.limit,1,100,20)));u.searchParams.set("order_by",["search_rank","popularity","last_updated"].includes(args?.order_by)?args.order_by:"search_rank")}if(operation==="vintages")u.searchParams.set("limit",String(clamp(args?.limit,1,1000,200)));const{body}=await request(u);return{provider:"fred",operation,items:operation==="vintages"?body?.vintage_dates||[]:body?.seriess||[],metadata:{count:body?.count??null,limit:body?.limit??null,offset:body?.offset??null}}}

const EIA="https://api.eia.gov/v2";
const EIA_ROOTS=new Set(["electricity","petroleum","natural-gas","coal","international","seds","steo","aeo","ieo","total-energy"]);
function eiaPath(v){const s=req(v,"route",220).replace(/^\/+|\/+$/g,"");const parts=s.split("/").filter(Boolean);if(!parts.length||parts.length>6||!EIA_ROOTS.has(parts[0])||parts.some(x=>!/^[A-Za-z0-9._-]+$/.test(x)))err("INVALID_EIA_ROUTE",400,{allowed_roots:[...EIA_ROOTS]});return parts.join("/")}
function eiaKey(env){const k=text(env?.EIA_API_KEY,100);if(!k)err("UPSTREAM_AUTH_FAILED",503,{missing:"EIA_API_KEY"});return k}
async function eia(operation,args,env){const key=eiaKey(env),route=eiaPath(args?.route||args?.root),u=new URL(`${EIA}/${route}${operation==="data"?"/data":""}/`);u.searchParams.set("api_key",key);if(operation==="route"){const{body}=await request(u);return{provider:"eia",operation,route,data:body}}
 if(operation==="data"){if(args?.frequency)u.searchParams.set("frequency",tok(args.frequency,"frequency",/^[A-Za-z0-9_-]+$/,40));const data=(Array.isArray(args?.data)?args.data:String(args?.data||"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,12);for(const d of data){if(!/^[A-Za-z0-9_.-]+$/.test(d))err("INVALID_EIA_DATA_FIELD");u.searchParams.append("data[]",d)}const facets=args?.facets&&typeof args.facets==="object"&&!Array.isArray(args.facets)?Object.entries(args.facets).slice(0,10):[];for(const[k,v]of facets){if(!/^[A-Za-z0-9_.-]+$/.test(k))err("INVALID_EIA_FACET");const vals=(Array.isArray(v)?v:[v]).slice(0,20);for(const x of vals){const s=text(x,100);if(!/^[A-Za-z0-9_.:@,+ -]+$/.test(s))err("INVALID_EIA_FACET_VALUE");u.searchParams.append(`facets[${k}][]`,s)}}if(args?.start)u.searchParams.set("start",text(args.start,30));if(args?.end)u.searchParams.set("end",text(args.end,30));u.searchParams.set("offset",String(clamp(args?.offset,0,1000000,0)));u.searchParams.set("length",String(clamp(args?.limit,1,500,100)));const{body}=await request(u);return{provider:"eia",operation,route,data:body}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}

const BIS="https://stats.bis.org/api/v2";
async function bis(operation,args){
 if(operation==="structure"){const type=tok(args?.structure_type||"dataflow","structure_type",/^[A-Za-z]+$/,30).toLowerCase();if(!new Set(["dataflow","datastructure","codelist","conceptscheme","categoryscheme","contentconstraint"]).has(type))err("INVALID_BIS_STRUCTURE_TYPE");const agency=tok(args?.agency||"all","agency",/^[A-Za-z0-9_.-]+$/,80),resource=tok(args?.resource||"all","resource",/^[A-Za-z0-9_.-]+$/,100),version=tok(args?.version||"latest","version",/^[A-Za-z0-9_.-]+$/,30),{body,content_type}=await request(`${BIS}/structure/${type}/${agency}/${resource}/${version}`,{headers:{accept:"application/vnd.sdmx.structure+json;version=2.0.0, application/json;q=0.9, */*;q=0.1"}});return{provider:"bis",operation,content_type,data:body}}
 if(operation==="data"){const context=tok(args?.context||"dataflow","context",/^[A-Za-z]+$/,30),agency=tok(args?.agency,"agency",/^[A-Za-z0-9_.-]+$/,80),resource=tok(args?.resource,"resource",/^[A-Za-z0-9_.-]+$/,100),version=tok(args?.version||"latest","version",/^[A-Za-z0-9_.-]+$/,30),key=text(args?.key||"all",300);if(!/^[A-Za-z0-9_.@,+*:-]+$/.test(key))err("INVALID_BIS_KEY");const u=new URL(`${BIS}/data/${context}/${agency}/${resource}/${version}/${key}`);if(args?.start_period)u.searchParams.set("startPeriod",text(args.start_period,30));if(args?.end_period)u.searchParams.set("endPeriod",text(args.end_period,30));const{body,content_type}=await request(u,{headers:{accept:"application/vnd.sdmx.data+json;version=2.0.0, application/json;q=0.9, */*;q=0.1"}});return{provider:"bis",operation,content_type,data:body}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}

const TREASURY="https://api.fiscaldata.treasury.gov/services/api/fiscal_service";
const TREASURY_ENDPOINTS={debt_to_penny:"v2/accounting/od/debt_to_penny",avg_interest_rates:"v2/accounting/od/avg_interest_rates",auctions:"v1/accounting/od/auctions_query"};
async function treasury(operation,args){const path=TREASURY_ENDPOINTS[operation];if(!path)err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`${TREASURY}/${path}`);u.searchParams.set("format","json");u.searchParams.set("page[number]",String(clamp(args?.page,1,10000,1)));u.searchParams.set("page[size]",String(clamp(args?.limit,1,200,50)));u.searchParams.set("sort","-record_date");const filters=[];const start=isoDate(args?.start,"start"),end=isoDate(args?.end,"end");if(start)filters.push(`record_date:gte:${start}`);if(end)filters.push(`record_date:lte:${end}`);if(operation==="avg_interest_rates"&&args?.security_type){const s=tok(args.security_type,"security_type",/^[A-Za-z -]+$/,40);filters.push(`security_type_desc:eq:${s}`)}if(operation==="auctions"&&args?.security_type){const s=tok(args.security_type,"security_type",/^[A-Za-z -]+$/,40);filters.push(`security_type:eq:${s}`)}if(filters.length)u.searchParams.set("filter",filters.join(","));const{body}=await request(u);return{provider:"us_treasury_fiscaldata",operation,meta:body?.meta||null,items:body?.data||[]}}

const FUSION={
 gdp_growth:{label:"Real GDP growth",unit:"percent",wb:"NY.GDP.MKTP.KD.ZG",imf:"NGDP_RPCH",note:"Both are annual growth rates but source vintages and estimation methods can differ."},
 inflation:{label:"Consumer price inflation",unit:"percent",wb:"FP.CPI.TOTL.ZG",imf:"PCPIPCH",note:"World Bank and IMF series can differ by source vintage and national methodology."},
 unemployment:{label:"Unemployment rate",unit:"percent",wb:"SL.UEM.TOTL.ZS",imf:"LUR",note:"Definitions and source series may differ; treat as a consistency check, not identity."}
};
function wbPoint(body,yr){const items=Array.isArray(body)?body[1]||[]:[];const x=items.find(r=>String(r?.date)===yr);return x?.value===null||x?.value===undefined?null:Number(x.value)}
function imfPoint(body,indicator,country,yr){const v=body?.values?.[indicator]?.[country]?.[yr];return v===null||v===undefined?null:Number(v)}
async function fusion(operation,args){if(operation==="catalog")return{provider:"splus_macro_fusion",operation,metrics:Object.entries(FUSION).map(([id,x])=>({id,...x}))};if(operation!=="compare")err("ADAPTER_OPERATION_NOT_APPROVED",403);const metric=text(args?.metric,50).toLowerCase(),m=FUSION[metric];if(!m)err("INVALID_FUSION_METRIC",400,{allowed:Object.keys(FUSION)});const country=tok(args?.country,"country",/^[A-Za-z]{3}$/,3).toUpperCase(),yr=year(args?.year);const wu=new URL(`${WB}/country/${country}/indicator/${m.wb}`);wu.searchParams.set("format","json");wu.searchParams.set("date",yr);wu.searchParams.set("per_page","5");const wb=(await request(wu)).body;const iu=new URL(`${IMF}/${m.imf}/${country}`);iu.searchParams.set("periods",yr);const ib=(await request(iu)).body;const wv=wbPoint(wb,yr),iv=imfPoint(ib,m.imf,country,yr),gap=Number.isFinite(wv)&&Number.isFinite(iv)?Math.abs(wv-iv):null;return{provider:"splus_macro_fusion",operation,metric,label:m.label,country,year:yr,unit:m.unit,records:[{source:"World Bank",indicator:m.wb,value:Number.isFinite(wv)?wv:null},{source:"IMF DataMapper",indicator:m.imf,value:Number.isFinite(iv)?iv:null}],comparison:{comparable:Number.isFinite(wv)&&Number.isFinite(iv),absolute_gap:gap,agreement:gap===null?"insufficient":gap<=0.5?"close":gap<=1.5?"moderate-gap":"divergent"},caveat:m.note}}

export const OPERATIONS={
 worldbank:["countries","indicator_metadata","topic_indicators","multi_indicator"],
 imf:["indicators","countries","regions","groups","timeseries"],
 fred:["series","search","vintages"],
 eia:["route","data"],
 bis:["structure","data"],
 us_treasury_fiscaldata:["debt_to_penny","avg_interest_rates","auctions"],
 splus_macro_fusion:["catalog","compare"]
};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="worldbank")return worldbank(operation,args);if(provider==="imf")return imf(operation,args);if(provider==="fred")return fred(operation,args,env);if(provider==="eia")return eia(operation,args,env);if(provider==="bis")return bis(operation,args);if(provider==="us_treasury_fiscaldata")return treasury(operation,args);if(provider==="splus_macro_fusion")return fusion(operation,args);err("ADAPTER_NOT_IMPLEMENTED",501)}
