const MAX_BYTES=1800000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function req(v,name,n=300){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function tok(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=req(v,name,n);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function arr(v,n=20){return(Array.isArray(v)?v:String(v??"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,n)}
function secret(env,name,required=false){const s=text(env?.[name],300);if(required&&!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const o={};for(const[k,v]of Object.entries(x)){if(["subscription-key","subscription_key","x-app-token","app_token","apikey","api_key","token"].includes(k.toLowerCase()))o[k]="[redacted]";else o[k]=redact(v)}return o}return x}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.message||body?.error||raw,400)});return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

const COMTRADE_CLASS=new Set(["HS","H0","H1","H2","H3","H4","H5","H6","S1","S2","S3","S4"]);
function comtradeSelection(args){
 const type=String(args?.type_code||"C").toUpperCase(),freq=String(args?.freq_code||"A").toUpperCase(),cl=String(args?.cl_code||"HS").toUpperCase();
 if(!["C","S"].includes(type))err("INVALID_COMTRADE_TYPE");if(!["A","M"].includes(freq))err("INVALID_COMTRADE_FREQUENCY");if(!COMTRADE_CLASS.has(cl))err("INVALID_COMTRADE_CLASSIFICATION");
 const period=req(args?.period,"period",40),periodOk=freq==="A"?/^\d{4}(,\d{4})*$/.test(period):/^\d{6}(,\d{6})*$/.test(period);if(!periodOk)err("INVALID_COMTRADE_PERIOD");
 const reporter=tok(args?.reporter_code,"reporter_code",/^\d+(,\d+)*$/,80),uparams={reporterCode:reporter,period,maxRecords:String(clamp(args?.limit,1,500,100)),format:"JSON",includeDesc:args?.include_desc===false?"false":"true"};
 for(const[k,name,re]of [["cmd_code","cmdCode",/^[A-Za-z0-9*+,.-]+$/],["flow_code","flowCode",/^[A-Za-z0-9+,.-]+$/],["partner_code","partnerCode",/^\d+(,\d+)*$/],["partner2_code","partner2Code",/^\d+(,\d+)*$/],["customs_code","customsCode",/^[A-Za-z0-9+,.-]+$/],["mot_code","motCode",/^[A-Za-z0-9+,.-]+$/]])if(args?.[k]!==undefined)uparams[name]=tok(args[k],k,re,120);
 if(args?.aggregate_by)uparams.aggregateBy=tok(args.aggregate_by,"aggregate_by",/^[A-Za-z0-9,+.-]+$/,100);if(args?.breakdown_mode){const s=String(args.breakdown_mode).toLowerCase();if(!["classic","plus"].includes(s))err("INVALID_COMTRADE_BREAKDOWN_MODE");uparams.breakdownMode=s}return{type,freq,cl,uparams};
}
async function comtrade(operation,args,env){const s=comtradeSelection(args),key=secret(env,"UN_COMTRADE_API_KEY",operation==="data"),base=operation==="data"?"https://comtradeapi.un.org/data/v1/get":"https://comtradeapi.un.org/public/v1/preview",u=new URL(`${base}/${s.type}/${s.freq}/${s.cl}`);for(const[k,v]of Object.entries(s.uparams))u.searchParams.set(k,v);if(key)u.searchParams.set("subscription-key",key);const body=await request(u);return{provider:"un_comtrade",operation,selection:{type_code:s.type,freq_code:s.freq,cl_code:s.cl},count:body?.count??null,items:Array.isArray(body?.data)?body.data:[],validation:body?.validation||null}}

const RELIEF_TYPES=new Set(["reports","disasters"]);
async function relief(operation,args,env){if(!RELIEF_TYPES.has(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);const app=secret(env,"RELIEFWEB_APPNAME",true);if(!/^[A-Za-z0-9_.:-]{3,120}$/.test(app))err("UPSTREAM_AUTH_FAILED",503,{invalid:"RELIEFWEB_APPNAME"});const u=new URL(`https://api.reliefweb.int/v2/${operation}`);u.searchParams.set("appname",app);const payload={limit:clamp(args?.limit,1,100,25),offset:clamp(args?.offset,0,10000,0),profile:"list",slim:1};const q=text(args?.query,240);if(q)payload.query={value:q,operator:"AND"};const body=await request(u,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"reliefweb",operation,total:body?.totalCount??null,items:Array.isArray(body?.data)?body.data:[]}}

async function gdacs(operation){if(operation==="source_info")return{provider:"gdacs",operation,role:"UN-EU Global Disaster Alert and Coordination System",api:"v1",scope:"earthquakes-cyclones-floods-volcanoes-drought-and-related-alerts"};if(operation!=="latest")err("ADAPTER_OPERATION_NOT_APPROVED",403);return{provider:"gdacs",operation,data:await request("https://www.gdacs.org/contentdata/xml/homepage_datatable.json")}}

function datasetId(v){return tok(v,"dataset_id",/^[a-z0-9]{4}-[a-z0-9]{4}$/i,9).toLowerCase()}
function cdcHeaders(env){const t=secret(env,"CDC_APP_TOKEN",false);return t?{"X-App-Token":t}:{}}
async function cdc(operation,args,env){const id=datasetId(args?.dataset_id);if(operation==="metadata")return{provider:"cdc_open_data",operation,dataset_id:id,data:await request(`https://data.cdc.gov/api/views/${id}.json`,{headers:cdcHeaders(env)})};if(operation!=="rows")err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`https://data.cdc.gov/resource/${id}.json`);u.searchParams.set("$limit",String(clamp(args?.limit,1,500,100)));u.searchParams.set("$offset",String(clamp(args?.offset,0,10000000,0)));const fields=arr(args?.fields,25);if(fields.length){if(fields.some(x=>!/^[A-Za-z_][A-Za-z0-9_]*$/.test(x)))err("INVALID_CDC_FIELD");u.searchParams.set("$select",fields.join(","))}if(args?.order_by){const f=tok(args.order_by,"order_by",/^[A-Za-z_][A-Za-z0-9_]*$/,80),dir=String(args?.order||"asc").toLowerCase();if(!["asc","desc"].includes(dir))err("INVALID_CDC_ORDER");u.searchParams.set("$order",`${f} ${dir}`)}const filters=args?.filters&&typeof args.filters==="object"&&!Array.isArray(args.filters)?Object.entries(args.filters).slice(0,10):[];for(const[k,v]of filters){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(k))err("INVALID_CDC_FILTER_FIELD");const vals=arr(v,10);if(vals.length!==1)err("INVALID_CDC_FILTER_VALUE");u.searchParams.set(k,text(vals[0],160))}const body=await request(u,{headers:cdcHeaders(env)});return{provider:"cdc_open_data",operation,dataset_id:id,items:Array.isArray(body)?body:[]}}

const GLOBAL_CATALOG=[{provider:"un_comtrade",role:"official-global-merchandise-and-services-trade",auth:"preview-public; full-data-subscription-key"},{provider:"reliefweb",role:"UN-OCHA-humanitarian-reports-and-disasters",auth:"pre-approved-RELIEFWEB_APPNAME"},{provider:"gdacs",role:"global-disaster-alerts",auth:"public"},{provider:"cdc_open_data",role:"US-public-health-surveillance-open-data",auth:"public; CDC_APP_TOKEN optional for higher throttling"}];
export const OPERATIONS={un_comtrade:["preview","data"],reliefweb:["reports","disasters"],gdacs:["source_info","latest"],cdc_open_data:["metadata","rows"],splus_global_events_trade_health:["catalog"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="un_comtrade")return comtrade(operation,args,env);if(provider==="reliefweb")return relief(operation,args,env);if(provider==="gdacs")return gdacs(operation,args);if(provider==="cdc_open_data")return cdc(operation,args,env);if(provider==="splus_global_events_trade_health")return{provider,operation,items:GLOBAL_CATALOG};err("ADAPTER_NOT_IMPLEMENTED",501)}
