const MAX_BYTES=1500000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
const required=(v,name)=>{const s=text(v,1000);if(!s)throw Object.assign(new Error(`ARG_REQUIRED:${name}`),{status:400});return s};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function safeToken(v,name,n=120){const s=required(v,name).slice(0,n);if(!/^[A-Za-z0-9_.:-]+$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function bbox(v){const a=Array.isArray(v)?v.map(Number):String(v||"").split(",").map(Number);if(a.length!==4||a.some(x=>!Number.isFinite(x)))err("INVALID_BBOX");const[w,s,e,n]=a;if(w< -180||e>180||s< -90||n>90||w>=e||s>=n)err("INVALID_BBOX");return a.join(",")}
function point(v){const a=Array.isArray(v)?v.map(Number):String(v||"").split(",").map(Number);if(a.length!==2||a.some(x=>!Number.isFinite(x)))err("INVALID_POINT");const[lon,lat]=a;if(lon< -180||lon>180||lat< -90||lat>90)err("INVALID_POINT");return `${lon},${lat}`}
function temporal(v){const s=text(v,100);if(!s)return"";if(!/^\d{4}-\d{2}-\d{2}T[0-9:.+-]+Z?(,\d{4}-\d{2}-\d{2}T[0-9:.+-]+Z?)?$/.test(s))err("INVALID_TEMPORAL");return s}
async function bounded(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}});const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);let body=null;try{body=raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502,{http_status:r.status})}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(body?.errors?.[0]||body?.error?.message||body?.message||raw,500)});return body}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
const CMR_BASE="https://cmr.earthdata.nasa.gov/search";
const STAC_BASE="https://cmr.earthdata.nasa.gov/stac";
const HARMONY_BASE="https://harmony.earthdata.nasa.gov";
const ADS_BASE="https://api.adsabs.harvard.edu/v1/search/query";
export const NASA_HIGH_VALUE={
  merra2:{label:"MERRA-2",keyword:"MERRA-2",domain:"atmosphere-climate-reanalysis",value:"weather-climate-air-quality-energy"},
  gpm_imerg:{label:"GPM IMERG",keyword:"IMERG",domain:"precipitation",value:"rainfall-storm-flood-risk"},
  smap:{label:"SMAP",keyword:"SMAP",domain:"soil-moisture",value:"agriculture-drought-water"},
  ecostress:{label:"ECOSTRESS",keyword:"ECOSTRESS",domain:"land-surface-temperature",value:"urban-heat-agriculture-water-stress"},
  gedi:{label:"GEDI",keyword:"GEDI",domain:"vegetation-structure",value:"forest-height-biomass-built-form-crosscheck"},
  swot:{label:"SWOT",keyword:"SWOT",domain:"surface-water",value:"river-lake-water-level-hydrology"},
  grace_fo:{label:"GRACE / GRACE-FO",keyword:"GRACE",domain:"terrestrial-water-storage",value:"groundwater-drought-water-balance"},
  tempo:{label:"TEMPO",keyword:"TEMPO",domain:"air-quality",value:"high-frequency-no2-ozone-formaldehyde-pollution"},
  sedac:{label:"SEDAC",keyword:"SEDAC",domain:"human-dimensions",value:"population-urbanization-poverty-infrastructure-environment"},
  black_marble:{label:"Black Marble",keyword:"Black Marble",domain:"nighttime-lights",value:"human-activity-commercial-urban-intensity"},
  modis:{label:"MODIS",keyword:"MODIS",domain:"land-ocean-atmosphere",value:"vegetation-fire-temperature-aerosol-land-cover"},
  viirs:{label:"VIIRS",keyword:"VIIRS",domain:"land-atmosphere-night-lights",value:"fire-night-lights-aerosol-ocean-color"},
  landsat:{label:"Landsat",keyword:"Landsat",domain:"land-imagery",value:"urban-change-land-cover-surface-temperature"}
};
function cmrParams(args,kind){const u=new URL(`${CMR_BASE}/${kind}.json`),limit=clamp(args?.limit,1,100,20);u.searchParams.set("page_size",String(limit));if(args?.page_num)u.searchParams.set("page_num",String(clamp(args.page_num,1,500,1)));if(args?.query)u.searchParams.set("keyword",text(args.query,240));if(args?.provider)u.searchParams.append("provider",safeToken(args.provider,"provider",100));if(args?.concept_id)u.searchParams.append(kind==="granules"?"collection_concept_id":"concept_id",safeToken(args.concept_id,"concept_id",120));if(args?.short_name)u.searchParams.append("short_name",text(args.short_name,180));if(args?.temporal)u.searchParams.set("temporal",temporal(args.temporal));if(args?.bbox)u.searchParams.append("bounding_box[]",bbox(args.bbox));if(args?.point)u.searchParams.set("point",point(args.point));if(args?.downloadable===true)u.searchParams.set("downloadable","true");if(args?.cloud_hosted===true)u.searchParams.set("cloud_hosted","true");return u}
function entries(body){return Array.isArray(body?.feed?.entry)?body.feed.entry:Array.isArray(body?.items)?body.items:[]}
async function cmr(operation,args){if(operation==="high_value_catalog")return{provider:"nasa_cmr",operation,items:Object.entries(NASA_HIGH_VALUE).map(([id,x])=>({id,...x}))};if(operation==="preset"){const id=text(args?.dataset,80).toLowerCase(),p=NASA_HIGH_VALUE[id];if(!p)err("INVALID_NASA_DATASET",400,{allowed:Object.keys(NASA_HIGH_VALUE)});const u=cmrParams({...args,query:p.keyword},"collections");const body=await bounded(u);return{provider:"nasa_cmr",operation,dataset:id,preset:p,total:body?.feed?.hits??null,items:entries(body)}}const kind={collections:"collections",granules:"granules",variables:"variables",services:"services"}[operation];if(!kind)err("ADAPTER_OPERATION_NOT_APPROVED",403);if(kind==="granules"&&!args?.concept_id&&!args?.short_name)err("ARG_REQUIRED:concept_id_or_short_name");const body=await bounded(cmrParams(args,kind));return{provider:"nasa_cmr",operation,total:body?.feed?.hits??null,items:entries(body)}}
async function stac(operation,args){if(operation==="catalogs"){const body=await bounded(STAC_BASE);return{provider:"nasa_stac",operation,data:body}}const provider=safeToken(args?.provider,"provider",100),base=`${STAC_BASE}/${encodeURIComponent(provider)}`;if(operation==="collections"){const body=await bounded(`${base}/collections`);return{provider:"nasa_stac",operation,provider,items:Array.isArray(body?.collections)?body.collections:[],links:body?.links||[]}}if(operation==="search"){const u=new URL(`${base}/search`);u.searchParams.set("limit",String(clamp(args?.limit,1,100,20)));if(args?.bbox)u.searchParams.set("bbox",bbox(args.bbox));if(args?.datetime)u.searchParams.set("datetime",text(args.datetime,100));if(args?.collections){const cs=(Array.isArray(args.collections)?args.collections:[args.collections]).slice(0,10).map(x=>safeToken(x,"collection",160));u.searchParams.set("collections",cs.join(","))}const body=await bounded(u);return{provider:"nasa_stac",operation,provider,items:Array.isArray(body?.features)?body.features:[],links:body?.links||[]}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}
function earthdataHeaders(env){const tok=String(env?.NASA_EARTHDATA_TOKEN||"").replace(/^Bearer\s+/i,"").trim();return tok?{authorization:`Bearer ${tok}`}:{}}
async function harmony(operation,args,env){if(operation==="source_info")return{provider:"nasa_harmony",operation,endpoint:HARMONY_BASE,role:"NASA EOSDIS subset-reproject-format-transform service",auth:"NASA_EARTHDATA_TOKEN optional for capabilities and required for protected service/job operations"};if(operation!=="capabilities")err("ADAPTER_OPERATION_NOT_APPROVED",403);const u=new URL(`${HARMONY_BASE}/capabilities`);if(args?.collection_id)u.searchParams.set("collectionId",safeToken(args.collection_id,"collection_id",160));else if(args?.short_name)u.searchParams.set("shortName",text(args.short_name,180));else err("ARG_REQUIRED:collection_id_or_short_name");const body=await bounded(u,{headers:earthdataHeaders(env)});return{provider:"nasa_harmony",operation,data:body}}
async function ads(operation,args,env){if(operation!=="search")err("ADAPTER_OPERATION_NOT_APPROVED",403);const token=String(env?.NASA_ADS_TOKEN||"").replace(/^Bearer\s+/i,"").trim();if(!token)err("UPSTREAM_AUTH_FAILED",503,{missing:"NASA_ADS_TOKEN"});const u=new URL(ADS_BASE);u.searchParams.set("q",required(args?.query,"query").slice(0,500));u.searchParams.set("rows",String(clamp(args?.limit,1,50,10)));u.searchParams.set("fl","bibcode,title,author,year,pub,doi,citation_count,abstract");const body=await bounded(u,{headers:{authorization:`Bearer ${token}`}});return{provider:"nasa_ads",operation,total:body?.response?.numFound??null,items:body?.response?.docs||[]}}
export const OPERATIONS={nasa_cmr:["high_value_catalog","preset","collections","granules","variables","services"],nasa_stac:["catalogs","collections","search"],nasa_harmony:["source_info","capabilities"],nasa_ads:["search"]};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="nasa_cmr")return cmr(operation,args);if(provider==="nasa_stac")return stac(operation,args);if(provider==="nasa_harmony")return harmony(operation,args,env);if(provider==="nasa_ads")return ads(operation,args,env);err("ADAPTER_NOT_IMPLEMENTED",501)}
