const BASE="https://agent.qcc.com/mcp";
const TIMEOUT_MS=20000,MAX_RESPONSE_BYTES=1500000,MAX_TOOL_NAME=160;
const SERVERS=Object.freeze({
  company:{name:"qcc-company",url:`${BASE}/company/stream`,auth_required:true},
  risk:{name:"qcc-risk",url:`${BASE}/risk/stream`,auth_required:true},
  ipr:{name:"qcc-ipr",url:`${BASE}/ipr/stream`,auth_required:true},
  operation:{name:"qcc-operation",url:`${BASE}/operation/stream`,auth_required:true},
  history:{name:"qcc-history",url:`${BASE}/history/stream`,auth_required:true,enterprise_verification_required:true},
  executive:{name:"qcc-executive",url:`${BASE}/executive/stream`,auth_required:true},
  regulation:{name:"qcc-legal-regulation",url:`${BASE}/regulation/stream`,auth_required:true},
  case:{name:"qcc-legal-case",url:`${BASE}/case/stream`,auth_required:true},
  tender:{name:"qcc-tender",url:`${BASE}/tender/stream`,auth_required:true},
  document:{name:"qcc-document",url:`${BASE}/document/stream`,auth_required:true,remote_document_only:true}
});
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
function apiKey(env){const v=String(env?.QICHACHA_API_KEY||"").trim();if(!v)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:"QICHACHA_API_KEY"}});return v}
function serverOf(v){const k=String(v||"").toLowerCase().replace(/^qcc-/,'').replace(/^legal-/,'');const key=k==="legal-regulation"?"regulation":k==="legal-case"?"case":k;const s=SERVERS[key];if(!s)throw Object.assign(new Error("INVALID_QICHACHA_SERVER"),{status:400,details:{allowed:Object.keys(SERVERS)}});return{key,...s}}
function toolName(v){const s=String(v||"").trim();if(!s)throw Object.assign(new Error("ARG_REQUIRED:tool"),{status:400});if(s.length>MAX_TOOL_NAME||!/^[A-Za-z0-9_.:-]+$/.test(s))throw Object.assign(new Error("INVALID_QICHACHA_TOOL"),{status:400});return s}
function cleanJson(v,depth=0,state={n:0}){if(++state.n>3000)throw Object.assign(new Error("ARGUMENTS_TOO_COMPLEX"),{status:400});if(depth>10)throw Object.assign(new Error("ARGUMENTS_TOO_DEEP"),{status:400});if(v===null||typeof v==="boolean")return v;if(typeof v==="number"){if(!Number.isFinite(v))throw Object.assign(new Error("INVALID_NUMBER"),{status:400});return v}if(typeof v==="string"){if(v.length>12000)throw Object.assign(new Error("ARGUMENT_STRING_TOO_LONG"),{status:400});return v}if(Array.isArray(v)){if(v.length>500)throw Object.assign(new Error("ARGUMENT_ARRAY_TOO_LARGE"),{status:400});return v.map(x=>cleanJson(x,depth+1,state))}if(v&&typeof v==="object"){const e=Object.entries(v);if(e.length>200)throw Object.assign(new Error("ARGUMENT_OBJECT_TOO_LARGE"),{status:400});const o={};for(const[k,x]of e){if(!/^[A-Za-z0-9_.:-]{1,120}$/.test(k))throw Object.assign(new Error("INVALID_ARGUMENT_KEY"),{status:400});o[k]=cleanJson(x,depth+1,state)}return o}throw Object.assign(new Error("INVALID_ARGUMENT_VALUE"),{status:400})}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_RESPONSE_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel().catch(()=>{});throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502})}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
function parseMcp(raw,contentType=""){const t=String(raw||"").trim();if(!t)return null;if(String(contentType).includes("text/event-stream")||/^event:|^data:/m.test(t)){const events=[];for(const line of t.split(/\r?\n/)){if(!line.startsWith("data:"))continue;const d=line.slice(5).trim();if(!d||d==="[DONE]")continue;try{events.push(JSON.parse(d))}catch{}}return events.findLast?.(x=>x&&("result" in x||"error" in x))||events[events.length-1]||null}try{return JSON.parse(t)}catch{throw Object.assign(new Error("UPSTREAM_BAD_MCP_RESPONSE"),{status:502})}}
async function http(endpoint,key,body,{sessionId,protocol="2026-07-28",methodName,tool}={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);const headers={authorization:`Bearer ${key}`,accept:"application/json, text/event-stream","content-type":"application/json","mcp-protocol-version":protocol};if(sessionId)headers["mcp-session-id"]=sessionId;if(methodName)headers["mcp-method"]=methodName;if(tool)headers["mcp-name"]=tool;try{const r=await fetch(endpoint,{method:"POST",headers,body:JSON.stringify(body),signal:c.signal}),raw=await readBounded(r),data=parseMcp(raw,r.headers.get("content-type")||"");if(!r.ok)throw Object.assign(new Error(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR"),{status:r.status===401||r.status===403?503:502,details:{http_status:r.status,mcp_error:text(data?.error?.message,300)||null}});if(data?.error)throw Object.assign(new Error("QICHACHA_MCP_ERROR"),{status:502,details:{code:data.error.code??null,message:text(data.error.message,300)}});return{data,sessionId:r.headers.get("mcp-session-id")||sessionId||null,http_status:r.status}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
const meta=()=>({"io.modelcontextprotocol/clientInfo":{name:"three-center-intelligence",version:"2026.08"}});
async function direct(server,key,method,params={},tool){const body={jsonrpc:"2.0",id:crypto.randomUUID(),method,params:{...params,_meta:meta()}};return http(server.url,key,body,{protocol:"2026-07-28",methodName:method,tool})}
async function stateful(server,key,method,params={},tool){const init=await http(server.url,key,{jsonrpc:"2.0",id:crypto.randomUUID(),method:"initialize",params:{protocolVersion:"2025-11-25",capabilities:{},clientInfo:{name:"three-center-intelligence",version:"2026.08"}}},{protocol:"2025-11-25",methodName:"initialize"});const sid=init.sessionId;try{if(sid)await http(server.url,key,{jsonrpc:"2.0",method:"notifications/initialized",params:{}},{sessionId:sid,protocol:"2025-11-25",methodName:"notifications/initialized"}).catch(()=>null);return await http(server.url,key,{jsonrpc:"2.0",id:crypto.randomUUID(),method,params},{sessionId:sid,protocol:"2025-11-25",methodName:method,tool})}finally{if(sid){const c=new AbortController(),timer=setTimeout(()=>c.abort(),3000);fetch(server.url,{method:"DELETE",headers:{authorization:`Bearer ${key}`,"mcp-session-id":sid,"mcp-protocol-version":"2025-11-25"},signal:c.signal}).catch(()=>{}).finally(()=>clearTimeout(timer))}}}
async function callMcp(server,key,method,params={},tool){try{return await direct(server,key,method,params,tool)}catch(e){const hs=Number(e?.details?.http_status||0);const msg=String(e?.details?.mcp_error||e?.message||"");if(!(hs===400||hs===404||hs===405||/initialize|session|protocol|method/i.test(msg)))throw e;return stateful(server,key,method,params,tool)}}
export function qichachaMeta(){return{provider:"qichacha",integration:"official-agent-mcp",auth:"bearer-api-key",secret_name:"QICHACHA_API_KEY",servers:Object.fromEntries(Object.entries(SERVERS).map(([k,v])=>[k,{name:v.name,url:v.url,enterprise_verification_required:v.enterprise_verification_required===true,remote_document_only:v.remote_document_only===true}])),arbitrary_server:false,arbitrary_url:false,arbitrary_tool_name:false,read_only_transport:true,local_document_mcp:false,points_billing:true}}
export const OPERATIONS={qichacha:["servers","tools_list","tool_call"]};
export async function runAdapter(provider,operation,args,env){if(provider!=="qichacha"||!OPERATIONS.qichacha.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});if(operation==="servers")return{provider,operation,...qichachaMeta()};const key=apiKey(env),server=serverOf(args?.server);if(operation==="tools_list"){const out=await callMcp(server,key,"tools/list",{});const tools=Array.isArray(out.data?.result?.tools)?out.data.result.tools:[];return{provider,operation,server:server.name,tools:tools.slice(0,250).map(t=>({name:text(t?.name,MAX_TOOL_NAME),title:text(t?.title,300),description:text(t?.description,2000),inputSchema:t?.inputSchema||null,annotations:t?.annotations||null})),next_cursor:out.data?.result?.nextCursor||null}}if(operation==="tool_call"){const name=toolName(args?.tool),argumentsClean=cleanJson(args?.arguments??args?.params??{}),out=await callMcp(server,key,"tools/call",{name,arguments:argumentsClean},name);return{provider,operation,server:server.name,tool:name,result:out.data?.result??null}}throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501})}
export const __test={SERVERS,parseMcp,cleanJson,serverOf};
