const MAX_BYTES=1500000,TIMEOUT_MS=25000,MAX_ARGS_BYTES=24000;
const BASE="https://apim-gateway.pkulaw.com/";
const SERVICES={
  law_recognition:"law_recognition",
  "mcp-fatiao":"mcp-fatiao",
  "mcp-law":"mcp-law",
  "mcp-law-search-service":"mcp-law-search-service",
  "add-doc-link":"add-doc-link",
  pku_citation_validator:"pku_citation_validator",
  case_number_recognition:"case_number_recognition",
  "mcp-case":"mcp-case",
  "mcp-law-agg":"mcp-law-agg/mcp",
  "mcp-case-search-service":"mcp-case-search-service"
};
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
function token(env){const v=String(env?.PKULAW_MCP_TOKEN||env?.PKULAW_API_TOKEN||env?.BROWSERFABRIC_API_KEY||"").trim();if(!v)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:"PKULAW_MCP_TOKEN"}});return v}
function servicePath(raw){const k=text(raw,80);const p=SERVICES[k];if(!p)throw Object.assign(new Error("INVALID_PKULAW_SERVICE"),{status:400,details:{allowed:Object.keys(SERVICES)}});return{k,path:p}}
function trimValue(v,depth=0){if(depth>7)return null;if(Array.isArray(v))return v.slice(0,80).map(x=>trimValue(x,depth+1));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v).slice(0,120))o[text(k,120)]=trimValue(x,depth+1);return o}if(typeof v==="string")return text(v,12000);if(typeof v==="number"||typeof v==="boolean"||v===null)return v;return text(v,12000)}
function safeArgs(v){const out=trimValue(v??{});const raw=JSON.stringify(out);if(new TextEncoder().encode(raw).length>MAX_ARGS_BYTES)throw Object.assign(new Error("ARGUMENTS_TOO_LARGE"),{status:413});return out}
function parseSse(raw){const out=[];for(const line of raw.split(/\r?\n/)){if(!line.startsWith("data:"))continue;const s=line.slice(5).trim();if(!s||s==="[DONE]")continue;try{out.push(JSON.parse(s))}catch{}}return out.at(-1)||null}
async function request(env,path,payload,sessionId){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const h={authorization:`Bearer ${token(env)}`,"content-type":"application/json",accept:"application/json, text/event-stream"};if(sessionId)h["mcp-session-id"]=sessionId;const r=await fetch(`${BASE}${path}`,{method:"POST",headers:h,body:JSON.stringify(payload),signal:c.signal});const raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});const ct=String(r.headers.get("content-type")||"").toLowerCase();let body=null;if(raw){if(ct.includes("text/event-stream"))body=parseSse(raw);else{try{body=JSON.parse(raw)}catch{body=null}}}if(!r.ok)throw Object.assign(new Error("UPSTREAM_HTTP_ERROR"),{status:502,details:{http_status:r.status,error:text(body?.error?.message||body?.message||body?.detail||raw,1000)}});if(body?.error)throw Object.assign(new Error("UPSTREAM_MCP_ERROR"),{status:502,details:{code:body.error.code??null,message:text(body.error.message,1000)}});return{body,sessionId:r.headers.get("mcp-session-id")||sessionId||null,http_status:r.status,content_type:ct}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
async function openSession(env,path){const init=await request(env,path,{jsonrpc:"2.0",id:1,method:"initialize",params:{protocolVersion:"2025-03-26",capabilities:{},clientInfo:{name:"three-center-intelligence",version:"2026.08"}}});const sessionId=init.sessionId;try{await request(env,path,{jsonrpc:"2.0",method:"notifications/initialized",params:{}},sessionId)}catch(e){if(String(e?.message||"")!=="UPSTREAM_HTTP_ERROR")throw e}return{sessionId,protocolVersion:init.body?.result?.protocolVersion||null,serverInfo:trimValue(init.body?.result?.serverInfo||null)}}
async function listTools(env,path,sessionId){const x=await request(env,path,{jsonrpc:"2.0",id:2,method:"tools/list",params:{}},sessionId);const tools=Array.isArray(x.body?.result?.tools)?x.body.result.tools:[];return tools.slice(0,100).map(t=>({name:text(t?.name,200),description:text(t?.description,3000),inputSchema:trimValue(t?.inputSchema||null)})).filter(t=>t.name)}
async function pkulaw(operation,args,env){const svc=servicePath(required(args,"service"));const opened=await openSession(env,svc.path);const tools=await listTools(env,svc.path,opened.sessionId);const legacy=!env?.PKULAW_MCP_TOKEN&&!env?.PKULAW_API_TOKEN&&Boolean(env?.BROWSERFABRIC_API_KEY);if(operation==="mcp_tools")return{provider:"pkulaw",operation,integration:"official-mcp-streamable-http",service:svc.k,protocol_version:opened.protocolVersion,server_info:opened.serverInfo,tool_count:tools.length,tools,legacy_secret_alias_used:legacy};if(operation==="mcp_call"){const name=text(required(args,"tool"),200);if(!tools.some(t=>t.name===name))throw Object.assign(new Error("POLICY_DENIED_UNADVERTISED_TOOL"),{status:403,details:{service:svc.k,tool:name,advertised:tools.map(t=>t.name)}});const x=await request(env,svc.path,{jsonrpc:"2.0",id:3,method:"tools/call",params:{name,arguments:safeArgs(args?.arguments||{})}},opened.sessionId);return{provider:"pkulaw",operation,integration:"official-mcp-streamable-http",service:svc.k,tool:name,data:trimValue(x.body?.result??x.body),legacy_secret_alias_used:legacy}}throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403})}
export const OPERATIONS={pkulaw:["mcp_tools","mcp_call"]};
export async function runAdapter(provider,operation,args,env){if(provider!=="pkulaw"||!OPERATIONS.pkulaw.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});return pkulaw(operation,args||{},env)}
