const MAX_BYTES=1500000,PKULAW_TIMEOUT_MS=60000,GOOGLE_TIMEOUT_MS=18000,PAGESPEED_TIMEOUT_MS=35000,MAX_ARGS_BYTES=24000;
const PKULAW_BASE="https://apim-gateway.pkulaw.com/";
const PKULAW_SERVICES={law_recognition:"law_recognition","mcp-fatiao":"mcp-fatiao","mcp-law":"mcp-law","mcp-law-search-service":"mcp-law-search-service","add-doc-link":"add-doc-link",pku_citation_validator:"pku_citation_validator",case_number_recognition:"case_number_recognition","mcp-case":"mcp-case","mcp-law-agg":"mcp-law-agg/mcp","mcp-case-search-service":"mcp-case-search-service"};
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(n,a,b,d)=>{n=Number(n);return Number.isFinite(n)?Math.max(a,Math.min(b,Math.trunc(n))):d};
const required=(o,k)=>{const v=o?.[k];if(v===undefined||v===null||String(v).trim()==="")throw Object.assign(new Error(`ARG_REQUIRED:${k}`),{status:400});return v};
function trimValue(v,depth=0){if(depth>7)return null;if(Array.isArray(v))return v.slice(0,80).map(x=>trimValue(x,depth+1));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v).slice(0,120))o[text(k,120)]=trimValue(x,depth+1);return o}if(typeof v==="string")return text(v,12000);if(typeof v==="number"||typeof v==="boolean"||v===null)return v;return text(v,12000)}
function safeArgs(v){const out=trimValue(v??{}),raw=JSON.stringify(out);if(new TextEncoder().encode(raw).length>MAX_ARGS_BYTES)throw Object.assign(new Error("ARGUMENTS_TOO_LARGE"),{status:413});return out}
function parseSse(raw){const out=[];for(const line of raw.split(/\r?\n/)){if(!line.startsWith("data:"))continue;const s=line.slice(5).trim();if(!s||s==="[DONE]")continue;try{out.push(JSON.parse(s))}catch{}}return out.at(-1)||null}
function pkulawToken(env){const v=String(env?.PKULAW_MCP_TOKEN||env?.PKULAW_API_TOKEN||env?.BROWSERFABRIC_API_KEY||"").trim();if(!v)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{missing:"PKULAW_MCP_TOKEN"}});return v}
function pkulawService(raw){const key=text(raw,80),path=PKULAW_SERVICES[key];if(!path)throw Object.assign(new Error("INVALID_PKULAW_SERVICE"),{status:400,details:{allowed:Object.keys(PKULAW_SERVICES)}});return{key,path}}
async function readBody(r){const raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});const ct=String(r.headers.get("content-type")||"").toLowerCase();let body=null;if(raw){if(ct.includes("text/event-stream"))body=parseSse(raw);else try{body=JSON.parse(raw)}catch{body=null}}return{raw,ct,body}}
async function pkulawRpc(env,path,method,params,id){const c=new AbortController(),timer=setTimeout(()=>c.abort(),PKULAW_TIMEOUT_MS);try{const payload={jsonrpc:"2.0",id,method,params:params||{}};const r=await fetch(`${PKULAW_BASE}${path}`,{method:"POST",headers:{authorization:`Bearer ${pkulawToken(env)}`,"content-type":"application/json",accept:"application/json, text/event-stream"},body:JSON.stringify(payload),signal:c.signal});const {raw,ct,body}=await readBody(r);if(!r.ok){const msg=text(body?.error?.message||body?.message||body?.description||body?.detail||raw,1000),auth=r.status===401||r.status===403;throw Object.assign(new Error(auth?"PKULAW_SERVICE_AUTH_REQUIRED":"UPSTREAM_HTTP_ERROR"),{status:auth?503:502,details:{http_status:r.status,error:msg}})}if(body?.error)throw Object.assign(new Error("UPSTREAM_MCP_ERROR"),{status:502,details:{code:body.error.code??null,message:text(body.error.message,1000)}});return{body,content_type:ct,http_status:r.status}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
async function listPkulawTools(env,path){const x=await pkulawRpc(env,path,"tools/list",{},1),tools=Array.isArray(x.body?.result?.tools)?x.body.result.tools:[];return tools.slice(0,100).map(t=>({name:text(t?.name,200),description:text(t?.description,3000),inputSchema:trimValue(t?.inputSchema||null)})).filter(t=>t.name)}
async function runPkulaw(operation,args,env){const svc=pkulawService(required(args,"service")),tools=await listPkulawTools(env,svc.path),legacy=!env?.PKULAW_MCP_TOKEN&&!env?.PKULAW_API_TOKEN&&Boolean(env?.BROWSERFABRIC_API_KEY);if(operation==="mcp_tools")return{provider:"pkulaw",operation,integration:"official-cli-direct-jsonrpc",service:svc.key,tool_count:tools.length,tools,legacy_secret_alias_used:legacy};const name=text(required(args,"tool"),200);if(!tools.some(t=>t.name===name))throw Object.assign(new Error("POLICY_DENIED_UNADVERTISED_TOOL"),{status:403,details:{service:svc.key,tool:name,advertised:tools.map(t=>t.name)}});const x=await pkulawRpc(env,svc.path,"tools/call",{name,arguments:safeArgs(args?.arguments||{})},2);return{provider:"pkulaw",operation,integration:"official-cli-direct-jsonrpc",service:svc.key,tool:name,data:trimValue(x.body?.result??x.body),legacy_secret_alias_used:legacy}}
function googleKey(env,provider){const map={google_civic:"GOOGLE_CIVIC_API_KEY",google_knowledge_graph:"GOOGLE_KNOWLEDGE_GRAPH_API_KEY",google_pagespeed:"GOOGLE_PAGESPEED_API_KEY"};return String(env?.[map[provider]]||env?.GOOGLE_API_KEY||"").trim()}
function safePublicUrl(v){let u;try{u=new URL(String(v))}catch{throw Object.assign(new Error("INVALID_URL"),{status:400})}if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw Object.assign(new Error("INVALID_URL"),{status:400});if(["localhost","127.0.0.1","::1"].includes(u.hostname)||u.hostname.endsWith(".local"))throw Object.assign(new Error("POLICY_DENIED_URL"),{status:403});return u.toString()}
async function googleJson(url,init={},timeoutMs=GOOGLE_TIMEOUT_MS){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{...init,headers:{accept:"application/json",...(init.headers||{})},signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let body;try{body=raw?JSON.parse(raw):null}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}if(!r.ok){const message=text(body?.error?.message||body?.error||raw,1000),blocked=r.status===403&&/\bblocked\b/i.test(message);throw Object.assign(new Error(blocked?"GOOGLE_API_KEY_SERVICE_BLOCKED":"UPSTREAM_HTTP_ERROR"),{status:blocked?503:502,details:{http_status:r.status,error:message}})}return body}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(timer)}}
function keyed(base,env,provider,optional=false){const u=new URL(base),key=googleKey(env,provider);if(key)u.searchParams.set("key",key);else if(!optional)throw Object.assign(new Error("UPSTREAM_AUTH_FAILED"),{status:503,details:{provider}});return u}
async function runGoogle(provider,operation,args,env){if(provider==="google_civic"){const base=operation==="elections"?"https://www.googleapis.com/civicinfo/v2/elections":operation==="divisions"?"https://www.googleapis.com/civicinfo/v2/divisions":"https://www.googleapis.com/civicinfo/v2/voterinfo",u=keyed(base,env,provider);if(operation==="divisions")u.searchParams.set("query",text(required(args,"query"),200));if(operation==="voter_info"){u.searchParams.set("address",text(required(args,"address"),300));if(args.election_id)u.searchParams.set("electionId",text(args.election_id,40));if(args.official_only===true)u.searchParams.set("officialOnly","true")}const body=await googleJson(u);return operation==="voter_info"?{provider,operation,data:body}:{provider,operation,items:operation==="elections"?body?.elections||[]:body?.results||[]}}
  if(provider==="google_knowledge_graph"){const u=keyed("https://kgsearch.googleapis.com/v1/entities:search",env,provider);u.searchParams.set("query",text(required(args,"query"),300));u.searchParams.set("limit",String(clamp(args.limit,1,500,20)));u.searchParams.set("indent","false");if(args.languages)u.searchParams.set("languages",Array.isArray(args.languages)?args.languages.map(x=>text(x,12)).filter(Boolean).join(","):text(args.languages,80));if(args.types)for(const type of (Array.isArray(args.types)?args.types:[args.types]).slice(0,10))u.searchParams.append("types",text(type,80));if(args.prefix===true)u.searchParams.set("prefix","true");const body=await googleJson(u);return{provider,operation,items:body?.itemListElement||[]}}
  if(provider==="google_pagespeed"){const u=keyed("https://www.googleapis.com/pagespeedonline/v5/runPagespeed",env,provider,true);u.searchParams.set("url",safePublicUrl(required(args,"url")));if(["mobile","desktop"].includes(String(args.strategy||"").toLowerCase()))u.searchParams.set("strategy",String(args.strategy).toLowerCase());for(const category of (Array.isArray(args.categories)?args.categories:[args.category]).filter(Boolean).slice(0,5)){const c=String(category).toUpperCase();if(["PERFORMANCE","ACCESSIBILITY","BEST_PRACTICES","SEO"].includes(c))u.searchParams.append("category",c)}if(args.locale)u.searchParams.set("locale",text(args.locale,20));let body;try{body=await googleJson(u,{},PAGESPEED_TIMEOUT_MS)}catch(e){if(String(e?.message||"")!=="GOOGLE_API_KEY_SERVICE_BLOCKED"||!u.searchParams.has("key"))throw e;u.searchParams.delete("key");body=await googleJson(u,{},PAGESPEED_TIMEOUT_MS)}return{provider,operation,data:{id:body?.id||null,analysisUTCTimestamp:body?.analysisUTCTimestamp||null,lighthouseResult:body?.lighthouseResult||null,loadingExperience:body?.loadingExperience||null,originLoadingExperience:body?.originLoadingExperience||null},timeout_ms:PAGESPEED_TIMEOUT_MS}}
  throw Object.assign(new Error("ADAPTER_NOT_IMPLEMENTED"),{status:501})}
export const OPERATIONS={pkulaw:["mcp_tools","mcp_call"],google_civic:["elections","divisions","voter_info"],google_knowledge_graph:["search"],google_pagespeed:["analyze"]};
export async function runAdapter(provider,operation,args={},env){if(!OPERATIONS[provider]?.includes(operation))throw Object.assign(new Error("ADAPTER_OPERATION_NOT_APPROVED"),{status:403});return provider==="pkulaw"?runPkulaw(operation,args,env):runGoogle(provider,operation,args,env)}
