const MAX_BYTES=1800000,TIMEOUT_MS=18000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function req(v,name,n=300){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);return s}
function tok(v,name,re=/^[A-Za-z0-9_.:@,+-]+$/,n=180){const s=req(v,name,n);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function secret(env,name){const s=text(env?.[name],300);if(!s)err("UPSTREAM_AUTH_FAILED",503,{missing:name});return s}
function isoDate(v,name){const s=text(v,20);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
function arr(v,n=20){return(Array.isArray(v)?v:String(v??"").split(",")).map(x=>String(x).trim()).filter(Boolean).slice(0,n)}
function redact(x){if(Array.isArray(x))return x.map(redact);if(x&&typeof x==="object"){const sensitive=new Set(["api_key","apikey","registrationkey","userid","user_id","key"]),name=String(x.ParameterName??x.parameter_name??"").toLowerCase(),pairSecret=sensitive.has(name);const o={};for(const[k,v]of Object.entries(x)){const lk=k.toLowerCase();if((sensitive.has(lk)&&typeof v==="string")||(pairSecret&&["parametervalue","parameter_value","value"].includes(lk)))o[k]="[redacted]";else o[k]=redact(v)}return o}return x}
async function readBounded(r){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>MAX_BYTES)err("UPSTREAM_RESPONSE_TOO_LARGE",502);const reader=r.body?.getReader?.();if(!reader)return"";const chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:"application/json",...(init.headers||{})}}),raw=await readBounded(r);let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(typeof body==="string"?body:body?.error?.message||body?.message||raw,400)});return redact(body)}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}

function censusDataset(v){const s=req(v,"dataset",160).replace(/^\/+|\/+$/g,"");const parts=s.split("/");if(parts.length>5||parts.some(x=>!/^[A-Za-z0-9_-]+$/.test(x)))err("INVALID_CENSUS_DATASET");return parts.join("/")}
async function census(operation,args,env){if(operation!=="data")err("ADAPTER_OPERATION_NOT_APPROVED",403);const y=tok(args?.year,"year",/^\d{4}$/,4),dataset=censusDataset(args?.dataset),vars=arr(args?.get||args?.variables,25);if(!vars.length)err("ARG_REQUIRED:variables");if(vars.some(x=>!/^[A-Za-z0-9_().-]+$/.test(x)))err("INVALID_CENSUS_VARIABLE");const u=new URL(`https://api.census.gov/data/${y}/${dataset}`);u.searchParams.set("get",vars.join(","));const geoFor=text(args?.for,200),geoIn=text(args?.in,200),ucgid=text(args?.ucgid,200);for(const[name,val]of [["for",geoFor],["in",geoIn],["ucgid",ucgid]])if(val){if(!/^[A-Za-z0-9_*: .,+-]+$/.test(val))err(`INVALID_CENSUS_${name.toUpperCase()}`);u.searchParams.set(name,val)}u.searchParams.set("key",secret(env,"CENSUS_API_KEY"));const body=await request(u);return{provider:"us_census_api",operation,year:y,dataset,columns:Array.isArray(body?.[0])?body[0]:[],items:Array.isArray(body)?body.slice(1):[]}}

async function bls(operation,args,env){if(operation!=="timeseries")err("ADAPTER_OPERATION_NOT_APPROVED",403);const ids=arr(args?.series_ids||args?.series_id,20).map(x=>tok(x,"series_id",/^[A-Z0-9_#-]+$/,80));if(!ids.length)err("ARG_REQUIRED:series_ids");const sy=Number(args?.start_year),ey=Number(args?.end_year);if(!Number.isInteger(sy)||!Number.isInteger(ey)||sy<1913||ey>2100||sy>ey||ey-sy>19)err("INVALID_BLS_YEAR_RANGE");const payload={seriesid:ids,startyear:String(sy),endyear:String(ey),registrationkey:secret(env,"BLS_API_KEY"),calculations:Boolean(args?.calculations),annualaverage:Boolean(args?.annual_average)};const body=await request("https://api.bls.gov/publicAPI/v2/timeseries/data/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"us_bls_api",operation,status:body?.status||null,message:body?.message||[],items:body?.Results?.series||[]}}

const BEA_DATASETS=new Set(["NIPA","NIUnderlyingDetail","FixedAssets","ITA","IIP","IntlServTrade","IntlServSTA","GDPByIndustry","UnderlyingGDPbyIndustry","InputOutput","Regional","MNE"]);
function beaBase(env,method){const u=new URL("https://apps.bea.gov/api/data/");u.searchParams.set("UserID",secret(env,"BEA_API_KEY"));u.searchParams.set("method",method);u.searchParams.set("ResultFormat","JSON");return u}
function beaDataset(v){const s=req(v,"dataset",80);if(!BEA_DATASETS.has(s))err("INVALID_BEA_DATASET",400,{allowed:[...BEA_DATASETS]});return s}
async function bea(operation,args,env){if(operation==="datasets"){const body=await request(beaBase(env,"GETDATASETLIST"));return{provider:"us_bea_api",operation,data:body}}
 const dataset=beaDataset(args?.dataset);if(operation==="parameters"){const u=beaBase(env,"GETPARAMETERLIST");u.searchParams.set("DatasetName",dataset);return{provider:"us_bea_api",operation,dataset,data:await request(u)}}
 if(operation==="data"){const u=beaBase(env,"GETDATA");u.searchParams.set("DatasetName",dataset);const entries=args?.parameters&&typeof args.parameters==="object"&&!Array.isArray(args.parameters)?Object.entries(args.parameters).slice(0,20):[];if(!entries.length)err("ARG_REQUIRED:parameters");for(const[k,v]of entries){if(!/^[A-Za-z][A-Za-z0-9_]{0,60}$/.test(k))err("INVALID_BEA_PARAMETER_NAME");const vals=arr(v,30);if(!vals.length||vals.some(x=>!/^[A-Za-z0-9_.:@,+* -]+$/.test(x)))err("INVALID_BEA_PARAMETER_VALUE");u.searchParams.set(k,vals.join(","))}return{provider:"us_bea_api",operation,dataset,data:await request(u)}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const NASS_FIELDS=new Set(["source_desc","sector_desc","group_desc","commodity_desc","statisticcat_desc","util_practice_desc","prodn_practice_desc","class_desc","short_desc","domain_desc","domaincat_desc","agg_level_desc","state_alpha","state_name","county_name","region_desc","zip_5","watershed_code","year","freq_desc","reference_period_desc","week_ending","load_time","unit_desc"]);
function nassField(k){const m=String(k).match(/^([a-z0-9_]+?)(__(?:GE|LE|GT|LT|NE|LIKE|NOT_LIKE))?$/i);if(!m||!NASS_FIELDS.has(m[1]))err("INVALID_NASS_FIELD");return m[1]+(m[2]||"")}
async function nass(operation,args,env){if(operation!=="query")err("ADAPTER_OPERATION_NOT_APPROVED",403);const q=args?.query&&typeof args.query==="object"&&!Array.isArray(args.query)?Object.entries(args.query).slice(0,25):[];if(!q.length)err("ARG_REQUIRED:query");const u=new URL("https://quickstats.nass.usda.gov/api/api_GET/");u.searchParams.set("key",secret(env,"USDA_NASS_API_KEY"));u.searchParams.set("format","JSON");for(const[k,v]of q){const field=nassField(k),vals=arr(v,20);if(!vals.length)continue;for(const value of vals){const s=text(value,180);if(!/^[A-Za-z0-9_.,:'()/%+*#& -]+$/.test(s))err("INVALID_NASS_VALUE");u.searchParams.append(field,s)}}const body=await request(u);return{provider:"usda_nass_quickstats",operation,items:Array.isArray(body?.data)?body.data:[],error:body?.error||null}}

function reporterText(v,n=300){const s=text(v,n);if(!/^[\p{L}\p{N}\s.,'"()/_:+*#&-]*$/u.test(s))err("INVALID_REPORTER_TEXT");return s}
async function reporter(operation,args){if(operation==="projects"){const criteria={};const q=reporterText(args?.query,300);if(q)criteria.advanced_text_search={operator:"and",search_field:"all",search_text:q};const fy=arr(args?.fiscal_years,10).map(Number).filter(Number.isInteger);if(fy.length)criteria.fiscal_years=fy;for(const[k,max]of [["org_names",10],["org_states",10],["org_countries",10],["agencies",10],["activity_codes",20],["project_nums",20]]){const vals=arr(args?.[k],max).map(x=>reporterText(x,120));if(vals.length)criteria[k]=vals}if(!Object.keys(criteria).length)err("ARG_REQUIRED:criteria");const payload={criteria,include_fields:["ApplId","ProjectNum","CoreProjectNum","ProjectTitle","AbstractText","OrgName","OrgCity","OrgState","OrgCountry","PrincipalInvestigators","AgencyIcAdmin","FiscalYear","AwardAmount","ProjectStartDate","ProjectEndDate","AwardNoticeDate","ProjectDetailUrl"],offset:clamp(args?.offset,0,14999,0),limit:clamp(args?.limit,1,100,25),sort_field:"award_notice_date",sort_order:"desc"};const body=await request("https://api.reporter.nih.gov/v2/projects/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"nih_reporter",operation,meta:body?.meta||null,items:body?.results||[]}}
 if(operation==="publications"){const criteria={};const pmids=arr(args?.pmids,50).map(Number).filter(Number.isInteger);if(pmids.length)criteria.pmids=pmids;const appl=arr(args?.appl_ids,50).map(Number).filter(Number.isInteger);if(appl.length)criteria.appl_ids=appl;const cores=arr(args?.core_project_nums,50).map(x=>reporterText(x,80));if(cores.length)criteria.core_project_nums=cores;if(!Object.keys(criteria).length)err("ARG_REQUIRED:criteria");const payload={criteria,offset:clamp(args?.offset,0,9999,0),limit:clamp(args?.limit,1,100,25)};const body=await request("https://api.reporter.nih.gov/v2/publications/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"nih_reporter",operation,meta:body?.meta||null,items:body?.results||[]}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}

function uuid(v){return tok(v,"dataset_id",/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,36)}
async function cms(operation,args){if(operation!=="dataset")err("ADAPTER_OPERATION_NOT_APPROVED",403);const id=uuid(args?.dataset_id),u=new URL(`https://data.cms.gov/data-api/v1/dataset/${id}/data`);u.searchParams.set("size",String(clamp(args?.limit,1,500,50)));u.searchParams.set("offset",String(clamp(args?.offset,0,10000000,0)));const filters=args?.filters&&typeof args.filters==="object"&&!Array.isArray(args.filters)?Object.entries(args.filters).slice(0,8):[];let i=0;for(const[field,spec]of filters){if(!/^[A-Za-z0-9_ -]{1,100}$/.test(field))err("INVALID_CMS_FILTER_FIELD");i++;const obj=spec&&typeof spec==="object"&&!Array.isArray(spec)?spec:{value:spec,operator:"="},op=String(obj.operator||"=").toUpperCase();if(!["=","CONTAINS"].includes(op))err("INVALID_CMS_FILTER_OPERATOR");const val=text(obj.value,180);u.searchParams.set(`filter[filter-${i}][condition][path]`,field);u.searchParams.set(`filter[filter-${i}][condition][operator]`,op);u.searchParams.set(`filter[filter-${i}][condition][value]`,val)}const body=await request(u);return{provider:"cms_data",operation,dataset_id:id,items:Array.isArray(body)?body:body?.data||body}}

const AWARD_CODES=new Set(["02","03","04","05","06","07","08","09","10","11","A","B","C","D","IDV_A","IDV_B","IDV_B_A","IDV_B_B","IDV_B_C","IDV_C","IDV_D","IDV_E"]);
function spendingFilters(args){const f={};if(args?.start_date||args?.end_date){const start=isoDate(args?.start_date,"start_date"),end=isoDate(args?.end_date,"end_date");if(start>end)err("INVALID_DATE_RANGE");f.time_period=[{start_date:start,end_date:end}]}const codes=arr(args?.award_type_codes,30).map(x=>x.toUpperCase());if(codes.length){if(codes.some(x=>!AWARD_CODES.has(x)))err("INVALID_AWARD_TYPE_CODE");f.award_type_codes=codes}const kw=arr(args?.keywords,10).map(x=>text(x,100));if(kw.length)f.keywords=kw;const rs=arr(args?.recipient_search_text,10).map(x=>text(x,100));if(rs.length)f.recipient_search_text=rs;const naics=arr(args?.naics,20);if(naics.length){if(naics.some(x=>!/^\d{2,6}$/.test(x)))err("INVALID_NAICS");f.naics_codes={require:naics}}if(!Object.keys(f).length)err("ARG_REQUIRED:filters");return f}
async function spending(operation,args){const filters=spendingFilters(args);if(operation==="award_count"){const body=await request("https://api.usaspending.gov/api/v2/search/spending_by_award_count/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filters,spending_level:"awards"})});return{provider:"usaspending",operation,data:body}}
 if(operation==="awarding_agencies"){const payload={filters,category:"awarding_agency",limit:clamp(args?.limit,1,100,20),page:clamp(args?.page,1,1000,1),spending_level:["transactions","awards"].includes(args?.spending_level)?args.spending_level:"transactions"},body=await request("https://api.usaspending.gov/api/v2/search/spending_by_category/awarding_agency/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{provider:"usaspending",operation,items:body?.results||[],page_metadata:body?.page_metadata||null,messages:body?.messages||[]}}err("ADAPTER_OPERATION_NOT_APPROVED",403)}

const SOURCE_CATALOG=[
 {provider:"us_census_api",role:"population-households-business-trade-construction-geography",auth:"CENSUS_API_KEY"},
 {provider:"us_bls_api",role:"employment-wages-cpi-ppi-productivity-occupations",auth:"BLS_API_KEY"},
 {provider:"us_bea_api",role:"gdp-industry-regional-international-investment",auth:"BEA_API_KEY"},
 {provider:"usda_nass_quickstats",role:"crops-livestock-prices-yield-acreage-production",auth:"USDA_NASS_API_KEY"},
 {provider:"nih_reporter",role:"biomedical-research-grants-projects-publications",auth:"public"},
 {provider:"cms_data",role:"medicare-medicaid-providers-utilization-cost-quality",auth:"public"},
 {provider:"usaspending",role:"contracts-grants-loans-agencies-recipients",auth:"public"}
];

export const OPERATIONS={
 us_census_api:["data"],us_bls_api:["timeseries"],us_bea_api:["datasets","parameters","data"],usda_nass_quickstats:["query"],nih_reporter:["projects","publications"],cms_data:["dataset"],usaspending:["award_count","awarding_agencies"],splus_us_official:["catalog"]
};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403,{provider,operation,allowed:OPERATIONS[provider]||[]});if(provider==="us_census_api")return census(operation,args,env);if(provider==="us_bls_api")return bls(operation,args,env);if(provider==="us_bea_api")return bea(operation,args,env);if(provider==="usda_nass_quickstats")return nass(operation,args,env);if(provider==="nih_reporter")return reporter(operation,args);if(provider==="cms_data")return cms(operation,args);if(provider==="usaspending")return spending(operation,args);if(provider==="splus_us_official")return{provider,operation,items:SOURCE_CATALOG};err("ADAPTER_NOT_IMPLEMENTED",501)}
