const TIMEOUT_MS=18000,MAX_BYTES=1800000;
const text=(v,n=500)=>String(v??"").trim().slice(0,n);
const clamp=(v,min,max,d)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):d};
function err(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
function token(v,name,re=/^[A-Za-z0-9_.:-]+$/,n=160){const s=text(v,n);if(!s)err(`ARG_REQUIRED:${name}`);if(!re.test(s))err(`INVALID_${name.toUpperCase()}`);return s}
async function readBounded(r,maxBytes=MAX_BYTES){const declared=Number(r.headers.get("content-length")||0);if(Number.isFinite(declared)&&declared>maxBytes)err("UPSTREAM_RESPONSE_TOO_LARGE",502);if(!r.body)return"";const reader=r.body.getReader(),chunks=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>maxBytes){await reader.cancel().catch(()=>{});err("UPSTREAM_RESPONSE_TOO_LARGE",502)}chunks.push(value)}}finally{try{reader.releaseLock()}catch{}}const out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}return new TextDecoder().decode(out)}
async function request(url,init={},expect="json"){const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...init,signal:c.signal,headers:{accept:expect==="json"?"application/json":"*/*",...(init.headers||{})}}),raw=await readBounded(r);if(!r.ok)err(r.status===401||r.status===403?"UPSTREAM_AUTH_FAILED":"UPSTREAM_HTTP_ERROR",r.status===401||r.status===403?503:502,{http_status:r.status,message:text(raw,400)});if(expect==="text")return raw;try{return raw?JSON.parse(raw):null}catch{err("UPSTREAM_BAD_JSON",502)}}catch(e){if(e?.name==="AbortError")err("UPSTREAM_TIMEOUT",504);throw e}finally{clearTimeout(timer)}}
function emailParam(env){const e=text(env?.CROSSREF_MAILTO||env?.CONTACT_EMAIL,200);return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)?e:""}
async function knowledge(operation,args,env){
 if(operation==="crossref_search"){const u=new URL("https://api.crossref.org/works");u.searchParams.set("query",text(args?.query,500));u.searchParams.set("rows",String(clamp(args?.limit,1,50,10)));const m=emailParam(env);if(m)u.searchParams.set("mailto",m);const b=await request(u);return{provider:"splus_knowledge",operation,source:"Crossref",total:b?.message?.["total-results"]??null,items:b?.message?.items||[]}}
 if(operation==="datacite_search"){const u=new URL("https://api.datacite.org/dois");u.searchParams.set("query",text(args?.query,500));u.searchParams.set("page[size]",String(clamp(args?.limit,1,50,10)));u.searchParams.set("detail","true");const b=await request(u);return{provider:"splus_knowledge",operation,source:"DataCite",items:b?.data||[],meta:b?.meta||null}}
 if(operation==="europepmc_search"||operation==="medical_case_search"){let q=text(args?.query,500);if(!q)err("ARG_REQUIRED:query");if(operation==="medical_case_search")q=`(${q}) AND ("case report" OR "case series")`;const u=new URL("https://www.ebi.ac.uk/europepmc/webservices/rest/search");u.searchParams.set("query",q);u.searchParams.set("format","json");u.searchParams.set("pageSize",String(clamp(args?.limit,1,50,10)));u.searchParams.set("resultType",args?.core===true?"core":"lite");const b=await request(u);return{provider:"splus_knowledge",operation,source:"Europe PMC",total:b?.hitCount??null,items:b?.resultList?.result||[]}}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}
const NCBI_BASE="https://eutils.ncbi.nlm.nih.gov/entrez/eutils";
function ncbiDb(v){return token(v||"pubmed","db",/^[a-z0-9_-]+$/,40)}
function ncbiAuth(u,env){const k=text(env?.NCBI_API_KEY,80);if(k)u.searchParams.set("api_key",k);const tool=text(env?.NCBI_TOOL,80);if(tool)u.searchParams.set("tool",tool);const email=text(env?.NCBI_EMAIL||env?.CONTACT_EMAIL,200);if(email)u.searchParams.set("email",email)}
async function biomed(operation,args,env){
 if(operation==="ncbi_search"){const u=new URL(`${NCBI_BASE}/esearch.fcgi`);u.searchParams.set("db",ncbiDb(args?.db));u.searchParams.set("term",text(args?.query,600));u.searchParams.set("retmode","json");u.searchParams.set("retmax",String(clamp(args?.limit,1,100,20)));ncbiAuth(u,env);const b=await request(u);return{provider:"splus_biomed",operation,source:"NCBI Entrez",result:b?.esearchresult||b}}
 if(operation==="ncbi_summary"){const ids=(Array.isArray(args?.ids)?args.ids:String(args?.ids||"").split(",")).map(x=>String(x).trim()).filter(x=>/^\d+$/.test(x)).slice(0,50);if(!ids.length)err("ARG_REQUIRED:ids");const u=new URL(`${NCBI_BASE}/esummary.fcgi`);u.searchParams.set("db",ncbiDb(args?.db));u.searchParams.set("id",ids.join(","));u.searchParams.set("retmode","json");ncbiAuth(u,env);const b=await request(u);return{provider:"splus_biomed",operation,source:"NCBI Entrez",data:b}}
 if(operation==="who_indicators"){const u=new URL("https://ghoapi.azureedge.net/api/Indicator");const q=text(args?.query,120).replace(/'/g,"''");if(q)u.searchParams.set("$filter",`contains(IndicatorName,'${q}')`);u.searchParams.set("$top",String(clamp(args?.limit,1,100,20)));const b=await request(u);return{provider:"splus_biomed",operation,source:"WHO GHO",items:b?.value||[]}}
 if(operation==="who_indicator_data"){const code=token(args?.code,"code",/^[A-Za-z0-9_]+$/,100),u=new URL(`https://ghoapi.azureedge.net/api/${code}`);const filters=[];if(args?.country)filters.push(`SpatialDim eq '${token(args.country,"country",/^[A-Z0-9_-]+$/,20)}'`);if(args?.year){const y=clamp(args.year,1900,2100,0);if(!y)err("INVALID_YEAR");filters.push(`TimeDim eq ${y}`)}if(filters.length)u.searchParams.set("$filter",filters.join(" and "));u.searchParams.set("$top",String(clamp(args?.limit,1,200,50)));const b=await request(u);return{provider:"splus_biomed",operation,source:"WHO GHO",items:b?.value||[]}}
 if(operation==="ebi_search"){const domain=token(args?.domain||"uniprot","domain",/^[A-Za-z0-9_.-]+$/,80),u=new URL(`https://www.ebi.ac.uk/ebisearch/ws/rest/${domain}`);u.searchParams.set("query",text(args?.query,500));u.searchParams.set("format","json");u.searchParams.set("size",String(clamp(args?.limit,1,100,20)));u.searchParams.set("start",String(clamp(args?.start,0,1000000,0)));const b=await request(u);return{provider:"splus_biomed",operation,source:"EMBL-EBI",domain,data:b}}
 if(operation==="openfda"){const endpoints={drug_event:"drug/event",drug_label:"drug/label",drug_enforcement:"drug/enforcement",device_event:"device/event",device_enforcement:"device/enforcement",food_enforcement:"food/enforcement"};const ep=endpoints[String(args?.dataset||"drug_event")];if(!ep)err("INVALID_DATASET",400,{allowed:Object.keys(endpoints)});const u=new URL(`https://api.fda.gov/${ep}.json`),k=text(env?.OPENFDA_API_KEY,80);if(k)u.searchParams.set("api_key",k);if(args?.search)u.searchParams.set("search",text(args.search,700));u.searchParams.set("limit",String(clamp(args?.limit,1,100,10)));if(args?.skip)u.searchParams.set("skip",String(clamp(args.skip,0,25000,0)));const b=await request(u);return{provider:"splus_biomed",operation,source:"openFDA",dataset:args?.dataset||"drug_event",meta:b?.meta||null,items:b?.results||[]}}
 if(operation==="medical_models")return{provider:"splus_biomed",operation,source:"curated-medical-model-registry",items:[
  {id:"google/medgemma-1.5-4b-it",publisher:"Google",priority:"S+",modalities:["text","3D CT/MRI","whole-slide pathology","longitudinal imaging"],access:"gated-terms-open-weights"},
  {id:"google/medgemma-4b-it",publisher:"Google",priority:"S",modalities:["text","medical-images"],access:"gated-terms-open-weights"},
  {id:"google/medgemma-27b-it",publisher:"Google",priority:"S",modalities:["text","medical-images"],access:"gated-terms-open-weights"},
  {id:"google/medgemma-27b-text-it",publisher:"Google",priority:"S",modalities:["text"],access:"gated-terms-open-weights"}],
  note:"Model metadata only. Do not treat model output as a medical diagnosis or as a substitute for clinical evaluation."}
 if(operation==="clinical_data_registry")return{provider:"splus_biomed",operation,items:[
  {id:"mimic_iv",source:"PhysioNet/MIT-LCP",priority:"S+",access:"credentialed+training+DUA",status:"metadata-only-until-authorized"},
  {id:"mimic_cxr",source:"PhysioNet/MIT-LCP",priority:"S+",access:"credentialed+training+DUA",status:"metadata-only-until-authorized"},
  {id:"eicu_crd",source:"PhysioNet",priority:"S",access:"controlled-by-current-release-terms",status:"metadata-only-until-authorized"}]}
 err("ADAPTER_OPERATION_NOT_APPROVED",403)
}
export const OPERATIONS={
 splus_knowledge:["crossref_search","datacite_search","europepmc_search","medical_case_search"],
 splus_biomed:["ncbi_search","ncbi_summary","who_indicators","who_indicator_data","ebi_search","openfda","medical_models","clinical_data_registry"]
};
export async function runAdapter(provider,operation,args={},env={}){if(!OPERATIONS[provider]?.includes(operation))err("ADAPTER_OPERATION_NOT_APPROVED",403);if(provider==="splus_knowledge")return knowledge(operation,args,env);if(provider==="splus_biomed")return biomed(operation,args,env);err("ADAPTER_NOT_IMPLEMENTED",501)}