export const CATALOG_VERSION="2026-08-15.6";
export const EXCLUDED_PROVIDERS=["datacommons","faostat","agt_stock","baichuan","taobao"];

export const CATALOG={
  exa:{category:"search",access:"key",secrets:["EXA_API_KEY"],adapter:"catalog-only"},
  tavily:{category:"search",access:"key",secrets:["TAVILY_API_KEY"],adapter:"tavily.search"},
  serpapi:{category:"search",access:"key",secrets:["SERPAPI_API_KEY"],adapter:"serpapi.search"},
  baidu_ai_search:{category:"search",access:"key",secrets:["BAIDU_API_KEY"],adapter:"catalog-only"},
  jina_reader:{category:"reader",access:"optional-key",secrets:["JINA_API_KEY"],adapter:"catalog-only"},
  firecrawl:{category:"reader",access:"key",secrets:["FIRECRAWL_API_KEY"],adapter:"catalog-only"},
  browserless:{category:"browser",access:"key",secrets:["BROWSERLESS_TOKEN"],adapter:"catalog-only"},
  bigquery:{category:"google-data",access:"key",secret_groups:[["GOOGLE_CLOUD_CREDENTIALS"],["GOOGLE_API_KEY"]],adapter:"catalog-only"},
  earthengine:{category:"google-data",access:"key",secrets:["GOOGLE_CLOUD_CREDENTIALS"],adapter:"catalog-only"},
  baostock:{category:"finance-cn",access:"external-runtime",adapter:"catalog-only"},
  tushare:{category:"finance-cn",access:"key",secrets:["TUSHARE_TOKEN"],adapter:"catalog-only"},
  akshare:{category:"finance-cn",access:"external-runtime",adapter:"catalog-only"},
  alpha_vantage:{category:"finance",access:"key",secrets:["ALPHAVANTAGE_API_KEY"],adapter:"alpha_vantage.daily"},
  eodhd:{category:"finance",access:"key",secrets:["EODHD_API_KEY"],adapter:"catalog-only"},
  alphafeed:{category:"finance",access:"key",secrets:["ALPHAFEED_API_KEY"],adapter:"catalog-only"},
  fred:{category:"macro",access:"key",secrets:["FRED_API_KEY"],adapter:"fred.series_observations"},
  worldbank:{category:"macro",access:"public",adapter:"worldbank.indicator"},
  imf:{category:"macro",access:"public",adapter:"catalog-only"},
  oecd:{category:"macro",access:"public",adapter:"oecd.sdmx_data"},
  bis:{category:"macro",access:"public",adapter:"catalog-only"},
  wto:{category:"trade",access:"public",adapter:"catalog-only"},
  eia:{category:"energy",access:"key",secrets:["EIA_API_KEY"],adapter:"eia.seriesid"},
  adb:{category:"macro",access:"public",adapter:"catalog-only"},
  un_comtrade:{category:"trade",access:"optional-key",secrets:["UN_COMTRADE_API_KEY"],adapter:"catalog-only"},
  qweather:{category:"weather",access:"key",secret_groups:[["QWEATHER_JWT"],["QWEATHER_API_KEY"]],adapter:"catalog-only"},
  xweather:{category:"weather",access:"key",secrets:["XWEATHER_API_KEY"],adapter:"catalog-only"},
  open_meteo:{category:"weather",access:"public",adapter:"open_meteo.forecast"},
  overture_maps:{category:"geo",access:"external-runtime",adapter:"catalog-only"},
  opensky:{category:"aviation",access:"key",secret_groups:[["OPENSKY_CLIENT_ID","OPENSKY_CLIENT_SECRET"]],adapter:"opensky.states"},
  worldpop:{category:"population",access:"public",adapter:"catalog-only"},
  night_lights:{category:"remote-sensing",access:"external-runtime",adapter:"catalog-only"},
  who_gho:{category:"health",access:"public",adapter:"who_gho.indicator"},
  clinicaltrials:{category:"health",access:"public",adapter:"clinicaltrials.studies"},
  biomcp:{category:"biomed-mcp",access:"external-mcp",adapter:"catalog-only"},
  huggingface:{category:"ai-catalog",access:"optional-key",secrets:["HUGGINGFACE_TOKEN"],adapter:"huggingface.models"},
  base:{category:"literature",access:"key",secrets:["BASE_API_KEY"],adapter:"catalog-only"},
  crossref:{category:"literature",access:"public",adapter:"crossref.works"},
  openalex:{category:"literature",access:"key",secrets:["OPENALEX_API_KEY"],adapter:"openalex.works"},
  semantic_scholar:{category:"literature",access:"optional-key",secrets:["SEMANTIC_SCHOLAR_API_KEY"],adapter:"semantic_scholar.paper_search"},
  unpaywall:{category:"literature",access:"config",secrets:["UNPAYWALL_EMAIL"],adapter:"unpaywall.doi"},
  openaire:{category:"literature",access:"public",adapter:"openaire.research_products"},
  worldbank_documents:{category:"documents",access:"public",adapter:"catalog-only"},
  east_asia_econ:{category:"regional-economy",access:"external-source",adapter:"catalog-only"},
  gapup_mcp:{category:"mcp",access:"external-mcp",adapter:"catalog-only"},
  newsapi:{category:"news",access:"key",secrets:["NEWSAPI_KEY"],adapter:"newsapi.everything"},
  gdelt:{category:"news",access:"public",adapter:"catalog-only"},
  wikipedia:{category:"knowledge",access:"public",adapter:"wikipedia.search"},
  wikidata:{category:"knowledge",access:"public",adapter:"wikidata.search_items"},
  llamaparse:{category:"document-parser",access:"key",secrets:["LLAMA_CLOUD_API_KEY"],adapter:"catalog-only"},
  mcp_registry:{category:"registry",access:"public",adapter:"mcp_registry.search"},
  apis_guru:{category:"registry",access:"public",adapter:"apis_guru.providers"},
  pipedream:{category:"integration-registry",access:"key",secrets:["PIPEDREAM_API_KEY"],adapter:"catalog-only"},
  postman:{category:"api-registry",access:"key",secrets:["POSTMAN_API_KEY"],adapter:"catalog-only"},
  smithery:{category:"mcp-registry",access:"optional-key",secrets:["SMITHERY_API_KEY"],adapter:"catalog-only"},
  glama:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  pulsemcp:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  composio:{category:"integration-registry",access:"key",secrets:["COMPOSIO_API_KEY"],adapter:"catalog-only"},
  zapier:{category:"integration-registry",access:"key",secrets:["ZAPIER_API_KEY"],adapter:"catalog-only"},
  mcp_so:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  rapidapi:{category:"api-market",access:"key",secrets:["RAPIDAPI_KEY"],adapter:"catalog-only"},
  docker_mcp:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  google_mcp_registry:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  azure_mcp_registry:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  modelscope_registry:{category:"cn-ai-registry",access:"public",adapter:"catalog-only"},
  tencent_cloud_registry:{category:"cn-cloud-registry",access:"public",adapter:"catalog-only"},
  volcano_registry:{category:"cn-cloud-registry",access:"public",adapter:"catalog-only"},
  alibaba_bailian_registry:{category:"cn-cloud-registry",access:"public",adapter:"catalog-only"},
  baidu_qianfan_registry:{category:"cn-cloud-registry",access:"public",adapter:"catalog-only"},
  huawei_registry:{category:"cn-cloud-registry",access:"public",adapter:"catalog-only"},
  dify_registry:{category:"agent-registry",access:"public",adapter:"catalog-only"},
  nacos_registry:{category:"mcp-registry",access:"public",adapter:"catalog-only"},
  courtlistener:{category:"legal-open-data-us",access:"key",secrets:["COURTLISTENER_API_TOKEN"],adapter:"courtlistener.search",integration:"official-rest-v4",scope:"case-law-pacer-judges-oral-arguments",registration_url:"https://www.courtlistener.com/sign-up/",token_url:"https://www.courtlistener.com/profile/api-token/"},
  repec:{category:"literature-economics",access:"external-source",adapter:"catalog-only",integration:"official-redif+oai-pmh+api",scope:"economics-bibliographic-metadata",endpoint:"https://oai.repec.org/",terms:"non-commercial-by-default-contact-repec-for-commercial-use"},
  agris:{category:"literature-agriculture-global",access:"external-source",adapter:"catalog-only",integration:"official-search+open-metadata-network",scope:"food-agriculture-forestry-fisheries-environment-literature",endpoint:"https://www.fao.org/agris/",terms:"free-search-metadata-license-varies-by-provider"},
  epo_ops:{category:"patent-global",access:"key",secret_groups:[["EPO_OPS_CONSUMER_KEY","EPO_OPS_CONSUMER_SECRET"]],adapter:"catalog-only",integration:"official-rest-oauth",scope:"worldwide-patent-bibliographic-legal-event-fulltext-image-data",registration_url:"https://developers.epo.org/user/register",free_tier:"non-paying-up-to-4GB-per-week"},
  epo_linked_data:{category:"patent-linked-open-data",access:"public",adapter:"catalog-only",integration:"official-linked-data-api",scope:"ep-patent-publications-applications-citations-classifications",endpoint:"https://data.epo.org/linked-data/"},

  dryad:{category:"research-data-repository",access:"public",adapter:"dryad.search",integration:"official-rest-v2",scope:"published-research-datasets",endpoint:"https://datadryad.org/api/v2/search"},
  art_institute_chicago:{category:"museum-open-collection",access:"public",adapter:"art_institute_chicago.search",integration:"official-rest",scope:"artworks-artists-places-publications-articles",endpoint:"https://api.artic.edu/api/v1/"},
  vam_collections:{category:"museum-open-collection-uk",access:"public",adapter:"vam_collections.search",integration:"official-rest-v2",scope:"victoria-and-albert-museum-collections",endpoint:"https://api.vam.ac.uk/v2/objects/search"},
  gbif_species:{category:"biodiversity-taxonomy-knowledge",access:"public",adapter:"gbif_species.search",integration:"official-rest",scope:"species-name-usages-taxonomy",endpoint:"https://api.gbif.org/v1/species/search"},
  pubchem:{category:"chemistry-knowledge",access:"public",adapter:"pubchem.compound_by_name",integration:"official-pug-rest",scope:"compound-properties-identifiers-cross-references",endpoint:"https://pubchem.ncbi.nlm.nih.gov/rest/pug/"},
  chembl:{category:"bioactivity-drug-discovery-knowledge",access:"public",adapter:"chembl.search",integration:"official-rest",scope:"molecules-targets-assays-activities-documents",endpoint:"https://www.ebi.ac.uk/chembl/api/data/"},
  harvard_dataverse:{category:"research-data-repository",access:"public",adapter:"harvard_dataverse.search",integration:"official-dataverse-search-api",scope:"public-datasets-files-dataverses",endpoint:"https://dataverse.harvard.edu/api/search"},
  rcsb_pdb:{category:"structural-biology-knowledge",access:"public",adapter:"rcsb_pdb.search",integration:"official-search-api-v2",scope:"protein-and-nucleic-acid-structures",endpoint:"https://search.rcsb.org/rcsbsearch/v2/query"},
  re3data:{category:"research-data-repository-registry",access:"public",adapter:"catalog-only",integration:"official-rest-v4",scope:"global-research-data-repository-registry",endpoint:"https://www.re3data.org/api/v40/repositories"},
  openfda:{category:"health-regulatory-open-data",access:"optional-key",secret_groups:[["DATA_GOV_API_KEY"],["OPENFDA_API_KEY"]],adapter:"catalog-only",integration:"official-rest",scope:"drugs-devices-food-public-fda-data",registration_url:"https://api.data.gov/signup/",note:"anonymous-usage-supported-with-lower-daily-limit"},
  congress_gov:{category:"government-legislative-knowledge-us",access:"key",secret_groups:[["DATA_GOV_API_KEY"],["CONGRESS_API_KEY"]],adapter:"catalog-only",integration:"official-rest-v3",scope:"bills-members-amendments-committees-congressional-data",registration_url:"https://api.congress.gov/sign-up"},
  regulations_gov:{category:"government-regulatory-knowledge-us",access:"key",secret_groups:[["DATA_GOV_API_KEY"],["REGULATIONS_GOV_API_KEY"]],adapter:"catalog-only",integration:"official-rest",scope:"rulemaking-documents-dockets-comments",registration_url:"https://api.data.gov/signup/"},
  anthropic_mcp_examples:{category:"mcp-reference",access:"public",adapter:"catalog-only"}
};

function anyGroup(env,groups){return groups?.some(g=>g.every(k=>Boolean(env[k])))}
export function statusFor(env,name){
  const p=CATALOG[name];if(!p)return null;
  let configured=false;
  if(["public","external-runtime","external-mcp","external-source"].includes(p.access))configured=true;
  else if(p.secret_groups)configured=anyGroup(env,p.secret_groups);
  else if(p.access==="optional-key")configured=true;
  else configured=(p.secrets||[]).every(k=>Boolean(env[k]));
  return{configured,category:p.category,access:p.access,adapter:p.adapter,live_adapter:p.adapter!=="catalog-only"};
}
export function allStatuses(env){return Object.fromEntries(Object.keys(CATALOG).map(k=>[k,statusFor(env,k)]))}
