export const SPLUS_CATALOG={
 splus_knowledge:{category:"splus-knowledge-information-discovery",access:"public",optional_secrets:["CROSSREF_MAILTO","CONTACT_EMAIL"],adapter:"splus.knowledge",integration:"Crossref+DataCite+EuropePMC",scope:"scholarly-works-dois-research-data-medical-case-report-discovery",endpoint:"fixed-official-apis",priority:"S+",arbitrary_url:false},
 splus_biomed:{category:"splus-medical-biomedical-clinical",access:"public",optional_secrets:["NCBI_API_KEY","OPENFDA_API_KEY","NCBI_EMAIL"],adapter:"splus.biomed",integration:"NCBI+WHO-GHO+EMBL-EBI+openFDA+controlled-clinical-registry+medical-model-registry",scope:"literature-genes-proteins-health-indicators-drug-device-safety-medical-cases-controlled-clinical-data-medical-model-metadata",endpoint:"fixed-official-apis",priority:"S+",arbitrary_url:false},
 splus_precision_biomed:{category:"splus-precision-medicine-cancer-genomics-structure",access:"public",adapter:"splus.precision-biomed",integration:"NCI-GDC+GTEx-v2+AlphaFold-DB+Human-Protein-Atlas",scope:"case-level-cancer-metadata-tissue-expression-eqtl-protein-structure-protein-expression",endpoint:"fixed-official-apis",priority:"S+",controlled_data:"public-metadata-only-unless-separately-authorized",arbitrary_url:false},
 splus_biomed_knowledge:{category:"splus-drug-target-gene-pathway-protein-structure-knowledge",access:"public",adapter:"splus.biomed-knowledge",integration:"PubChem+ChEMBL+Ensembl+Reactome+RCSB-PDB+UniProt",scope:"compound-properties-drug-target-bioactivity-gene-xrefs-pathways-participants-protein-structure-function",endpoint:"fixed-official-apis",priority:"S+",relationship_chain:"compound-to-drug-to-target-to-gene-to-pathway-to-protein-to-structure",arbitrary_url:false},
 splus_macro:{category:"splus-global-macro-economic-statistics",access:"public",adapter:"splus.macro",integration:"OECD+Eurostat+IMF+BIS",scope:"economy-industry-trade-labor-prices-tax-finance-banking-credit-property-derivatives-policy",endpoint:"fixed-official-apis",priority:"S+",arbitrary_url:false},
 splus_macro_fusion:{category:"splus-authoritative-macro-normalization-validation",access:"public",adapter:"splus.macro-fusion",integration:"World-Bank+IMF-DataMapper-v2+official-provenance",scope:"canonical-gdp-growth-inflation-unemployment-cross-source-comparison-and-disagreement-flags",endpoint:"fixed-official-apis",priority:"S+",validation:"differences-are-flags-not-automatic-truth-ranking",arbitrary_url:false},
 splus_us_official:{category:"splus-us-official-economy-industry-health-spending",access:"public",optional_secrets:["CENSUS_API_KEY","BLS_API_KEY","BEA_API_KEY","USDA_NASS_API_KEY"],adapter:"splus.us-official",integration:"Census+BLS+BEA+USDA-NASS+NIH-RePORTER+CMS+USAspending",scope:"population-households-labor-prices-gdp-industry-regional-agriculture-biomedical-funding-healthcare-contracts-grants",endpoint:"fixed-official-apis",priority:"S+",auth_note:"catalog and public subproviders are always available; keyed subproviders fail closed individually",arbitrary_url:false},
 splus_global_events_trade_health:{category:"splus-global-events-trade-humanitarian-public-health",access:"public",optional_secrets:["UN_COMTRADE_API_KEY","CDC_APP_TOKEN","RELIEFWEB_APPNAME"],adapter:"splus.global-events-trade-health",integration:"UN-Comtrade+ReliefWeb+GDACS+CDC-Open-Data",scope:"international-trade-humanitarian-reports-disaster-alerts-public-health-surveillance",endpoint:"fixed-official-apis",priority:"S+",auth_note:"public preview/CDC/GDACS paths remain usable; full Comtrade and ReliefWeb operations enforce their required credentials/config",arbitrary_url:false},
 splus_corporate_markets_procurement:{category:"splus-corporate-disclosure-positioning-procurement",access:"public",optional_secrets:["COMPANIES_HOUSE_API_KEY","OPENDART_API_KEY","CFTC_APP_TOKEN"],adapter:"splus.corporate-markets-procurement",integration:"Companies-House+OpenDART+CFTC-COT+TED",scope:"company-registry-company-profile-corporate-disclosures-financial-accounts-regulatory-positioning-public-procurement",endpoint:"fixed-official-apis",priority:"S+",auth_note:"CFTC and TED remain public; Companies House and OpenDART fail closed individually without their keys",arbitrary_url:false},
 splus_risk:{category:"splus-security-entity-geohazard",access:"public",optional_secrets:["NVD_API_KEY"],adapter:"splus.risk",integration:"NIST-NVD+CISA-KEV+GLEIF+USGS",scope:"cve-known-exploited-vulnerabilities-legal-entities-earthquakes",endpoint:"fixed-official-apis",priority:"S+",arbitrary_url:false},
 splus_china:{category:"splus-china-mainland-official-intelligence",access:"public",adapter:"splus.china",integration:"official-fixed-source-catalog+bounded-page-reader",scope:"macro-money-fiscal-trade-business-securities-futures-disclosures-policy-law-health-drugs",endpoint:"fixed-official-domains-only",priority:"S+",arbitrary_url:false},
 splus_opportunity:{category:"splus-china-business-opportunity-quant-research",access:"public",adapter:"splus.opportunity",integration:"fixed-China-official-pages+curated-quant-source-routing",scope:"procurement-awards-patents-industry-energy-healthcare-environment-standards-credit+factor-fixed-income-macro-financial-research",endpoint:"fixed-official-domains+local-registry",priority:"S+",safety:"legitimate-market-research-only",arbitrary_url:false},
 splus_decision:{category:"splus-business-decision-strategy-case-method-library",access:"public",adapter:"splus.decision",integration:"curated-method-and-case-routing-library",scope:"decision-science-business-strategy-negotiation-game-theory-operations-research-quant-validation-case-evidence",endpoint:"local-curated-registry",priority:"S+",safety:"legitimate-analysis-only",arbitrary_url:false}
};
